=== PokeAPI/api-data/data/schema/v2/ability/$id/index.json
{
    "$schema": "http://json-schema.org/schema#",
    "properties": {
        "effect_changes": {
            "items": {
                "properties": {
                    "effect_entries": {
                        "items": {
                            "properties": {
                                "effect": {
                                    "type": "string"
                                },
                                "language": {
                                    "$ref": "/schema/v2/named_api_resource.json"
                                }
                            },
                            "required": [
                                "effect",
                                "language"
                            ],
                            "type": "object"
                        },
                        "type": "array"
                    },
                    "version_group": {
                        "$ref": "/schema/v2/named_api_resource.json"
                    }
                },
                "required": [
                    "effect_entries",
                    "version_group"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "effect_entries": {
            "items": {
                "properties": {
                    "effect": {
                        "type": "string"
                    },
                    "language": {
                        "$ref": "/schema/v2/named_api_resource.json"
                    },
                    "short_effect": {
                        "type": "string"
                    }
                },
                "required": [
                    "effect",
                    "language",
                    "short_effect"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "flavor_text_entries": {
            "items": {
                "properties": {
                    "flavor_text": {
                        "type": "string"
                    },
                    "language": {
                        "$ref": "/schema/v2/named_api_resource.json"
                    },
                    "version_group": {
                        "$ref": "/schema/v2/named_api_resource.json"
                    }
                },
                "required": [
                    "flavor_text",
                    "language",
                    "version_group"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "generation": {
            "$ref": "/schema/v2/named_api_resource.json"
        },
        "id": {
            "type": "integer"
        },
        "is_main_series": {
            "type": "boolean"
        },
        "name": {
            "type": "string"
        },
        "names": {
            "items": {
                "properties": {
                    "language": {
                        "$ref": "/schema/v2/named_api_resource.json"
                    },
                    "name": {
                        "type": "string"
                    }
                },
                "required": [
                    "language",
                    "name"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "pokemon": {
            "items": {
                "properties": {
                    "is_hidden": {
                        "type": "boolean"
                    },
                    "pokemon": {
                        "$ref": "/schema/v2/named_api_resource.json"
                    },
                    "slot": {
                        "type": "integer"
                    }
                },
                "required": [
                    "is_hidden",
                    "pokemon",
                    "slot"
                ],
                "type": "object"
            },
            "type": "array"
        }
    },
    "required": [
        "effect_changes",
        "effect_entries",
        "flavor_text_entries",
        "generation",
        "id",
        "is_main_series",
        "name",
        "names",
        "pokemon"
    ],
    "type": "object"
}

=== PokeAPI/api-data/data/api/v2/ability/52/index.json
{
    "effect_changes": [
        {
            "effect_entries": [
                {
                    "effect": "N'a pas d'effet en dehors du combat.",
                    "language": {
                        "name": "fr",
                        "url": "/api/v2/language/5/"
                    }
                },
                {
                    "effect": "Hat au\u00dferhalb vom Kampf keinen Effekt.",
                    "language": {
                        "name": "de",
                        "url": "/api/v2/language/6/"
                    }
                },
                {
                    "effect": "Has no overworld effect.",
                    "language": {
                        "name": "en",
                        "url": "/api/v2/language/9/"
                    }
                }
            ],
            "version_group": {
                "name": "emerald",
                "url": "/api/v2/version-group/6/"
            }
        },
        {
            "effect_entries": [
                {
                    "effect": "Double le rayon d'action de Coupe dans le monde ext\u00e9rieur si un Pok\u00e9mon de l'\u00e9quipe a ce talent.",
                    "language": {
                        "name": "fr",
                        "url": "/api/v2/language/5/"
                    }
                },
                {
                    "effect": "Verdoppelt den Radius in dem Zerschneider Gras entfernt, wenn irgendein Pok\u00e9mon im Team diese F\u00e4higkeit hat.",
                    "language": {
                        "name": "de",
                        "url": "/api/v2/language/6/"
                    }
                },
                {
                    "effect": "Doubles Cut's grass-cutting radius on the overworld if any party Pok\u00e9mon has this ability.",
                    "language": {
                        "name": "en",
                        "url": "/api/v2/language/9/"
                    }
                }
            ],
            "version_group": {
                "name": "diamond-pearl",
                "url": "/api/v2/version-group/8/"
            }
        }
    ],
    "effect_entries": [
        {
            "effect": "L'Attaque de ce Pok\u00e9mon ne peut pas \u00eatre baiss\u00e9e par d'autres Pok\u00e9mon.\n\nCe talent n'emp\u00eache pas les baisses d'Attaque autres que les modifications de stat, telles que la baisse d'Attaque de la br\u00fblure.  Ce Pok\u00e9mon peut toujours recevoir des modifications d'Attaque n\u00e9gatives via Permuc\u0153ur ou Permuforce.",
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "short_effect": "Emp\u00eache l'Attaque d'\u00eatre baiss\u00e9e."
        },
        {
            "effect": "Pok\u00e9mon mit dieser F\u00e4higkeit kann der Angriff nicht gesenkt werden.\n\nDie F\u00e4higkeit verhindert nur Statuswertver\u00e4nderungen, der verminderte Angriff durch Verbrennung wird nicht verhindert. Pok\u00e9mon mit dieser F\u00e4higkeit k\u00f6nnen trotzdem negative Genauigkeit durch Statustausch oder Krafttausch \u00fcbertragen werden.",
            "language": {
                "name": "de",
                "url": "/api/v2/language/6/"
            },
            "short_effect": "Verhindert das Absenken des Angriffs."
        },
        {
            "effect": "This Pok\u00e9mon's Attack cannot be lowered by other Pok\u00e9mon.\n\nThis ability does not prevent any Attack losses other than stat modifiers, such as the Attack cut from a burn.  This Pok\u00e9mon can still be passed negative Attack modifiers through Heart Swap or Power Swap.",
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "short_effect": "Prevents Attack from being lowered by other Pok\u00e9mon."
        }
    ],
    "flavor_text_entries": [
        {
            "flavor_text": "Emp\u00eache r\u00e9duction ATTAQUE.",
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "version_group": {
                "name": "ruby-sapphire",
                "url": "/api/v2/version-group/5/"
            }
        },
        {
            "flavor_text": "Prevents ATTACK reduction.",
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "version_group": {
                "name": "ruby-sapphire",
                "url": "/api/v2/version-group/5/"
            }
        },
        {
            "flavor_text": "Emp\u00eache r\u00e9duction ATTAQUE.",
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "version_group": {
                "name": "emerald",
                "url": "/api/v2/version-group/6/"
            }
        },
        {
            "flavor_text": "Prevents ATTACK reduction.",
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "version_group": {
                "name": "emerald",
                "url": "/api/v2/version-group/6/"
            }
        },
        {
            "flavor_text": "Emp\u00eache r\u00e9duction ATTAQUE.",
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "version_group": {
                "name": "firered-leafgreen",
                "url": "/api/v2/version-group/7/"
            }
        },
        {
            "flavor_text": "Prevents ATTACK reduction.",
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "version_group": {
                "name": "firered-leafgreen",
                "url": "/api/v2/version-group/7/"
            }
        },
        {
            "flavor_text": "Emp\u00eache la r\u00e9duction de l'Attaque.",
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "version_group": {
                "name": "diamond-pearl",
                "url": "/api/v2/version-group/8/"
            }
        },
        {
            "flavor_text": "Prevents the Attack stat\nfrom being lowered.",
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "version_group": {
                "name": "diamond-pearl",
                "url": "/api/v2/version-group/8/"
            }
        },
        {
            "flavor_text": "Emp\u00eache la r\u00e9duction de l'Attaque.",
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "version_group": {
                "name": "platinum",
                "url": "/api/v2/version-group/9/"
            }
        },
        {
            "flavor_text": "Prevents the Attack stat\nfrom being lowered.",
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "version_group": {
                "name": "platinum",
                "url": "/api/v2/version-group/9/"
            }
        },
        {
            "flavor_text": "Emp\u00eache la r\u00e9duction de l'Attaque.",
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "version_group": {
                "name": "heartgold-soulsilver",
                "url": "/api/v2/version-group/10/"
            }
        },
        {
            "flavor_text": "Prevents the Attack\nstat from being lowered.",
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "version_group": {
                "name": "heartgold-soulsilver",
                "url": "/api/v2/version-group/10/"
            }
        },
        {
            "flavor_text": "Emp\u00eache la r\u00e9duction de l'Attaque.",
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "version_group": {
                "name": "black-white",
                "url": "/api/v2/version-group/11/"
            }
        },
        {
            "flavor_text": "Prevents other Pok\u00e9mon\nfrom lowering Attack stat.",
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "version_group": {
                "name": "black-white",
                "url": "/api/v2/version-group/11/"
            }
        },
        {
            "flavor_text": "Emp\u00eache la r\u00e9duction de l'Attaque.",
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "version_group": {
                "name": "xd",
                "url": "/api/v2/version-group/13/"
            }
        },
        {
            "flavor_text": "Emp\u00eache la r\u00e9duction de l'Attaque.",
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "version_group": {
                "name": "black-2-white-2",
                "url": "/api/v2/version-group/14/"
            }
        },
        {
            "flavor_text": "Prevents other Pok\u00e9mon\nfrom lowering Attack stat.",
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "version_group": {
                "name": "black-2-white-2",
                "url": "/api/v2/version-group/14/"
            }
        },
        {
            "flavor_text": "\u3042\u3044\u3066\u306b\u3000\u3053\u3046\u3052\u304d\u3092\n\u3055\u3052\u3089\u308c\u306a\u3044\u3002",
            "language": {
                "name": "ja-hrkt",
