=== PokeAPI/api-data/data/schema/v2/encounter-method/$id/index.json
{
    "$schema": "http://json-schema.org/schema#",
    "properties": {
        "id": {
            "type": "integer"
        },
        "name": {
            "type": "string"
        },
        "names": {
            "items": {
                "$ref": "/schema/v2/name.json"
            },
            "type": "array"
        },
        "order": {
            "type": "integer"
        }
    },
    "required": [
        "id",
        "name",
        "names",
        "order"
    ],
    "type": "object"
}

=== PokeAPI/api-data/data/api/v2/encounter-method/5/index.json
{
    "id": 5,
    "name": "surf",
    "names": [
        {
            "language": {
                "name": "de",
                "url": "/api/v2/language/6/"
            },
            "name": "Surfen"
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Surfing"
        },
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "En surfant"
        }
    ],
    "order": 14
}
