=== PokeAPI/api-data/data/schema/v2/location-area/$id/index.json
{
    "$schema": "http://json-schema.org/schema#",
    "properties": {
        "encounter_method_rates": {
            "items": {
                "properties": {
                    "encounter_method": {
                        "$ref": "/schema/v2/named_api_resource.json"
                    },
                    "version_details": {
                        "items": {
                            "properties": {
                                "rate": {
                                    "type": "integer"
                                },
                                "version": {
                                    "$ref": "/schema/v2/named_api_resource.json"
                                }
                            },
                            "required": [
                                "rate",
                                "version"
                            ],
                            "type": "object"
                        },
                        "type": "array"
                    }
                },
                "required": [
                    "encounter_method",
                    "version_details"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "game_index": {
            "type": "integer"
        },
        "id": {
            "type": "integer"
        },
        "location": {
            "$ref": "/schema/v2/named_api_resource.json"
        },
        "name": {
            "type": "string"
        },
        "names": {
            "items": {
                "$ref": "/schema/v2/name.json"
            },
            "type": "array"
        },
        "pokemon_encounters": {
            "items": {
                "properties": {
                    "pokemon": {
                        "$ref": "/schema/v2/named_api_resource.json"
                    },
                    "version_details": {
                        "items": {
                            "$ref": "/schema/v2/version_encounter_detail.json"
                        },
                        "type": "array"
                    }
                },
                "required": [
                    "pokemon",
                    "version_details"
                ],
                "type": "object"
            },
            "type": "array"
        }
    },
    "required": [
        "encounter_method_rates",
        "game_index",
        "id",
        "location",
        "name",
        "names",
        "pokemon_encounters"
    ],
    "type": "object"
}

=== PokeAPI/api-data/data/api/v2/location-area/1340/index.json
{
    "encounter_method_rates": [
        {
            "encounter_method": {
                "name": "hidden-grotto",
                "url": "/api/v2/encounter-method/54/"
            },
            "version_details": [
                {
                    "rate": 20,
                    "version": {
                        "name": "black-2",
                        "url": "/api/v2/version/21/"
                    }
                },
                {
                    "rate": 20,
                    "version": {
                        "name": "white-2",
                        "url": "/api/v2/version/22/"
                    }
                }
            ]
        }
    ],
    "game_index": 15,
    "id": 1340,
    "location": {
        "name": "unova-route-2",
        "url": "/api/v2/location/357/"
    },
    "name": "unova-route-2-hidden-grotto",
    "names": [
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Route 2 (Hidden Grotto)"
        }
    ],
    "pokemon_encounters": [
        {
            "pokemon": {
                "name": "nidoran-f",
                "url": "/api/v2/pokemon/29/"
            },
            "version_details": [
                {
                    "encounter_details": [
                        {
                            "chance": 10,
                            "condition_values": [],
                            "max_level": 59,
                            "method": {
                                "name": "hidden-grotto",
                                "url": "/api/v2/encounter-method/54/"
                            },
                            "min_level": 55
                        }
                    ],
                    "max_chance": 10,
                    "version": {
                        "name": "black-2",
                        "url": "/api/v2/version/21/"
                    }
                },
                {
                    "encounter_details": [
                        {
                            "chance": 10,
                            "condition_values": [],
                            "max_level": 59,
                            "method": {
                                "name": "hidden-grotto",
                                "url": "/api/v2/encounter-method/54/"
                            },
                            "min_level": 55
                        }
                    ],
                    "max_chance": 10,
                    "version": {
                        "name": "white-2",
                        "url": "/api/v2/version/22/"
                    }
                }
            ]
        },
        {
            "pokemon": {
                "name": "nidoran-m",
                "url": "/api/v2/pokemon/32/"
            },
            "version_details": [
                {
                    "encounter_details": [
                        {
                            "chance": 10,
                            "condition_values": [],
                            "max_level": 59,
                            "method": {
                                "name": "hidden-grotto",
                                "url": "/api/v2/encounter-method/54/"
                            },
                            "min_level": 55
                        }
                    ],
                    "max_chance": 10,
                    "version": {
                        "name": "black-2",
                        "url": "/api/v2/version/21/"
                    }
                },
                {
                    "encounter_details": [
                        {
                            "chance": 10,
                            "condition_values": [],
                            "max_level": 59,
                            "method": {
                                "name": "hidden-grotto",
                                "url": "/api/v2/encounter-method/54/"
                            },
                            "min_level": 55
                        }
                    ],
                    "max_chance": 10,
                    "version": {
                        "name": "white-2",
                        "url": "/api/v2/version/22/"
                    }
                }
            ]
        },
        {
            "pokemon": {
                "name": "granbull",
                "url": "/api/v2/pokemon/210/"
            },
            "version_details": [
                {
                    "encounter_details": [
                        {
                            "chance": 5,
                            "condition_values": [],
                            "max_level": 59,
                            "method": {
                                "name": "hidden-grotto",
                                "url": "/api/v2/encounter-method/54/"
                            },
                            "min_level": 55
                        }
                    ],
                    "max_chance": 5,
                    "version": {
                        "name": "black-2",
                        "url": "/api/v2/version/21/"
                    }
                },
                {
                    "encounter_details": [
                        {
                            "chance": 5,
                            "condition_values": [],
                            "max_level": 59,
                            "method": {
                                "name": "hidden-grotto",
                                "url": "/api/v2/encounter-method/54/"
                            },
                            "min_level": 55
                        }
                    ],
                    "max_chance": 5,
                    "version": {
                        "name": "white-2",
                        "url": "/api/v2/version/22/"
                    }
                }
            ]
        },
        {
            "pokemon": {
                "name": "watchog",
                "url": "/api/v2/pokemon/505/"
            },
            "version_details": [
                {
                    "encounter_details": [
                        {
                            "chance": 75,
                            "condition_values": [],
                            "max_level": 59,
                            "method": {
                                "name": "hidden-grotto",
                                "url": "/api/v2/encounter-method/54/"
                            },
                            "min_level": 55
                        }
                    ],
                    "max_chance": 75,
                    "version": {
                        "name": "black-2",
                        "url": "/api/v2/version/21/"
                    }
                },
                {
                    "encounter_details": [
                        {
                            "chance": 75,
                            "condition_values": [],
                            "max_level": 59,
                            "method": {
                                "name": "hidden-grotto",
                                "url": "/api/v2/encounter-method/54/"
                            },
                            "min_level": 55
                        }
                    ],
                    "max_chance": 75,
                    "version": {
                        "name": "white-2",
                        "url": "/api/v2/version/22/"
                    }
                }
            ]
        }
    ]
}

=== PokeAPI/api-data/data/api/v2/location-area/1173/index.json
{
    "encounter_method_rates": [],
    "game_index": 0,
    "id": 1173,
    "location": {
        "name": "twist-mountain",
        "url": "/api/v2/location/380/"
    },
    "name": "twist-mountain-b4f",
    "names": [],
    "pokemon_encounters": [
        {
            "pokemon": {
                "name": "regigigas",
                "url": "/api/v2/pokemon/486/"
            },
            "version_details": [
                {
                    "encounter_details": [
                        {
                            "chance": 100,
                            "condition_values": [
                                {
                                    "name": "other-regirock-regice-registeel-in-party",
                                    "url": "/api/v2/encounter-condition-value/58/"
                                }
                            ],
                            "max_level": 68,
                            "method": {
                                "name": "static",
                                "url": "/api/v2/encounter-method/20/"
                            },
                            "min_level": 68
                        }
                    ],
                    "max_chance": 100,
                    "version": {
                        "name": "black-2",
                        "url": "/api/v2/version/21/"
                    }
                },
                {
                    "encounter_details": [
                        {
                            "chance": 100,
                            "condition_values": [
                                {
                                    "name": "other-regirock-regice-registeel-in-party",
                                    "url": "/api/v2/encounter-condition-value/58/"
                                }
                            ],
                            "max_level": 68,
                            "method": {
                                "name": "static",
                                "url": "/api/v2/encounter-method/20/"
                            },
                            "min_level": 68
                        }
                    ],
                    "max_chance": 100,
                    "version": {
                        "name": "white-2",
                        "url": "/api/v2/version/22/"
                    }
                }
            ]
        }
    ]
}

=== PokeAPI/api-data/data/api/v2/location-area/812/index.json
{
    "encounter_method_rates": [],
    "game_index": 0,
    "id": 812,
    "location": {
        "name": "ancient-tomb",
        "url": "/api/v2/location/583/"
    },
    "name": "ancient-tomb-area",
    "names": [
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Ancient Tomb"
        },
        {
            "language": {
                "name": "de",
                "url": "/api/v2/language/6/"
            },
            "name": "Grabmal"
        },
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "Tombeau Antique"
        }
    ],
    "pokemon_encounters": [
        {
            "pokemon": {
                "name": "registeel",
                "url": "/api/v2/pokemon/379/"
            },
            "version_details": [
                {
                    "encounter_details": [
                        {
                            "chance": 100,
                            "condition_values": [],
                            "max_level": 40,
                            "method": {
                                "name": "static",
                                "url": "/api/v2/encounter-method/20/"
                            },
                            "min_level": 40
                        }
                    ],
                    "max_chance": 100,
                    "version": {
                        "name": "ruby",
                        "url": "/api/v2/version/7/"
                    }
                },
                {
                    "encounter_details": [
                        {
                            "chance": 100,
                            "condition_values": [],
                            "max_level": 40,
                            "method": {
                                "name": "static",
                                "url": "/api/v2/encounter-method/20/"
                            },
                            "min_level": 40
                        }
                    ],
                    "max_chance": 100,
                    "version": {
                        "name": "sapphire",
                        "url": "/api/v2/version/8/"
                    }
                },
                {
                    "encounter_details": [
                        {
                            "chance": 100,
                            "condition_values": [],
                            "max_level": 40,
                            "method": {
                                "name": "static",
                                "url": "/api/v2/encounter-method/20/"
                            },
                            "min_level": 40
                        }
                    ],
                    "max_chance": 100,
                    "version": {
                        "name": "emerald",
                        "url": "/api/v2/version/9/"
                    }
                },
                {
                    "encounter_details": [
                        {
                            "chance": 100,
                            "condition_values": [],
                            "max_level": 40,
                            "method": {
                                "name": "static",
                                "url": "/api/v2/encounter-method/20/"
                            },
                            "min_level": 40
                        }
                    ],
                    "max_chance": 100,
                    "version": {
                        "name": "omega-ruby",
                        "url": "/api/v2/version/25/"
                    }
                },
                {
                    "encounter_details": [
                        {
                            "chance": 100,
                            "condition_values": [],
                            "max_level": 40,
                            "method": {
                                "name": "static",
                                "url": "/api/v2/encounter-method/20/"
                            },
                            "min_level": 40
                        }
                    ],
                    "max_chance": 100,
                    "version": {
                        "name": "alpha-sapphire",
                        "url": "/api/v2/version/26/"
                    }
                }
            ]
        }
    ]
}

=== PokeAPI/api-data/data/api/v2/location-area/1289/index.json
{
    "encounter_method_rates": [],
    "game_index": 0,
    "id": 1289,
    "location": {
        "name": "citadark-isle",
        "url": "/api/v2/location/1112/"
    },
    "name": "citadark-isle-dome-exterior",
    "names": [
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Citadark Isle Dome Exterior"
        }
    ],
    "pokemon_encounters": [
        {
            "pokemon": {
                "name": "poliwrath",
                "url": "/api/v2/pokemon/62/"
            },
            "version_details": [
                {
                    "encounter_details": [
                        {
                            "chance": 100,
                            "condition_values": [],
                            "max_level": 42,
                            "method": {
                                "name": "snag",
                                "url": "/api/v2/encounter-method/51/"
                            },
                            "min_level": 42
                        }
                    ],
                    "max_chance": 100,
                    "version": {
                        "name": "xd",
                        "url": "/api/v2/version/20/"
                    }
                }
            ]
        },
        {
            "pokemon": {
                "name": "starmie",
                "url": "/api/v2/pokemon/121/"
            },
            "version_details": [
                {
                    "encounter_details": [
                        {
                            "chance": 100,
                            "condition_values": [],
                            "max_level": 41,
                            "method": {
                                "name": "snag",
                                "url": "/api/v2/encounter-method/51/"
                            },
                            "min_level": 41
                        }
                    ],
                    "max_chance": 100,
                    "version": {
                        "name": "xd",
                        "url": "/api/v2/version/20/"
                    }
                }
            ]
        },
        {
            "pokemon": {
                "name": "mr-mime",
                "url": "/api/v2/pokemon/122/"
            },
            "version_details": [
                {
                    "encounter_details": [
                        {
                            "chance": 100,
                            "condition_values": [],
                            "max_level": 42,
                            "method": {
                                "name": "snag",
                                "url": "/api/v2/encounter-method/51/"
                            },
                            "min_level": 42
                        }
                    ],
                    "max_chance": 100,
                    "version": {
                        "name": "xd",
                        "url": "/api/v2/version/20/"
                    }
                }
            ]
        },
        {
            "pokemon": {
                "name": "electabuzz",
                "url": "/api/v2/pokemon/125/"
            },
            "version_details": [
                {
                    "encounter_details": [
                        {
                            "chance": 100,
                            "condition_values": [],
                            "max_level": 43,
                            "method": {
                                "name": "snag",
                                "url": "/api/v2/encounter-method/51/"
                            },
                            "min_level": 43
                        }
                    ],
                    "max_chance": 100,
                    "version": {
                        "name": "xd",
                        "url": "/api/v2/version/20/"
                    }
                }
            ]
        },
        {
            "pokemon": {
                "name": "snorlax",
                "url": "/api/v2/pokemon/143/"
            },
            "version_details": [
                {
                    "encounter_details": [
                        {
                            "chance": 100,
                            "condition_values": [],
                            "max_level": 43,
                            "method": {
                                "name": "snag",
                                "url": "/api/v2/encounter-method/51/"
                            },
                            "min_level": 43
                        }
                    ],
                    "max_chance": 100,
                    "version": {
                        "name": "xd",
                        "url": "/api/v2/version/20/"
                    }
                }
            ]
        },
        {
            "pokemon": {
                "name": "swellow",
                "url": "/api/v2/pokemon/277/"
            },
            "version_details": [
                {
                    "encounter_details": [
                        {
                            "chance": 100,
                            "condition_values": [],
                            "max_level": 43,
                            "method": {
                                "name": "snag",
                                "url": "/api/v2/encounter-method/51/"
                            },
                            "min_level": 43
                        }
                    ],
                    "max_chance": 100,
                    "version": {
                        "name": "xd",
                        "url": "/api/v2/version/20/"
                    }
                }
            ]
        },
        {
            "pokemon": {
                "name": "solrock",
                "url": "/api/v2/pokemon/338/"
            },
            "version_details": [
                {
                    "encounter_details": [
                        {
                            "chance": 100,
                            "condition_values": [],
                            "max_level": 41,
                            "method": {
                                "name": "snag",
                                "url": "/api/v2/encounter-method/51/"
                            },
                            "min_level": 41
                        }
                    ],
                    "max_chance": 100,
                    "version": {
                        "name": "xd",
                        "url": "/api/v2/version/20/"
                    }
                }
            ]
        }
    ]
}
