=== PokeAPI/api-data/data/schema/v2/pokemon-species/$id/index.json
{
    "$schema": "http://json-schema.org/schema#",
    "properties": {
        "base_happiness": {
            "type": "integer"
        },
        "capture_rate": {
            "type": "integer"
        },
        "color": {
            "$ref": "/schema/v2/named_api_resource.json"
        },
        "egg_groups": {
            "items": {
                "$ref": "/schema/v2/named_api_resource.json"
            },
            "type": "array"
        },
        "evolution_chain": {
            "$ref": "/schema/v2/api_resource.json"
        },
        "evolves_from_species": {
            "anyOf": [
                {
                    "type": "null"
                },
                {
                    "$ref": "/schema/v2/named_api_resource.json"
                }
            ]
        },
        "flavor_text_entries": {
            "items": {
                "properties": {
                    "flavor_text": {
                        "type": "string"
                    },
                    "language": {
                        "$ref": "/schema/v2/named_api_resource.json"
                    },
                    "version": {
                        "$ref": "/schema/v2/named_api_resource.json"
                    }
                },
                "required": [
                    "flavor_text",
                    "language",
                    "version"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "form_descriptions": {
            "items": {
                "properties": {
                    "description": {
                        "type": "string"
                    },
                    "language": {
                        "$ref": "/schema/v2/named_api_resource.json"
                    }
                },
                "required": [
                    "description",
                    "language"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "forms_switchable": {
            "type": "boolean"
        },
        "gender_rate": {
            "type": "integer"
        },
        "genera": {
            "items": {
                "properties": {
                    "genus": {
                        "type": "string"
                    },
                    "language": {
                        "$ref": "/schema/v2/named_api_resource.json"
                    }
                },
                "required": [
                    "genus",
                    "language"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "generation": {
            "$ref": "/schema/v2/named_api_resource.json"
        },
        "growth_rate": {
            "$ref": "/schema/v2/named_api_resource.json"
        },
        "habitat": {
            "anyOf": [
                {
                    "type": "null"
                },
                {
                    "$ref": "/schema/v2/named_api_resource.json"
                }
            ]
        },
        "has_gender_differences": {
            "type": "boolean"
        },
        "hatch_counter": {
            "type": "integer"
        },
        "id": {
            "type": "integer"
        },
        "is_baby": {
            "type": "boolean"
        },
        "is_legendary": {
            "type": "boolean"
        },
        "is_mythical": {
            "type": "boolean"
        },
        "name": {
            "type": "string"
        },
        "names": {
            "items": {
                "properties": {
                    "language": {
                        "$ref": "/schema/v2/named_api_resource.json"
                    },
                    "name": {
                        "type": "string"
                    }
                },
                "required": [
                    "language",
                    "name"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "order": {
            "type": "integer"
        },
        "pal_park_encounters": {
            "items": {
                "properties": {
                    "area": {
                        "$ref": "/schema/v2/named_api_resource.json"
                    },
                    "base_score": {
                        "type": "integer"
                    },
                    "rate": {
                        "type": "integer"
                    }
                },
                "required": [
                    "area",
                    "base_score",
                    "rate"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "pokedex_numbers": {
            "items": {
                "properties": {
                    "entry_number": {
                        "type": "integer"
                    },
                    "pokedex": {
                        "$ref": "/schema/v2/named_api_resource.json"
                    }
                },
                "required": [
                    "entry_number",
                    "pokedex"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "shape": {
            "$ref": "/schema/v2/named_api_resource.json"
        },
        "varieties": {
            "items": {
                "properties": {
                    "is_default": {
                        "type": "boolean"
                    },
                    "pokemon": {
                        "$ref": "/schema/v2/named_api_resource.json"
                    }
                },
                "required": [
                    "is_default",
                    "pokemon"
                ],
                "type": "object"
            },
            "type": "array"
        }
    },
    "required": [
        "base_happiness",
        "capture_rate",
        "color",
        "egg_groups",
        "evolution_chain",
        "evolves_from_species",
        "flavor_text_entries",
        "form_descriptions",
        "forms_switchable",
        "gender_rate",
        "genera",
        "generation",
        "growth_rate",
        "habitat",
        "has_gender_differences",
        "hatch_counter",
        "id",
        "is_baby",
        "is_legendary",
        "is_mythical",
        "name",
        "names",
        "order",
        "pal_park_encounters",
        "pokedex_numbers",
        "shape",
        "varieties"
    ],
    "type": "object"
}

=== PokeAPI/api-data/data/api/v2/pokemon-species/1007/index.json
{
    "base_happiness": 0,
    "capture_rate": 3,
    "color": {
        "name": "red",
        "url": "/api/v2/pokemon-color/8/"
    },
    "egg_groups": [
        {
            "name": "no-eggs",
            "url": "/api/v2/egg-group/15/"
        }
    ],
    "evolution_chain": {
        "url": "/api/v2/evolution-chain/535/"
    },
    "evolves_from_species": null,
    "flavor_text_entries": [
        {
            "flavor_text": "This seems to be the Winged King mentioned in an old expedition journal. It was said to have split the land with its bare fists.",
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "version": {
                "name": "scarlet",
                "url": "/api/v2/version/40/"
            }
        },
        {
            "flavor_text": "This Pok\u00e9mon resembles Cyclizar, but it is far burlier and more ferocious. Nothing is known about its ecology or other features.",
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "version": {
                "name": "violet",
                "url": "/api/v2/version/41/"
            }
        }
    ],
    "form_descriptions": [],
    "forms_switchable": false,
    "gender_rate": -1,
    "genera": [
        {
            "genus": "\u30d1\u30e9\u30c9\u30c3\u30af\u30b9\u30dd\u30b1\u30e2\u30f3",
            "language": {
                "name": "ja-hrkt",
                "url": "/api/v2/language/1/"
            }
        },
        {
            "genus": "\ud328\ub7ec\ub3c5\uc2a4\ud3ec\ucf13\ubaac",
            "language": {
                "name": "ko",
                "url": "/api/v2/language/3/"
            }
        },
        {
            "genus": "\u6096\u8b2c\u5bf6\u53ef\u5922",
            "language": {
                "name": "zh-hant",
                "url": "/api/v2/language/4/"
            }
        },
        {
            "genus": "Paradoxe",
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            }
        },
        {
            "genus": "Paradox",
            "language": {
                "name": "de",
                "url": "/api/v2/language/6/"
            }
        },
        {
            "genus": "Paradox Pok\u00e9mon",
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            }
        },
        {
            "genus": "\u6096\u8c2c\u5b9d\u53ef\u68a6",
            "language": {
                "name": "zh-hans",
                "url": "/api/v2/language/12/"
            }
        }
    ],
    "generation": {
        "name": "generation-ix",
        "url": "/api/v2/generation/9/"
    },
    "growth_rate": {
        "name": "slow",
        "url": "/api/v2/growth-rate/1/"
    },
    "habitat": null,
    "has_gender_differences": false,
    "hatch_counter": 50,
    "id": 1007,
    "is_baby": false,
    "is_legendary": true,
    "is_mythical": false,
    "name": "koraidon",
    "names": [
        {
            "language": {
                "name": "ja-hrkt",
                "url": "/api/v2/language/1/"
            },
            "name": "\u30b3\u30e9\u30a4\u30c9\u30f3"
        },
        {
            "language": {
                "name": "ja-roma",
                "url": "/api/v2/language/2/"
            },
            "name": "Koraidon"
        },
        {
            "language": {
                "name": "ko",
                "url": "/api/v2/language/3/"
            },
            "name": "\ucf54\ub77c\uc774\ub3c8"
        },
        {
            "language": {
                "name": "zh-hant",
                "url": "/api/v2/language/4/"
            },
            "name": "\u6545\u52d2\u9813"
        },
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "Koraidon"
        },
        {
            "language": {
                "name": "de",
                "url": "/api/v2/language/6/"
            },
            "name": "Koraidon"
        },
        {
            "language": {
                "name": "es",
                "url": "/api/v2/language/7/"
            },
            "name": "Koraidon"
        },
        {
            "language": {
                "name": "it",
                "url": "/api/v2/language/8/"
            },
            "name": "Koraidon"
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Koraidon"
        },
        {
            "language": {
                "name": "ja",
                "url": "/api/v2/language/11/"
            },
            "name": "\u30b3\u30e9\u30a4\u30c9\u30f3"
        },
        {
            "language": {
                "name": "zh-hans",
                "url": "/api/v2/language/12/"
            },
            "name": "\u6545\u52d2\u987f"
        },
        {
            "language": {
                "name": "es-419",
                "url": "/api/v2/language/14/"
            },
            "name": "Koraidon"
        }
    ],
    "order": 998,
    "pal_park_encounters": [],
    "pokedex_numbers": [
        {
            "entry_number": 1007,
            "pokedex": {
                "name": "national",
                "url": "/api/v2/pokedex/1/"
            }
        },
        {
            "entry_number": 399,
            "pokedex": {
                "name": "paldea",
                "url": "/api/v2/pokedex/31/"
            }
        }
    ],
    "shape": {
        "name": "upright",
        "url": "/api/v2/pokemon-shape/6/"
    },
    "varieties": [
        {
            "is_default": true,
            "pokemon": {
                "name": "koraidon",
                "url": "/api/v2/pokemon/1007/"
            }
        },
        {
            "is_default": false,
            "pokemon": {
                "name": "koraidon-limited-build",
                "url": "/api/v2/pokemon/10264/"
            }
        },
        {
            "is_default": false,
            "pokemon": {
                "name": "koraidon-sprinting-build",
                "url": "/api/v2/pokemon/10265/"
            }
        },
        {
            "is_default": false,
            "pokemon": {
                "name": "koraidon-swimming-build",
                "url": "/api/v2/pokemon/10266/"
            }
        },
        {
            "is_default": false,
            "pokemon": {
                "name": "koraidon-gliding-build",
                "url": "/api/v2/pokemon/10267/"
            }
        }
    ]
}

=== PokeAPI/api-data/data/api/v2/pokemon-species/989/index.json
{
    "base_happiness": 0,
    "capture_rate": 30,
    "color": {
        "name": "gray",
        "url": "/api/v2/pokemon-color/4/"
    },
    "egg_groups": [
        {
            "name": "no-eggs",
            "url": "/api/v2/egg-group/15/"
        }
    ],
    "evolution_chain": {
        "url": "/api/v2/evolution-chain/520/"
    },
    "evolves_from_species": null,
    "flavor_text_entries": [
        {
            "flavor_text": "It slightly resembles a Magneton that lived for 10,000 years and was featured in an article in a paranormal magazine.",
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "version": {
                "name": "violet",
                "url": "/api/v2/version/41/"
            }
        },
        {
            "flavor_text": "No records exist of this Pok\u00e9mon being caught. Data is lacking, but the Pok\u00e9mon\u2019s traits match up with a creature shown in an expedition journal.",
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "version": {
                "name": "scarlet",
                "url": "/api/v2/version/40/"
            }
        }
    ],
    "form_descriptions": [],
    "forms_switchable": false,
    "gender_rate": -1,
    "genera": [
        {
            "genus": "\u30d1\u30e9\u30c9\u30c3\u30af\u30b9\u30dd\u30b1\u30e2\u30f3",
            "language": {
                "name": "ja-hrkt",
                "url": "/api/v2/language/1/"
            }
        },
        {
            "genus": "\ud328\ub7ec\ub3c5\uc2a4\ud3ec\ucf13\ubaac",
            "language": {
                "name": "ko",
                "url": "/api/v2/language/3/"
            }
        },
        {
            "genus": "\u6096\u8b2c\u5bf6\u53ef\u5922",
            "language": {
                "name": "zh-hant",
                "url": "/api/v2/language/4/"
            }
        },
        {
            "genus": "Paradoxe",
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            }
        },
        {
            "genus": "Paradox",
            "language": {
                "name": "de",
                "url": "/api/v2/language/6/"
            }
        },
        {
            "genus": "Paradox Pok\u00e9mon",
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            }
        },
        {
            "genus": "\u6096\u8c2c\u5b9d\u53ef\u68a6",
            "language": {
                "name": "zh-hans",
                "url": "/api/v2/language/12/"
            }
        }
    ],
    "generation": {
        "name": "generation-ix",
        "url": "/api/v2/generation/9/"
    },
    "growth_rate": {
        "name": "slow",
        "url": "/api/v2/growth-rate/1/"
    },
    "habitat": null,
    "has_gender_differences": false,
    "hatch_counter": 50,
    "id": 989,
    "is_baby": false,
    "is_legendary": false,
    "is_mythical": false,
    "name": "sandy-shocks",
    "names": [
        {
            "language": {
                "name": "ja-hrkt",
                "url": "/api/v2/language/1/"
            },
            "name": "\u30b9\u30ca\u30ce\u30b1\u30ac\u30ef"
        },
        {
            "language": {
                "name": "ja-roma",
                "url": "/api/v2/language/2/"
            },
            "name": "Sunanokegawa"
        },
        {
            "language": {
                "name": "ko",
                "url": "/api/v2/language/3/"
            },
            "name": "\ubaa8\ub798\ud138\uac00\uc8fd"
        },
        {
            "language": {
                "name": "zh-hant",
                "url": "/api/v2/language/4/"
            },
            "name": "\u6c99\u9435\u76ae"
        },
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "Pelage-Sabl\u00e9"
        },
        {
            "language": {
                "name": "de",
                "url": "/api/v2/language/6/"
            },
            "name": "Sandfell"
        },
        {
            "language": {
                "name": "es",
                "url": "/api/v2/language/7/"
            },
            "name": "Pelarena"
        },
        {
            "language": {
                "name": "it",
                "url": "/api/v2/language/8/"
            },
            "name": "Peldisabbia"
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Sandy Shocks"
        },
        {
            "language": {
                "name": "ja",
                "url": "/api/v2/language/11/"
            },
            "name": "\u30b9\u30ca\u30ce\u30b1\u30ac\u30ef"
        },
        {
            "language": {
                "name": "zh-hans",
                "url": "/api/v2/language/12/"
            },
            "name": "\u6c99\u94c1\u76ae"
        },
        {
            "language": {
                "name": "es-419",
                "url": "/api/v2/language/14/"
            },
            "name": "Pelarena"
        }
    ],
    "order": 981,
    "pal_park_encounters": [],
    "pokedex_numbers": [
        {
            "entry_number": 989,
            "pokedex": {
                "name": "national",
                "url": "/api/v2/pokedex/1/"
            }
        },
        {
            "entry_number": 381,
            "pokedex": {
                "name": "paldea",
                "url": "/api/v2/pokedex/31/"
            }
        }
    ],
    "shape": {
        "name": "quadruped",
        "url": "/api/v2/pokemon-shape/8/"
    },
    "varieties": [
        {
            "is_default": true,
            "pokemon": {
                "name": "sandy-shocks",
                "url": "/api/v2/pokemon/989/"
            }
        }
    ]
}
