=== PokeAPI/api-data/data/schema/v2/pokemon-species/$id/index.json
{
    "$schema": "http://json-schema.org/schema#",
    "properties": {
        "base_happiness": {
            "type": "integer"
        },
        "capture_rate": {
            "type": "integer"
        },
        "color": {
            "$ref": "/schema/v2/named_api_resource.json"
        },
        "egg_groups": {
            "items": {
                "$ref": "/schema/v2/named_api_resource.json"
            },
            "type": "array"
        },
        "evolution_chain": {
            "$ref": "/schema/v2/api_resource.json"
        },
        "evolves_from_species": {
            "anyOf": [
                {
                    "type": "null"
                },
                {
                    "$ref": "/schema/v2/named_api_resource.json"
                }
            ]
        },
        "flavor_text_entries": {
            "items": {
                "properties": {
                    "flavor_text": {
                        "type": "string"
                    },
                    "language": {
                        "$ref": "/schema/v2/named_api_resource.json"
                    },
                    "version": {
                        "$ref": "/schema/v2/named_api_resource.json"
                    }
                },
                "required": [
                    "flavor_text",
                    "language",
                    "version"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "form_descriptions": {
            "items": {
                "properties": {
                    "description": {
                        "type": "string"
                    },
                    "language": {
                        "$ref": "/schema/v2/named_api_resource.json"
                    }
                },
                "required": [
                    "description",
                    "language"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "forms_switchable": {
            "type": "boolean"
        },
        "gender_rate": {
            "type": "integer"
        },
        "genera": {
            "items": {
                "properties": {
                    "genus": {
                        "type": "string"
                    },
                    "language": {
                        "$ref": "/schema/v2/named_api_resource.json"
                    }
                },
                "required": [
                    "genus",
                    "language"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "generation": {
            "$ref": "/schema/v2/named_api_resource.json"
        },
        "growth_rate": {
            "$ref": "/schema/v2/named_api_resource.json"
        },
        "habitat": {
            "anyOf": [
                {
                    "type": "null"
                },
                {
                    "$ref": "/schema/v2/named_api_resource.json"
                }
            ]
        },
        "has_gender_differences": {
            "type": "boolean"
        },
        "hatch_counter": {
            "type": "integer"
        },
        "id": {
            "type": "integer"
        },
        "is_baby": {
            "type": "boolean"
        },
        "is_legendary": {
            "type": "boolean"
        },
        "is_mythical": {
            "type": "boolean"
        },
        "name": {
            "type": "string"
        },
        "names": {
            "items": {
                "properties": {
                    "language": {
                        "$ref": "/schema/v2/named_api_resource.json"
                    },
                    "name": {
                        "type": "string"
                    }
                },
                "required": [
                    "language",
                    "name"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "order": {
            "type": "integer"
        },
        "pal_park_encounters": {
            "items": {
                "properties": {
                    "area": {
                        "$ref": "/schema/v2/named_api_resource.json"
                    },
                    "base_score": {
                        "type": "integer"
                    },
                    "rate": {
                        "type": "integer"
                    }
                },
                "required": [
                    "area",
                    "base_score",
                    "rate"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "pokedex_numbers": {
            "items": {
                "properties": {
                    "entry_number": {
                        "type": "integer"
                    },
                    "pokedex": {
                        "$ref": "/schema/v2/named_api_resource.json"
                    }
                },
                "required": [
                    "entry_number",
                    "pokedex"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "shape": {
            "$ref": "/schema/v2/named_api_resource.json"
        },
        "varieties": {
            "items": {
                "properties": {
                    "is_default": {
                        "type": "boolean"
                    },
                    "pokemon": {
                        "$ref": "/schema/v2/named_api_resource.json"
                    }
                },
                "required": [
                    "is_default",
                    "pokemon"
                ],
                "type": "object"
            },
            "type": "array"
        }
    },
    "required": [
        "base_happiness",
        "capture_rate",
        "color",
        "egg_groups",
        "evolution_chain",
        "evolves_from_species",
        "flavor_text_entries",
        "form_descriptions",
        "forms_switchable",
        "gender_rate",
        "genera",
        "generation",
        "growth_rate",
        "habitat",
        "has_gender_differences",
        "hatch_counter",
        "id",
        "is_baby",
        "is_legendary",
        "is_mythical",
        "name",
        "names",
        "order",
        "pal_park_encounters",
        "pokedex_numbers",
        "shape",
        "varieties"
    ],
    "type": "object"
}

=== PokeAPI/api-data/data/api/v2/pokemon-species/1020/index.json
{
    "base_happiness": 0,
    "capture_rate": 10,
    "color": {
        "name": "brown",
        "url": "/api/v2/pokemon-color/3/"
    },
    "egg_groups": [
        {
            "name": "no-eggs",
            "url": "/api/v2/egg-group/15/"
        }
    ],
    "evolution_chain": {
        "url": "/api/v2/evolution-chain/544/"
    },
    "evolves_from_species": null,
    "flavor_text_entries": [
        {
            "flavor_text": "There are scant few reports of this creature being sighted. One short video shows it rampaging and spouting pillars of flame.",
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "version": {
                "name": "scarlet",
                "url": "/api/v2/version/40/"
            }
        },
        {
            "flavor_text": "It resembles an eerie Pok\u00e9mon once shown in a paranormal magazine. That Pok\u00e9mon was said to be an Entei regenerated from a fossil.",
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "version": {
                "name": "violet",
                "url": "/api/v2/version/41/"
            }
        }
    ],
    "form_descriptions": [],
    "forms_switchable": false,
    "gender_rate": -1,
    "genera": [
        {
            "genus": "\u30d1\u30e9\u30c9\u30c3\u30af\u30b9\u30dd\u30b1\u30e2\u30f3",
            "language": {
                "name": "ja-hrkt",
                "url": "/api/v2/language/1/"
            }
        },
        {
            "genus": "\ud328\ub7ec\ub3c5\uc2a4\ud3ec\ucf13\ubaac",
            "language": {
                "name": "ko",
                "url": "/api/v2/language/3/"
            }
        },
        {
            "genus": "Paradoxe",
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            }
        },
        {
            "genus": "Paradox Pok\u00e9mon",
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            }
        },
        {
            "genus": "\u30d1\u30e9\u30c9\u30c3\u30af\u30b9\u30dd\u30b1\u30e2\u30f3",
            "language": {
                "name": "ja",
                "url": "/api/v2/language/11/"
            }
        }
    ],
    "generation": {
        "name": "generation-ix",
        "url": "/api/v2/generation/9/"
    },
    "growth_rate": {
        "name": "slow",
        "url": "/api/v2/growth-rate/1/"
    },
    "habitat": null,
    "has_gender_differences": false,
    "hatch_counter": 50,
    "id": 1020,
    "is_baby": false,
    "is_legendary": false,
    "is_mythical": false,
    "name": "gouging-fire",
    "names": [
        {
            "language": {
                "name": "ja-hrkt",
                "url": "/api/v2/language/1/"
            },
            "name": "\u30a6\u30ac\u30c4\u30db\u30e0\u30e9"
        },
        {
            "language": {
                "name": "ko",
                "url": "/api/v2/language/3/"
            },
            "name": "\uaff0\ub6ab\ub294\ud654\uc5fc"
        },
        {
            "language": {
                "name": "zh-hant",
                "url": "/api/v2/language/4/"
            },
            "name": "\u7834\u7a7a\u7130"
        },
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "Feu-Per\u00e7ant"
        },
        {
            "language": {
                "name": "de",
                "url": "/api/v2/language/6/"
            },
            "name": "Keilflamme"
        },
        {
            "language": {
                "name": "es",
                "url": "/api/v2/language/7/"
            },
            "name": "Flamariete"
        },
        {
            "language": {
                "name": "it",
                "url": "/api/v2/language/8/"
            },
            "name": "Vampeaguzze"
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Gouging Fire"
        },
        {
            "language": {
                "name": "ja",
                "url": "/api/v2/language/11/"
            },
            "name": "\u30a6\u30ac\u30c4\u30db\u30e0\u30e9"
        },
        {
            "language": {
                "name": "zh-hans",
                "url": "/api/v2/language/12/"
            },
            "name": "\u7834\u7a7a\u7130"
        },
        {
            "language": {
                "name": "es-419",
                "url": "/api/v2/language/14/"
            },
            "name": "Flamariete"
        }
    ],
    "order": 1022,
    "pal_park_encounters": [],
    "pokedex_numbers": [
        {
            "entry_number": 1020,
            "pokedex": {
                "name": "national",
                "url": "/api/v2/pokedex/1/"
            }
        },
        {
            "entry_number": 236,
            "pokedex": {
                "name": "blueberry",
                "url": "/api/v2/pokedex/33/"
            }
        }
    ],
    "shape": {
        "name": "quadruped",
        "url": "/api/v2/pokemon-shape/8/"
    },
    "varieties": [
        {
            "is_default": true,
            "pokemon": {
                "name": "gouging-fire",
                "url": "/api/v2/pokemon/1020/"
            }
        }
    ]
}

=== PokeAPI/api-data/data/api/v2/pokemon-species/1025/index.json
{
    "base_happiness": 0,
    "capture_rate": 3,
    "color": {
        "name": "purple",
        "url": "/api/v2/pokemon-color/7/"
    },
    "egg_groups": [
        {
            "name": "no-eggs",
            "url": "/api/v2/egg-group/15/"
        }
    ],
    "evolution_chain": {
        "url": "/api/v2/evolution-chain/549/"
    },
    "evolves_from_species": null,
    "flavor_text_entries": [
        {
            "flavor_text": "It feeds others toxic mochi that draw out desires and capabilities. Those who eat the mochi fall under Pecharunt\u2019s control, chained to its will.",
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "version": {
                "name": "scarlet",
                "url": "/api/v2/version/40/"
            }
        },
        {
            "flavor_text": "Its peach-shaped shell serves as storage for a potent poison. It makes poisonous mochi and serves them to people and Pok\u00e9mon.",
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "version": {
                "name": "violet",
                "url": "/api/v2/version/41/"
            }
        }
    ],
    "form_descriptions": [],
    "forms_switchable": false,
    "gender_rate": -1,
    "genera": [
        {
            "genus": "\u3057\u306f\u3044\u30dd\u30b1\u30e2\u30f3",
            "language": {
                "name": "ja-hrkt",
                "url": "/api/v2/language/1/"
            }
        },
        {
            "genus": "\uc9c0\ubc30\ud3ec\ucf13\ubaac",
            "language": {
                "name": "ko",
                "url": "/api/v2/language/3/"
            }
        },
        {
            "genus": "Emprise",
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            }
        },
        {
            "genus": "Subjugation Pok\u00e9mon",
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            }
        },
        {
            "genus": "\u3057\u306f\u3044\u30dd\u30b1\u30e2\u30f3",
            "language": {
                "name": "ja",
                "url": "/api/v2/language/11/"
            }
        }
    ],
    "generation": {
        "name": "generation-ix",
        "url": "/api/v2/generation/9/"
    },
    "growth_rate": {
        "name": "slow",
        "url": "/api/v2/growth-rate/1/"
    },
    "habitat": null,
    "has_gender_differences": false,
    "hatch_counter": 20,
    "id": 1025,
    "is_baby": false,
    "is_legendary": false,
    "is_mythical": true,
    "name": "pecharunt",
    "names": [
        {
            "language": {
                "name": "ja-hrkt",
                "url": "/api/v2/language/1/"
            },
            "name": "\u30e2\u30e2\u30ef\u30ed\u30a6"
        },
        {
            "language": {
                "name": "ja-roma",
                "url": "/api/v2/language/2/"
            },
            "name": "Momowarou"
        },
        {
            "language": {
                "name": "ko",
                "url": "/api/v2/language/3/"
            },
            "name": "\ubcf5\uc22d\uc545\ub3d9"
        },
        {
            "language": {
                "name": "zh-hant",
                "url": "/api/v2/language/4/"
            },
            "name": "\u6843\u6b79\u90ce"
        },
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "P\u00eachaminus"
        },
        {
            "language": {
                "name": "de",
                "url": "/api/v2/language/6/"
            },
            "name": "Infamomo"
        },
        {
            "language": {
                "name": "es",
                "url": "/api/v2/language/7/"
            },
            "name": "Pecharunt"
        },
        {
            "language": {
                "name": "it",
                "url": "/api/v2/language/8/"
            },
            "name": "Pecharunt"
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Pecharunt"
        },
        {
            "language": {
                "name": "ja",
                "url": "/api/v2/language/11/"
            },
            "name": "\u30e2\u30e2\u30ef\u30ed\u30a6"
        },
        {
            "language": {
                "name": "zh-hans",
                "url": "/api/v2/language/12/"
            },
            "name": "\u6843\u6b79\u90ce"
        },
        {
            "language": {
                "name": "es-419",
                "url": "/api/v2/language/14/"
            },
            "name": "Pecharunt"
        }
    ],
    "order": 1027,
    "pal_park_encounters": [],
    "pokedex_numbers": [
        {
            "entry_number": 1025,
            "pokedex": {
                "name": "national",
                "url": "/api/v2/pokedex/1/"
            }
        },
        {
            "entry_number": 243,
            "pokedex": {
                "name": "blueberry",
                "url": "/api/v2/pokedex/33/"
            }
        }
    ],
    "shape": {
        "name": "ball",
        "url": "/api/v2/pokemon-shape/1/"
    },
    "varieties": [
        {
            "is_default": true,
            "pokemon": {
                "name": "pecharunt",
                "url": "/api/v2/pokemon/1025/"
            }
        }
    ]
}

=== PokeAPI/api-data/data/api/v2/pokemon-species/971/index.json
{
    "base_happiness": 50,
    "capture_rate": 120,
    "color": {
        "name": "white",
        "url": "/api/v2/pokemon-color/9/"
    },
    "egg_groups": [
        {
            "name": "ground",
            "url": "/api/v2/egg-group/5/"
        }
    ],
    "evolution_chain": {
        "url": "/api/v2/evolution-chain/509/"
    },
    "evolves_from_species": null,
    "flavor_text_entries": [
        {
            "flavor_text": "It is said that a dog Pok\u00e9mon that died in the wild without ever interacting with a human was reborn as this Pok\u00e9mon.",
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "version": {
                "name": "scarlet",
                "url": "/api/v2/version/40/"
            }
        },
        {
            "flavor_text": "This friendly Pok\u00e9mon doesn\u2019t like being alone. Pay it even the slightest bit of attention, and it will follow you forever.",
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "version": {
                "name": "violet",
                "url": "/api/v2/version/41/"
            }
        }
    ],
    "form_descriptions": [],
    "forms_switchable": false,
    "gender_rate": 4,
    "genera": [
        {
            "genus": "\u304a\u3070\u3051\u3044\u306c\u30dd\u30b1\u30e2\u30f3",
            "language": {
                "name": "ja-hrkt",
                "url": "/api/v2/language/1/"
            }
        },
        {
            "genus": "\uc720\ub839\uac1c\ud3ec\ucf13\ubaac",
            "language": {
                "name": "ko",
                "url": "/api/v2/language/3/"
            }
        },
        {
            "genus": "\u9b3c\u72ac\u5bf6\u53ef\u5922",
            "language": {
                "name": "zh-hant",
                "url": "/api/v2/language/4/"
            }
        },
        {
            "genus": "Fant\u00f4chien",
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            }
        },
        {
            "genus": "Geisterhund",
            "language": {
                "name": "de",
                "url": "/api/v2/language/6/"
            }
        },
        {
            "genus": "Ghost Dog Pok\u00e9mon",
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            }
        },
        {
            "genus": "\u9b3c\u72ac\u5b9d\u53ef\u68a6",
            "language": {
                "name": "zh-hans",
                "url": "/api/v2/language/12/"
            }
        }
    ],
    "generation": {
        "name": "generation-ix",
        "url": "/api/v2/generation/9/"
    },
    "growth_rate": {
        "name": "medium-slow",
        "url": "/api/v2/growth-rate/4/"
    },
    "habitat": null,
    "has_gender_differences": false,
    "hatch_counter": 20,
    "id": 971,
    "is_baby": false,
    "is_legendary": false,
    "is_mythical": false,
    "name": "greavard",
    "names": [
        {
            "language": {
                "name": "ja-hrkt",
                "url": "/api/v2/language/1/"
            },
            "name": "\u30dc\u30c1"
        },
        {
            "language": {
                "name": "ja-roma",
                "url": "/api/v2/language/2/"
            },
            "name": "Bochi"
        },
        {
            "language": {
                "name": "ko",
                "url": "/api/v2/language/3/"
            },
            "name": "\ub9dd\ub9dd\uc774"
        },
        {
            "language": {
                "name": "zh-hant",
                "url": "/api/v2/language/4/"
            },
            "name": "\u5893\u4ed4\u72d7"
        },
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "Toutombe"
        },
        {
            "language": {
                "name": "de",
                "url": "/api/v2/language/6/"
            },
            "name": "Gruff"
        },
        {
            "language": {
                "name": "es",
                "url": "/api/v2/language/7/"
            },
            "name": "Greavard"
        },
        {
            "language": {
                "name": "it",
                "url": "/api/v2/language/8/"
            },
            "name": "Greavard"
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Greavard"
        },
        {
            "language": {
                "name": "ja",
                "url": "/api/v2/language/11/"
            },
            "name": "\u30dc\u30c1"
        },
        {
            "language": {
                "name": "zh-hans",
                "url": "/api/v2/language/12/"
            },
            "name": "\u5893\u4ed4\u72d7"
        },
        {
            "language": {
                "name": "es-419",
                "url": "/api/v2/language/14/"
            },
            "name": "Greavard"
        }
    ],
    "order": 924,
    "pal_park_encounters": [],
    "pokedex_numbers": [
        {
            "entry_number": 971,
            "pokedex": {
                "name": "national",
                "url": "/api/v2/pokedex/1/"
            }
        },
        {
            "entry_number": 311,
            "pokedex": {
                "name": "paldea",
                "url": "/api/v2/pokedex/31/"
            }
        },
        {
            "entry_number": 23,
            "pokedex": {
                "name": "hyperspace",
                "url": "/api/v2/pokedex/35/"
            }
        }
    ],
    "shape": {
        "name": "quadruped",
        "url": "/api/v2/pokemon-shape/8/"
    },
    "varieties": [
        {
            "is_default": true,
            "pokemon": {
                "name": "greavard",
                "url": "/api/v2/pokemon/971/"
            }
        }
    ]
}

=== PokeAPI/api-data/data/api/v2/pokemon-species/1024/index.json
{
    "base_happiness": 50,
    "capture_rate": 255,
    "color": {
        "name": "blue",
        "url": "/api/v2/pokemon-color/2/"
    },
    "egg_groups": [
        {
            "name": "no-eggs",
            "url": "/api/v2/egg-group/15/"
        }
    ],
    "evolution_chain": {
        "url": "/api/v2/evolution-chain/548/"
    },
    "evolves_from_species": null,
    "flavor_text_entries": [
        {
            "flavor_text": "Terapagos protects itself using its power to transform energy into hard crystals. This Pok\u00e9mon is the source of the Terastal phenomenon.",
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "version": {
                "name": "scarlet",
                "url": "/api/v2/version/40/"
            }
        },
        {
            "flavor_text": "It\u2019s thought that this Pok\u00e9mon lived in ancient Paldea until it got caught in seismic shifts and went extinct.",
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "version": {
                "name": "violet",
                "url": "/api/v2/version/41/"
            }
        }
    ],
    "form_descriptions": [],
    "forms_switchable": false,
    "gender_rate": 4,
    "genera": [
        {
            "genus": "\u30c6\u30e9\u30b9\u30bf\u30eb\u30dd\u30b1\u30e2\u30f3",
            "language": {
                "name": "ja-hrkt",
                "url": "/api/v2/language/1/"
            }
        },
        {
            "genus": "\ud14c\ub77c\uc2a4\ud0c8\ud3ec\ucf13\ubaac",
            "language": {
                "name": "ko",
                "url": "/api/v2/language/3/"
            }
        },
        {
            "genus": "T\u00e9racristal",
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            }
        },
        {
            "genus": "Tera Pok\u00e9mon",
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            }
        },
        {
            "genus": "\u30c6\u30e9\u30b9\u30bf\u30eb\u30dd\u30b1\u30e2\u30f3",
            "language": {
                "name": "ja",
                "url": "/api/v2/language/11/"
            }
        }
    ],
    "generation": {
        "name": "generation-ix",
        "url": "/api/v2/generation/9/"
    },
    "growth_rate": {
        "name": "slow",
        "url": "/api/v2/growth-rate/1/"
    },
    "habitat": null,
    "has_gender_differences": false,
    "hatch_counter": 5,
    "id": 1024,
    "is_baby": false,
    "is_legendary": true,
    "is_mythical": false,
    "name": "terapagos",
    "names": [
        {
            "language": {
                "name": "ja-hrkt",
                "url": "/api/v2/language/1/"
            },
            "name": "\u30c6\u30e9\u30d1\u30b4\u30b9"
        },
        {
            "language": {
                "name": "ko",
                "url": "/api/v2/language/3/"
            },
            "name": "\ud14c\ub77c\ud30c\uace0\uc2a4"
        },
        {
            "language": {
                "name": "zh-hant",
                "url": "/api/v2/language/4/"
            },
            "name": "\u592a\u6a02\u5df4\u6208\u65af"
        },
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "Terapagos"
        },
        {
            "language": {
                "name": "de",
                "url": "/api/v2/language/6/"
            },
            "name": "Terapagos"
        },
        {
            "language": {
                "name": "es",
                "url": "/api/v2/language/7/"
            },
            "name": "Terapagos"
        },
        {
            "language": {
                "name": "it",
                "url": "/api/v2/language/8/"
            },
            "name": "Terapagos"
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Terapagos"
        },
        {
            "language": {
                "name": "ja",
                "url": "/api/v2/language/11/"
            },
            "name": "\u30c6\u30e9\u30d1\u30b4\u30b9"
        },
        {
            "language": {
                "name": "zh-hans",
                "url": "/api/v2/language/12/"
            },
            "name": "\u592a\u4e50\u5df4\u6208\u65af"
        },
        {
            "language": {
                "name": "es-419",
                "url": "/api/v2/language/14/"
            },
            "name": "Terapagos"
        }
    ],
    "order": 1026,
    "pal_park_encounters": [],
    "pokedex_numbers": [
        {
            "entry_number": 1024,
            "pokedex": {
                "name": "national",
                "url": "/api/v2/pokedex/1/"
            }
        },
        {
            "entry_number": 240,
            "pokedex": {
                "name": "blueberry",
                "url": "/api/v2/pokedex/33/"
            }
        }
    ],
    "shape": {
        "name": "quadruped",
        "url": "/api/v2/pokemon-shape/8/"
    },
    "varieties": [
        {
            "is_default": true,
            "pokemon": {
                "name": "terapagos",
                "url": "/api/v2/pokemon/1024/"
            }
        },
        {
            "is_default": false,
            "pokemon": {
                "name": "terapagos-terastal",
                "url": "/api/v2/pokemon/10276/"
            }
        },
        {
            "is_default": false,
            "pokemon": {
                "name": "terapagos-stellar",
                "url": "/api/v2/pokemon/10277/"
            }
        }
    ]
}
