=== PokeAPI/api-data/data/schema/v2/nature/$id/index.json
{
    "$schema": "http://json-schema.org/schema#",
    "properties": {
        "decreased_stat": {
            "anyOf": [
                {
                    "type": "null"
                },
                {
                    "$ref": "/schema/v2/named_api_resource.json"
                }
            ]
        },
        "hates_flavor": {
            "anyOf": [
                {
                    "type": "null"
                },
                {
                    "$ref": "/schema/v2/named_api_resource.json"
                }
            ]
        },
        "id": {
            "type": "integer"
        },
        "increased_stat": {
            "anyOf": [
                {
                    "type": "null"
                },
                {
                    "$ref": "/schema/v2/named_api_resource.json"
                }
            ]
        },
        "likes_flavor": {
            "anyOf": [
                {
                    "type": "null"
                },
                {
                    "$ref": "/schema/v2/named_api_resource.json"
                }
            ]
        },
        "move_battle_style_preferences": {
            "items": {
                "properties": {
                    "high_hp_preference": {
                        "type": "integer"
                    },
                    "low_hp_preference": {
                        "type": "integer"
                    },
                    "move_battle_style": {
                        "$ref": "/schema/v2/named_api_resource.json"
                    }
                },
                "required": [
                    "high_hp_preference",
                    "low_hp_preference",
                    "move_battle_style"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "name": {
            "type": "string"
        },
        "names": {
            "items": {
                "properties": {
                    "language": {
                        "$ref": "/schema/v2/named_api_resource.json"
                    },
                    "name": {
                        "type": "string"
                    }
                },
                "required": [
                    "language",
                    "name"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "pokeathlon_stat_changes": {
            "items": {
                "properties": {
                    "max_change": {
                        "type": "integer"
                    },
                    "pokeathlon_stat": {
                        "$ref": "/schema/v2/named_api_resource.json"
                    }
                },
                "required": [
                    "max_change",
                    "pokeathlon_stat"
                ],
                "type": "object"
            },
            "type": "array"
        }
    },
    "required": [
        "decreased_stat",
        "hates_flavor",
        "id",
        "increased_stat",
        "likes_flavor",
        "move_battle_style_preferences",
        "name",
        "names",
        "pokeathlon_stat_changes"
    ],
    "type": "object"
}

=== PokeAPI/api-data/data/api/v2/nature/8/index.json
{
    "decreased_stat": {
        "name": "defense",
        "url": "/api/v2/stat/3/"
    },
    "hates_flavor": {
        "name": "sour",
        "url": "/api/v2/berry-flavor/5/"
    },
    "id": 8,
    "increased_stat": {
        "name": "special-attack",
        "url": "/api/v2/stat/4/"
    },
    "likes_flavor": {
        "name": "dry",
        "url": "/api/v2/berry-flavor/2/"
    },
    "move_battle_style_preferences": [
        {
            "high_hp_preference": 44,
            "low_hp_preference": 34,
            "move_battle_style": {
                "name": "attack",
                "url": "/api/v2/move-battle-style/1/"
            }
        },
        {
            "high_hp_preference": 50,
            "low_hp_preference": 6,
            "move_battle_style": {
                "name": "defense",
                "url": "/api/v2/move-battle-style/2/"
            }
        },
        {
            "high_hp_preference": 6,
            "low_hp_preference": 60,
            "move_battle_style": {
                "name": "support",
                "url": "/api/v2/move-battle-style/3/"
            }
        }
    ],
    "name": "mild",
    "names": [
        {
            "language": {
                "name": "ja-hrkt",
                "url": "/api/v2/language/1/"
            },
            "name": "\u304a\u3063\u3068\u308a"
        },
        {
            "language": {
                "name": "ko",
                "url": "/api/v2/language/3/"
            },
            "name": "\uc758\uc813"
        },
        {
            "language": {
                "name": "zh-hant",
                "url": "/api/v2/language/4/"
            },
            "name": "\u6162\u541e\u541e"
        },
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "Doux"
        },
        {
            "language": {
                "name": "de",
                "url": "/api/v2/language/6/"
            },
            "name": "Mild"
        },
        {
            "language": {
                "name": "es",
                "url": "/api/v2/language/7/"
            },
            "name": "Afable"
        },
        {
            "language": {
                "name": "it",
                "url": "/api/v2/language/8/"
            },
            "name": "Mite"
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Mild"
        },
        {
            "language": {
                "name": "ja",
                "url": "/api/v2/language/11/"
            },
            "name": "\u304a\u3063\u3068\u308a"
        },
        {
            "language": {
                "name": "zh-hans",
                "url": "/api/v2/language/12/"
            },
            "name": "\u6162\u541e\u541e"
        },
        {
            "language": {
                "name": "es-419",
                "url": "/api/v2/language/14/"
            },
            "name": "Afable"
        }
    ],
    "pokeathlon_stat_changes": [
        {
            "max_change": -2,
            "pokeathlon_stat": {
                "name": "skill",
                "url": "/api/v2/pokeathlon-stat/3/"
            }
        },
        {
            "max_change": 2,
            "pokeathlon_stat": {
                "name": "jump",
                "url": "/api/v2/pokeathlon-stat/5/"
            }
        }
    ]
}
