=== PokeAPI/api-data/data/schema/v2/move-ailment/-1/index.json
{
    "$schema": "http://json-schema.org/schema#",
    "properties": {
        "id": {
            "type": "integer"
        },
        "moves": {
            "items": {
                "$ref": "/schema/v2/named_api_resource.json"
            },
            "type": "array"
        },
        "name": {
            "type": "string"
        },
        "names": {
            "items": {
                "$ref": "/schema/v2/name.json"
            },
            "type": "array"
        }
    },
    "required": [
        "id",
        "moves",
        "name",
        "names"
    ],
    "type": "object"
}

=== PokeAPI/api-data/api/v2/move-ailment/14/index.json
{
    "id": 14,
    "moves": [
        {
            "name": "yawn",
            "url": "http://localhost/api/v2/move/281/"
        }
    ],
    "name": "yawn",
    "names": [
        {
            "language": {
                "name": "fr",
                "url": "http://localhost/api/v2/language/5/"
            },
            "name": "B\u00e2illement"
        },
        {
            "language": {
                "name": "en",
                "url": "http://localhost/api/v2/language/9/"
            },
            "name": "Yawn"
        }
    ]
}
