=== PokeAPI/api-data/data/schema/v2/encounter-condition-value/$id/index.json
{
    "$schema": "http://json-schema.org/schema#",
    "properties": {
        "condition": {
            "$ref": "/schema/v2/named_api_resource.json"
        },
        "id": {
            "type": "integer"
        },
        "name": {
            "type": "string"
        },
        "names": {
            "items": {
                "$ref": "/schema/v2/name.json"
            },
            "type": "array"
        }
    },
    "required": [
        "condition",
        "id",
        "name",
        "names"
    ],
    "type": "object"
}

=== PokeAPI/api-data/data/api/v2/encounter-condition-value/153/index.json
{
    "condition": {
        "name": "trade",
        "url": "/api/v2/encounter-condition/15/"
    },
    "id": 153,
    "name": "trade-ponyta",
    "names": [
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Give Ponyta in a Trade"
        }
    ]
}

=== PokeAPI/api-data/data/api/v2/encounter-condition-value/160/index.json
{
    "condition": {
        "name": "trade",
        "url": "/api/v2/encounter-condition/15/"
    },
    "id": 160,
    "name": "trade-kangaskhan",
    "names": [
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Give Kangaskhan in a Trade"
        }
    ]
}

=== PokeAPI/api-data/data/api/v2/encounter-condition-value/195/index.json
{
    "condition": {
        "name": "trade",
        "url": "/api/v2/encounter-condition/15/"
    },
    "id": 195,
    "name": "trade-cottonee",
    "names": [
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Give Cottonee in a Trade"
        }
    ]
}

=== PokeAPI/api-data/data/api/v2/encounter-condition-value/295/index.json
{
    "condition": {
        "name": "johto-safari-blocks",
        "url": "/api/v2/encounter-condition/26/"
    },
    "id": 295,
    "name": "johto-safari-blocks-peak-min-35",
    "names": [
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "At least 35 Peak block points placed"
        }
    ]
}

=== PokeAPI/api-data/data/api/v2/encounter-condition-value/59/index.json
{
    "condition": {
        "name": "weekday",
        "url": "/api/v2/encounter-condition/12/"
    },
    "id": 59,
    "name": "weekday-sunday",
    "names": [
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Sunday"
        },
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "Le dimanche"
        }
    ]
}

=== PokeAPI/api-data/data/api/v2/encounter-condition-value/31/index.json
{
    "condition": {
        "name": "story-progress",
        "url": "/api/v2/encounter-condition/9/"
    },
    "id": 31,
    "name": "story-progress-oak-eterna-city",
    "names": [
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Talked to Professor Oak at Eterna City"
        },
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "Apr\u00e8s avoir parl\u00e9 au Prof. Chen \u00e0 Vestigion"
        }
    ]
}

=== PokeAPI/api-data/api/v2/encounter-condition-value/19/index.json
{
    "condition": {
        "name": "season",
        "url": "http://127.0.0.1:8000/api/v2/encounter-condition/6/"
    },
    "id": 19,
    "name": "season-autumn",
    "names": [
        {
            "language": {
                "name": "de",
                "url": "http://127.0.0.1:8000/api/v2/language/6/"
            },
            "name": "Im Herbst"
        },
        {
            "language": {
                "name": "en",
                "url": "http://127.0.0.1:8000/api/v2/language/9/"
            },
            "name": "During Autumn"
        }
    ]
}
