=== PokeAPI/api-data/data/schema/v2/language/$id/index.json
{
    "$schema": "http://json-schema.org/schema#",
    "properties": {
        "id": {
            "type": "integer"
        },
        "iso3166": {
            "type": "string"
        },
        "iso639": {
            "type": "string"
        },
        "name": {
            "type": "string"
        },
        "names": {
            "items": {
                "$ref": "/schema/v2/name.json"
            },
            "type": "array"
        },
        "official": {
            "type": "boolean"
        }
    },
    "required": [
        "id",
        "iso3166",
        "iso639",
        "name",
        "names",
        "official"
    ],
    "type": "object"
}

=== PokeAPI/api-data/data/api/v2/language/10/index.json
{
    "id": 10,
    "iso3166": "cz",
    "iso639": "cs",
    "name": "cs",
    "names": [
        {
            "language": {
                "name": "ja-hrkt",
                "url": "/api/v2/language/1/"
            },
            "name": "\u30c1\u30a7\u30b3\u8a9e"
        },
        {
            "language": {
                "name": "ko",
                "url": "/api/v2/language/3/"
            },
            "name": "\uccb4\ucf54\uc5b4"
        },
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "Tch\u00e8que"
        },
        {
            "language": {
                "name": "de",
                "url": "/api/v2/language/6/"
            },
            "name": "Tschechisch"
        },
        {
            "language": {
                "name": "es",
                "url": "/api/v2/language/7/"
            },
            "name": "Checo"
        },
        {
            "language": {
                "name": "it",
                "url": "/api/v2/language/8/"
            },
            "name": "Ceco"
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Czech"
        },
        {
            "language": {
                "name": "pt-br",
                "url": "/api/v2/language/13/"
            },
            "name": "Tcheco"
        },
        {
            "language": {
                "name": "es-419",
                "url": "/api/v2/language/14/"
            },
            "name": "Checo"
        }
    ],
    "official": false
}

=== PokeAPI/api-data/data/api/v2/language/9/index.json
{
    "id": 9,
    "iso3166": "us",
    "iso639": "en",
    "name": "en",
    "names": [
        {
            "language": {
                "name": "ja-hrkt",
                "url": "/api/v2/language/1/"
            },
            "name": "\u82f1\u8a9e"
        },
        {
            "language": {
                "name": "ko",
                "url": "/api/v2/language/3/"
            },
            "name": "\uc601\uc5b4"
        },
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "Anglais"
        },
        {
            "language": {
                "name": "de",
                "url": "/api/v2/language/6/"
            },
            "name": "Englisch"
        },
        {
            "language": {
                "name": "es",
                "url": "/api/v2/language/7/"
            },
            "name": "Ingl\u00e9s"
        },
        {
            "language": {
                "name": "it",
                "url": "/api/v2/language/8/"
            },
            "name": "Inglese"
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "English"
        },
        {
            "language": {
                "name": "pt-br",
                "url": "/api/v2/language/13/"
            },
            "name": "Ingl\u00eas"
        },
        {
            "language": {
                "name": "es-419",
                "url": "/api/v2/language/14/"
            },
            "name": "Ingl\u00e9s"
        }
    ],
    "official": true
}
