=== PokeAPI/api-data/data/schema/v2/pokemon-form/$id/index.json
{
    "$schema": "http://json-schema.org/schema#",
    "properties": {
        "form_name": {
            "type": "string"
        },
        "form_names": {
            "items": {
                "$ref": "/schema/v2/name.json"
            },
            "type": "array"
        },
        "form_order": {
            "type": "integer"
        },
        "id": {
            "type": "integer"
        },
        "is_battle_only": {
            "type": "boolean"
        },
        "is_default": {
            "type": "boolean"
        },
        "is_mega": {
            "type": "boolean"
        },
        "name": {
            "type": "string"
        },
        "names": {
            "items": {
                "$ref": "/schema/v2/name.json"
            },
            "type": "array"
        },
        "order": {
            "type": "integer"
        },
        "pokemon": {
            "$ref": "/schema/v2/named_api_resource.json"
        },
        "sprites": {
            "properties": {
                "back_default": {
                    "type": [
                        "null",
                        "string"
                    ]
                },
                "back_female": {
                    "type": [
                        "null",
                        "string"
                    ]
                },
                "back_shiny": {
                    "type": [
                        "null",
                        "string"
                    ]
                },
                "back_shiny_female": {
                    "type": [
                        "null",
                        "string"
                    ]
                },
                "front_default": {
                    "type": [
                        "null",
                        "string"
                    ]
                },
                "front_female": {
                    "type": [
                        "null",
                        "string"
                    ]
                },
                "front_shiny": {
                    "type": [
                        "null",
                        "string"
                    ]
                },
                "front_shiny_female": {
                    "type": [
                        "null",
                        "string"
                    ]
                },
                "versions": {
                    "properties": {
                        "generation-ix": {
                            "properties": {
                                "scarlet-violet": {
                                    "properties": {
                                        "front_default": {
                                            "type": [
                                                "null",
                                                "string"
                                            ]
                                        },
                                        "front_female": {
                                            "type": [
                                                "null",
                                                "string"
                                            ]
                                        }
                                    },
                                    "required": [
                                        "front_default",
                                        "front_female"
                                    ],
                                    "type": "object"
                                }
                            },
                            "required": [
                                "scarlet-violet"
                            ],
                            "type": "object"
                        },
                        "generation-viii": {
                            "properties": {
                                "brilliant-diamond-shining-pearl": {
                                    "properties": {
                                        "front_default": {
                                            "type": [
                                                "null",
                                                "string"
                                            ]
                                        },
                                        "front_female": {
                                            "type": "null"
                                        }
                                    },
                                    "required": [
                                        "front_default",
                                        "front_female"
                                    ],
                                    "type": "object"
                                }
                            },
                            "required": [
                                "brilliant-diamond-shining-pearl"
                            ],
                            "type": "object"
                        }
                    },
                    "required": [
                        "generation-ix",
                        "generation-viii"
                    ],
                    "type": "object"
                }
            },
            "required": [
                "back_default",
                "back_female",
                "back_shiny",
                "back_shiny_female",
                "front_default",
                "front_female",
                "front_shiny",
                "front_shiny_female",
                "versions"
            ],
            "type": "object"
        },
        "trigger_conditions": {
            "items": {
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "trigger": {
                        "type": "string"
                    },
                    "url": {
                        "type": "string"
                    }
                },
                "required": [
                    "trigger"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "types": {
            "items": {
                "properties": {
                    "slot": {
                        "type": "integer"
                    },
                    "type": {
                        "$ref": "/schema/v2/named_api_resource.json"
                    }
                },
                "required": [
                    "slot",
                    "type"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "version_group": {
            "$ref": "/schema/v2/named_api_resource.json"
        }
    },
    "required": [
        "form_name",
        "form_names",
        "form_order",
        "id",
        "is_battle_only",
        "is_default",
        "is_mega",
        "name",
        "names",
        "order",
        "pokemon",
        "sprites",
        "trigger_conditions",
        "types",
        "version_group"
    ],
    "type": "object"
}

=== PokeAPI/api-data/data/api/v2/pokemon-form/606/index.json
{
    "form_name": "",
    "form_names": [],
    "form_order": 1,
    "id": 606,
    "is_battle_only": false,
    "is_default": true,
    "is_mega": false,
    "name": "beheeyem",
    "names": [],
    "order": 809,
    "pokemon": {
        "name": "beheeyem",
        "url": "/api/v2/pokemon/606/"
    },
    "sprites": {
        "back_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/606.png",
        "back_female": null,
        "back_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/606.png",
        "back_shiny_female": null,
        "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/606.png",
        "front_female": null,
        "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/606.png",
        "front_shiny_female": null,
        "versions": {
            "generation-ix": {
                "scarlet-violet": {
                    "front_default": null,
                    "front_female": null
                }
            },
            "generation-viii": {
                "brilliant-diamond-shining-pearl": {
                    "front_default": null,
                    "front_female": null
                }
            }
        }
    },
    "trigger_conditions": [],
    "types": [
        {
            "slot": 1,
            "type": {
                "name": "psychic",
                "url": "/api/v2/type/14/"
            }
        }
    ],
    "version_group": {
        "name": "black-white",
        "url": "/api/v2/version-group/11/"
    }
}

=== PokeAPI/api-data/data/api/v2/pokemon-form/10219/index.json
{
    "form_name": "ash",
    "form_names": [
        {
            "language": {
                "name": "ja-hrkt",
                "url": "/api/v2/language/1/"
            },
            "name": "\u30b5\u30c8\u30b7\u30b2\u30c3\u30b3\u30a6\u30ac"
        },
        {
            "language": {
                "name": "ko",
                "url": "/api/v2/language/3/"
            },
            "name": "\uc9c0\uc6b0\uac1c\uad74\ub2cc\uc790"
        },
        {
            "language": {
                "name": "zh-hant",
                "url": "/api/v2/language/4/"
            },
            "name": "\u5c0f\u667a\u7248\u7532\u8cc0\u5fcd\u86d9"
        },
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "Forme Sacha"
        },
        {
            "language": {
                "name": "de",
                "url": "/api/v2/language/6/"
            },
            "name": "Ash-Form"
        },
        {
            "language": {
                "name": "es",
                "url": "/api/v2/language/7/"
            },
            "name": "Forma Ash"
        },
        {
            "language": {
                "name": "it",
                "url": "/api/v2/language/8/"
            },
            "name": "Forma Ash"
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Ash-Greninja"
        },
        {
            "language": {
                "name": "ja",
                "url": "/api/v2/language/11/"
            },
            "name": "\u30b5\u30c8\u30b7\u30b2\u30c3\u30b3\u30a6\u30ac"
        },
        {
            "language": {
                "name": "zh-hans",
                "url": "/api/v2/language/12/"
            },
            "name": "\u5c0f\u667a\u7248\u7532\u8d3a\u5fcd\u86d9"
        },
        {
            "language": {
                "name": "es-419",
                "url": "/api/v2/language/14/"
            },
            "name": "Forma Ash"
        }
    ],
    "form_order": 3,
    "id": 10219,
    "is_battle_only": true,
    "is_default": true,
    "is_mega": false,
    "name": "greninja-ash",
    "names": [
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "Amphinobi Forme Sacha"
        },
        {
            "language": {
                "name": "de",
                "url": "/api/v2/language/6/"
            },
            "name": "Ash Quajutsu"
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Ash\u2019s Greninja"
        }
    ],
    "order": 879,
    "pokemon": {
        "name": "greninja-ash",
        "url": "/api/v2/pokemon/10117/"
    },
    "sprites": {
        "back_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/10117.png",
        "back_female": null,
        "back_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/10117.png",
        "back_shiny_female": null,
        "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10117.png",
        "front_female": null,
        "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10117.png",
        "front_shiny_female": null,
        "versions": {
            "generation-ix": {
                "scarlet-violet": {
                    "front_default": null,
                    "front_female": null
                }
            },
            "generation-viii": {
                "brilliant-diamond-shining-pearl": {
                    "front_default": null,
                    "front_female": null
                }
            }
        }
    },
    "trigger_conditions": [
        {
            "name": "battle-bond",
            "trigger": "ability",
            "url": "/api/v2/ability/210/"
        }
    ],
    "types": [
        {
            "slot": 1,
            "type": {
                "name": "water",
                "url": "/api/v2/type/11/"
            }
        },
        {
            "slot": 2,
            "type": {
                "name": "dark",
                "url": "/api/v2/type/17/"
            }
        }
    ],
    "version_group": {
        "name": "sun-moon",
        "url": "/api/v2/version-group/17/"
    }
}
