=== PokeAPI/api-data/data/schema/v2/pokemon-form/$id/index.json
{
    "$schema": "http://json-schema.org/schema#",
    "properties": {
        "form_name": {
            "type": "string"
        },
        "form_names": {
            "items": {
                "$ref": "/schema/v2/name.json"
            },
            "type": "array"
        },
        "form_order": {
            "type": "integer"
        },
        "id": {
            "type": "integer"
        },
        "is_battle_only": {
            "type": "boolean"
        },
        "is_default": {
            "type": "boolean"
        },
        "is_mega": {
            "type": "boolean"
        },
        "name": {
            "type": "string"
        },
        "names": {
            "items": {
                "$ref": "/schema/v2/name.json"
            },
            "type": "array"
        },
        "order": {
            "type": "integer"
        },
        "pokemon": {
            "$ref": "/schema/v2/named_api_resource.json"
        },
        "sprites": {
            "properties": {
                "back_default": {
                    "type": [
                        "null",
                        "string"
                    ]
                },
                "back_female": {
                    "type": [
                        "null",
                        "string"
                    ]
                },
                "back_shiny": {
                    "type": [
                        "null",
                        "string"
                    ]
                },
                "back_shiny_female": {
                    "type": [
                        "null",
                        "string"
                    ]
                },
                "front_default": {
                    "type": [
                        "null",
                        "string"
                    ]
                },
                "front_female": {
                    "type": [
                        "null",
                        "string"
                    ]
                },
                "front_shiny": {
                    "type": [
                        "null",
                        "string"
                    ]
                },
                "front_shiny_female": {
                    "type": [
                        "null",
                        "string"
                    ]
                },
                "versions": {
                    "properties": {
                        "generation-ix": {
                            "properties": {
                                "scarlet-violet": {
                                    "properties": {
                                        "front_default": {
                                            "type": [
                                                "null",
                                                "string"
                                            ]
                                        },
                                        "front_female": {
                                            "type": [
                                                "null",
                                                "string"
                                            ]
                                        }
                                    },
                                    "required": [
                                        "front_default",
                                        "front_female"
                                    ],
                                    "type": "object"
                                }
                            },
                            "required": [
                                "scarlet-violet"
                            ],
                            "type": "object"
                        },
                        "generation-viii": {
                            "properties": {
                                "brilliant-diamond-shining-pearl": {
                                    "properties": {
                                        "front_default": {
                                            "type": [
                                                "null",
                                                "string"
                                            ]
                                        },
                                        "front_female": {
                                            "type": "null"
                                        }
                                    },
                                    "required": [
                                        "front_default",
                                        "front_female"
                                    ],
                                    "type": "object"
                                }
                            },
                            "required": [
                                "brilliant-diamond-shining-pearl"
                            ],
                            "type": "object"
                        }
                    },
                    "required": [
                        "generation-ix",
                        "generation-viii"
                    ],
                    "type": "object"
                }
            },
            "required": [
                "back_default",
                "back_female",
                "back_shiny",
                "back_shiny_female",
                "front_default",
                "front_female",
                "front_shiny",
                "front_shiny_female",
                "versions"
            ],
            "type": "object"
        },
        "trigger_conditions": {
            "items": {
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "trigger": {
                        "type": "string"
                    },
                    "url": {
                        "type": "string"
                    }
                },
                "required": [
                    "trigger"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "types": {
            "items": {
                "properties": {
                    "slot": {
                        "type": "integer"
                    },
                    "type": {
                        "$ref": "/schema/v2/named_api_resource.json"
                    }
                },
                "required": [
                    "slot",
                    "type"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "version_group": {
            "$ref": "/schema/v2/named_api_resource.json"
        }
    },
    "required": [
        "form_name",
        "form_names",
        "form_order",
        "id",
        "is_battle_only",
        "is_default",
        "is_mega",
        "name",
        "names",
        "order",
        "pokemon",
        "sprites",
        "trigger_conditions",
        "types",
        "version_group"
    ],
    "type": "object"
}

=== PokeAPI/api-data/data/api/v2/pokemon-form/10269/index.json
{
    "form_name": "sandy",
    "form_names": [],
    "form_order": 2,
    "id": 10269,
    "is_battle_only": false,
    "is_default": false,
    "is_mega": false,
    "name": "mothim-sandy",
    "names": [],
    "order": 589,
    "pokemon": {
        "name": "mothim",
        "url": "/api/v2/pokemon/414/"
    },
    "sprites": {
        "back_default": null,
        "back_female": null,
        "back_shiny": null,
        "back_shiny_female": null,
        "front_default": null,
        "front_female": null,
        "front_shiny": null,
        "front_shiny_female": null,
        "versions": {
            "generation-ix": {
                "scarlet-violet": {
                    "front_default": null,
                    "front_female": null
                }
            },
            "generation-viii": {
                "brilliant-diamond-shining-pearl": {
                    "front_default": null,
                    "front_female": null
                }
            }
        }
    },
    "trigger_conditions": [],
    "types": [
        {
            "slot": 1,
            "type": {
                "name": "bug",
                "url": "/api/v2/type/7/"
            }
        },
        {
            "slot": 2,
            "type": {
                "name": "flying",
                "url": "/api/v2/type/3/"
            }
        }
    ],
    "version_group": {
        "name": "ultra-sun-ultra-moon",
        "url": "/api/v2/version-group/18/"
    }
}

=== PokeAPI/api-data/data/api/v2/pokemon-form/151/index.json
{
    "form_name": "",
    "form_names": [],
    "form_order": 1,
    "id": 151,
    "is_battle_only": false,
    "is_default": true,
    "is_mega": false,
    "name": "mew",
    "names": [],
    "order": 255,
    "pokemon": {
        "name": "mew",
        "url": "/api/v2/pokemon/151/"
    },
    "sprites": {
        "back_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/151.png",
        "back_female": null,
        "back_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/151.png",
        "back_shiny_female": null,
        "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/151.png",
        "front_female": null,
        "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/151.png",
        "front_shiny_female": null,
        "versions": {
            "generation-ix": {
                "scarlet-violet": {
                    "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-ix/scarlet-violet/151.png",
                    "front_female": null
                }
            },
            "generation-viii": {
                "brilliant-diamond-shining-pearl": {
                    "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-viii/brilliant-diamond-shining-pearl/151.png",
                    "front_female": null
                }
            }
        }
    },
    "trigger_conditions": [],
    "types": [
        {
            "slot": 1,
            "type": {
                "name": "psychic",
                "url": "/api/v2/type/14/"
            }
        }
    ],
    "version_group": {
        "name": "red-green-japan",
        "url": "/api/v2/version-group/28/"
    }
}

=== PokeAPI/api-data/data/api/v2/pokemon-form/607/index.json
{
    "form_name": "",
    "form_names": [],
    "form_order": 1,
    "id": 607,
    "is_battle_only": false,
    "is_default": true,
    "is_mega": false,
    "name": "litwick",
    "names": [],
    "order": 810,
    "pokemon": {
        "name": "litwick",
        "url": "/api/v2/pokemon/607/"
    },
    "sprites": {
        "back_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/607.png",
        "back_female": null,
        "back_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/607.png",
        "back_shiny_female": null,
        "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/607.png",
        "front_female": null,
        "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/607.png",
        "front_shiny_female": null,
        "versions": {
            "generation-ix": {
                "scarlet-violet": {
                    "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-ix/scarlet-violet/607.png",
                    "front_female": null
                }
            },
            "generation-viii": {
                "brilliant-diamond-shining-pearl": {
                    "front_default": null,
                    "front_female": null
                }
            }
        }
    },
    "trigger_conditions": [],
    "types": [
        {
            "slot": 1,
            "type": {
                "name": "ghost",
                "url": "/api/v2/type/8/"
            }
        },
        {
            "slot": 2,
            "type": {
                "name": "fire",
                "url": "/api/v2/type/10/"
            }
        }
    ],
    "version_group": {
        "name": "black-white",
        "url": "/api/v2/version-group/11/"
    }
}

=== PokeAPI/api-data/data/api/v2/pokemon-form/461/index.json
{
    "form_name": "",
    "form_names": [],
    "form_order": 1,
    "id": 461,
    "is_battle_only": false,
    "is_default": true,
    "is_mega": false,
    "name": "weavile",
    "names": [],
    "order": 349,
    "pokemon": {
        "name": "weavile",
        "url": "/api/v2/pokemon/461/"
    },
    "sprites": {
        "back_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/461.png",
        "back_female": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/female/461.png",
        "back_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/461.png",
        "back_shiny_female": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/female/461.png",
        "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/461.png",
        "front_female": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/female/461.png",
        "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/461.png",
        "front_shiny_female": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/female/461.png",
        "versions": {
            "generation-ix": {
                "scarlet-violet": {
                    "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-ix/scarlet-violet/461.png",
                    "front_female": null
                }
            },
            "generation-viii": {
                "brilliant-diamond-shining-pearl": {
                    "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-viii/brilliant-diamond-shining-pearl/461.png",
                    "front_female": null
                }
            }
        }
    },
    "trigger_conditions": [],
    "types": [
        {
            "slot": 1,
            "type": {
                "name": "dark",
                "url": "/api/v2/type/17/"
            }
        },
        {
            "slot": 2,
            "type": {
                "name": "ice",
                "url": "/api/v2/type/15/"
            }
        }
    ],
    "version_group": {
        "name": "diamond-pearl",
        "url": "/api/v2/version-group/8/"
    }
}

=== PokeAPI/api-data/data/api/v2/pokemon-form/789/index.json
{
    "form_name": "",
    "form_names": [],
    "form_order": 1,
    "id": 789,
    "is_battle_only": false,
    "is_default": true,
    "is_mega": false,
    "name": "cosmog",
    "names": [],
    "order": 1164,
    "pokemon": {
        "name": "cosmog",
        "url": "/api/v2/pokemon/789/"
    },
    "sprites": {
        "back_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/789.png",
        "back_female": null,
        "back_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/789.png",
        "back_shiny_female": null,
        "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/789.png",
        "front_female": null,
        "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/789.png",
        "front_shiny_female": null,
        "versions": {
            "generation-ix": {
                "scarlet-violet": {
                    "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-ix/scarlet-violet/789.png",
                    "front_female": null
                }
            },
            "generation-viii": {
                "brilliant-diamond-shining-pearl": {
                    "front_default": null,
                    "front_female": null
                }
            }
        }
    },
    "trigger_conditions": [],
    "types": [
        {
            "slot": 1,
            "type": {
                "name": "psychic",
                "url": "/api/v2/type/14/"
            }
        }
    ],
    "version_group": {
        "name": "sun-moon",
        "url": "/api/v2/version-group/17/"
    }
}

=== PokeAPI/api-data/data/api/v2/pokemon-form/10414/index.json
{
    "form_name": "origin",
    "form_names": [
        {
            "language": {
                "name": "ja-hrkt",
                "url": "/api/v2/language/1/"
            },
            "name": "\u30aa\u30ea\u30b8\u30f3\u30d5\u30a9\u30eb\u30e0"
        },
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "Forme Originelle"
        },
        {
            "language": {
                "name": "de",
                "url": "/api/v2/language/6/"
            },
            "name": "Urform"
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Origin Forme"
        },
        {
            "language": {
                "name": "ja",
                "url": "/api/v2/language/11/"
            },
            "name": "\u30aa\u30ea\u30b8\u30f3\u30d5\u30a9\u30eb\u30e0"
        }
    ],
    "form_order": 2,
    "id": 10414,
    "is_battle_only": false,
    "is_default": true,
    "is_mega": false,
    "name": "dialga-origin",
    "names": [
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "Diagla Originel"
        },
        {
            "language": {
                "name": "de",
                "url": "/api/v2/language/6/"
            },
            "name": "Ur-Dialga"
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Origin Dialga"
        }
    ],
    "order": 1343,
    "pokemon": {
        "name": "dialga-origin",
        "url": "/api/v2/pokemon/10245/"
    },
    "sprites": {
        "back_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/10245.png",
        "back_female": null,
        "back_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/10245.png",
        "back_shiny_female": null,
        "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10245.png",
        "front_female": null,
        "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10245.png",
        "front_shiny_female": null,
        "versions": {
            "generation-ix": {
                "scarlet-violet": {
                    "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-ix/scarlet-violet/10245.png",
                    "front_female": null
                }
            },
            "generation-viii": {
                "brilliant-diamond-shining-pearl": {
                    "front_default": null,
                    "front_female": null
                }
            }
        }
    },
    "trigger_conditions": [
        {
            "name": "adamant-crystal",
            "trigger": "held-item",
            "url": "/api/v2/item/1659/"
        }
    ],
    "types": [
        {
            "slot": 1,
            "type": {
                "name": "steel",
                "url": "/api/v2/type/9/"
            }
        },
        {
            "slot": 2,
            "type": {
                "name": "dragon",
                "url": "/api/v2/type/16/"
            }
        }
    ],
    "version_group": {
        "name": "legends-arceus",
        "url": "/api/v2/version-group/24/"
    }
}

=== PokeAPI/api-data/data/api/v2/pokemon-form/230/index.json
{
    "form_name": "",
    "form_names": [],
    "form_order": 1,
    "id": 230,
    "is_battle_only": false,
    "is_default": true,
    "is_mega": false,
    "name": "kingdra",
    "names": [],
    "order": 193,
    "pokemon": {
        "name": "kingdra",
        "url": "/api/v2/pokemon/230/"
    },
    "sprites": {
        "back_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/230.png",
        "back_female": null,
        "back_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/230.png",
        "back_shiny_female": null,
        "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/230.png",
        "front_female": null,
        "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/230.png",
        "front_shiny_female": null,
        "versions": {
            "generation-ix": {
                "scarlet-violet": {
                    "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-ix/scarlet-violet/230.png",
                    "front_female": null
                }
            },
            "generation-viii": {
                "brilliant-diamond-shining-pearl": {
                    "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-viii/brilliant-diamond-shining-pearl/230.png",
                    "front_female": null
                }
            }
        }
    },
    "trigger_conditions": [],
    "types": [
        {
            "slot": 1,
            "type": {
                "name": "water",
                "url": "/api/v2/type/11/"
            }
        },
        {
            "slot": 2,
            "type": {
                "name": "dragon",
                "url": "/api/v2/type/16/"
            }
        }
    ],
    "version_group": {
        "name": "gold-silver",
        "url": "/api/v2/version-group/3/"
    }
}

=== PokeAPI/api-data/data/api/v2/pokemon-form/10158/index.json
{
    "form_name": "mega",
    "form_names": [
        {
            "language": {
                "name": "ja-hrkt",
                "url": "/api/v2/language/1/"
            },
            "name": "\u30e1\u30ac\u30ac\u30d6\u30ea\u30a2\u30b9"
        },
        {
            "language": {
                "name": "ko",
                "url": "/api/v2/language/3/"
            },
            "name": "\uba54\uac00\ud55c\uce74\ub9ac\uc544\uc2a4"
        },
        {
            "language": {
                "name": "zh-hant",
                "url": "/api/v2/language/4/"
            },
            "name": "\u8d85\u7d1a\u70c8\u54ac\u9678\u9bca"
        },
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "M\u00e9ga-Carchacrok"
        },
        {
            "language": {
                "name": "de",
                "url": "/api/v2/language/6/"
            },
            "name": "Mega-Form"
        },
        {
            "language": {
                "name": "es",
                "url": "/api/v2/language/7/"
            },
            "name": "Mega-Garchomp"
        },
        {
            "language": {
                "name": "it",
                "url": "/api/v2/language/8/"
            },
            "name": "MegaGarchomp"
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Mega Garchomp"
        },
        {
            "language": {
                "name": "ja",
                "url": "/api/v2/language/11/"
            },
            "name": "\u30e1\u30ac\u30ac\u30d6\u30ea\u30a2\u30b9"
        },
        {
            "language": {
                "name": "zh-hans",
                "url": "/api/v2/language/12/"
            },
            "name": "\u8d85\u7ea7\u70c8\u54ac\u9646\u9ca8"
        },
        {
            "language": {
                "name": "es-419",
                "url": "/api/v2/language/14/"
            },
            "name": "Mega-Garchomp"
        }
    ],
    "form_order": 2,
    "id": 10158,
    "is_battle_only": true,
    "is_default": true,
    "is_mega": true,
    "name": "garchomp-mega",
    "names": [
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "M\u00e9ga-Carchacrok"
        },
        {
            "language": {
                "name": "de",
                "url": "/api/v2/language/6/"
            },
            "name": "Mega-Knakrack"
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Mega Garchomp"
        }
    ],
    "order": 619,
    "pokemon": {
        "name": "garchomp-mega",
        "url": "/api/v2/pokemon/10058/"
    },
    "sprites": {
        "back_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/10058.png",
        "back_female": null,
        "back_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/10058.png",
        "back_shiny_female": null,
        "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10058.png",
        "front_female": null,
        "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10058.png",
        "front_shiny_female": null,
        "versions": {
            "generation-ix": {
                "scarlet-violet": {
                    "front_default": null,
                    "front_female": null
                }
            },
            "generation-viii": {
                "brilliant-diamond-shining-pearl": {
                    "front_default": null,
                    "front_female": null
                }
            }
        }
    },
    "trigger_conditions": [
        {
            "name": "garchompite",
            "trigger": "held-item",
            "url": "/api/v2/item/722/"
        }
    ],
    "types": [
        {
            "slot": 1,
            "type": {
                "name": "dragon",
                "url": "/api/v2/type/16/"
            }
        },
        {
            "slot": 2,
            "type": {
                "name": "ground",
                "url": "/api/v2/type/5/"
            }
        }
    ],
    "version_group": {
        "name": "x-y",
        "url": "/api/v2/version-group/15/"
    }
}
