=== PokeAPI/api-data/data/schema/v2/named_api_resource_list.json
{
    "$schema": "http://json-schema.org/schema#",
    "properties": {
        "count": {
            "type": "integer"
        },
        "next": {
            "type": [
                "null",
                "string"
            ]
        },
        "previous": {
            "type": [
                "null",
                "string"
            ]
        },
        "results": {
            "items": {
                "$ref": "/schema/v2/named_api_resource.json"
            },
            "type": "array"
        }
    },
    "required": [
        "count",
        "next",
        "previous",
        "results"
    ],
    "type": "object"
}

=== PokeAPI/api-data/data/api/v2/region/index.json
{
    "count": 10,
    "next": null,
    "previous": null,
    "results": [
        {
            "name": "kanto",
            "url": "/api/v2/region/1/"
        },
        {
            "name": "johto",
            "url": "/api/v2/region/2/"
        },
        {
            "name": "hoenn",
            "url": "/api/v2/region/3/"
        },
        {
            "name": "sinnoh",
            "url": "/api/v2/region/4/"
        },
        {
            "name": "unova",
            "url": "/api/v2/region/5/"
        },
        {
            "name": "kalos",
            "url": "/api/v2/region/6/"
        },
        {
            "name": "alola",
            "url": "/api/v2/region/7/"
        },
        {
            "name": "galar",
            "url": "/api/v2/region/8/"
        },
        {
            "name": "hisui",
            "url": "/api/v2/region/9/"
        },
        {
            "name": "paldea",
            "url": "/api/v2/region/10/"
        }
    ]
}
