=== PokeAPI/api-data/data/schema/v2/machine/$id/index.json
{
    "$schema": "http://json-schema.org/schema#",
    "properties": {
        "id": {
            "type": "integer"
        },
        "item": {
            "$ref": "/schema/v2/named_api_resource.json"
        },
        "move": {
            "$ref": "/schema/v2/named_api_resource.json"
        },
        "version_group": {
            "$ref": "/schema/v2/named_api_resource.json"
        }
    },
    "required": [
        "id",
        "item",
        "move",
        "version_group"
    ],
    "type": "object"
}

=== PokeAPI/api-data/data/api/v2/machine/1693/index.json
{
    "id": 1693,
    "item": {
        "name": "tm49",
        "url": "/api/v2/item/353/"
    },
    "move": {
        "name": "scald",
        "url": "/api/v2/move/503/"
    },
    "version_group": {
        "name": "brilliant-diamond-and-shining-pearl",
        "url": "/api/v2/version-group/23/"
    }
}

=== PokeAPI/api-data/data/api/v2/machine/740/index.json
{
    "id": 740,
    "item": {
        "name": "tm37",
        "url": "/api/v2/item/341/"
    },
    "move": {
        "name": "flamethrower",
        "url": "/api/v2/move/53/"
    },
    "version_group": {
        "name": "lets-go-pikachu-lets-go-eevee",
        "url": "/api/v2/version-group/19/"
    }
}

=== PokeAPI/api-data/data/api/v2/machine/480/index.json
{
    "id": 480,
    "item": {
        "name": "tm24",
        "url": "/api/v2/item/328/"
    },
    "move": {
        "name": "x-scissor",
        "url": "/api/v2/move/404/"
    },
    "version_group": {
        "name": "lets-go-pikachu-lets-go-eevee",
        "url": "/api/v2/version-group/19/"
    }
}
