=== PokeAPI/api-data/data/schema/v2/move/$id/index.json
{
    "$schema": "http://json-schema.org/schema#",
    "properties": {
        "accuracy": {
            "type": [
                "integer",
                "null"
            ]
        },
        "contest_combos": {
            "anyOf": [
                {
                    "type": "null"
                },
                {
                    "properties": {
                        "normal": {
                            "properties": {
                                "use_after": {
                                    "anyOf": [
                                        {
                                            "type": "null"
                                        },
                                        {
                                            "items": {
                                                "$ref": "/schema/v2/named_api_resource.json"
                                            },
                                            "type": "array"
                                        }
                                    ]
                                },
                                "use_before": {
                                    "anyOf": [
                                        {
                                            "type": "null"
                                        },
                                        {
                                            "items": {
                                                "$ref": "/schema/v2/named_api_resource.json"
                                            },
                                            "type": "array"
                                        }
                                    ]
                                }
                            },
                            "required": [
                                "use_after",
                                "use_before"
                            ],
                            "type": "object"
                        },
                        "super": {
                            "properties": {
                                "use_after": {
                                    "anyOf": [
                                        {
                                            "type": "null"
                                        },
                                        {
                                            "items": {
                                                "$ref": "/schema/v2/named_api_resource.json"
                                            },
                                            "type": "array"
                                        }
                                    ]
                                },
                                "use_before": {
                                    "anyOf": [
                                        {
                                            "type": "null"
                                        },
                                        {
                                            "items": {
                                                "$ref": "/schema/v2/named_api_resource.json"
                                            },
                                            "type": "array"
                                        }
                                    ]
                                }
                            },
                            "required": [
                                "use_after",
                                "use_before"
                            ],
                            "type": "object"
                        }
                    },
                    "required": [
                        "normal",
                        "super"
                    ],
                    "type": "object"
                }
            ]
        },
        "contest_effect": {
            "anyOf": [
                {
                    "type": "null"
                },
                {
                    "$ref": "/schema/v2/api_resource.json"
                }
            ]
        },
        "contest_type": {
            "anyOf": [
                {
                    "type": "null"
                },
                {
                    "$ref": "/schema/v2/named_api_resource.json"
                }
            ]
        },
        "damage_class": {
            "$ref": "/schema/v2/named_api_resource.json"
        },
        "effect_chance": {
            "type": [
                "integer",
                "null"
            ]
        },
        "effect_changes": {
            "items": {
                "properties": {
                    "effect_entries": {
                        "items": {
                            "properties": {
                                "effect": {
                                    "type": "string"
                                },
                                "language": {
                                    "$ref": "/schema/v2/named_api_resource.json"
                                }
                            },
                            "required": [
                                "effect",
                                "language"
                            ],
                            "type": "object"
                        },
                        "type": "array"
                    },
                    "version_group": {
                        "$ref": "/schema/v2/named_api_resource.json"
                    }
                },
                "required": [
                    "effect_entries",
                    "version_group"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "effect_entries": {
            "items": {
                "properties": {
                    "effect": {
                        "type": "string"
                    },
                    "language": {
                        "$ref": "/schema/v2/named_api_resource.json"
                    },
                    "short_effect": {
                        "type": "string"
                    }
                },
                "required": [
                    "effect",
                    "language",
                    "short_effect"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "flavor_text_entries": {
            "items": {
                "properties": {
                    "flavor_text": {
                        "type": "string"
                    },
                    "language": {
                        "$ref": "/schema/v2/named_api_resource.json"
                    },
                    "version_group": {
                        "$ref": "/schema/v2/named_api_resource.json"
                    }
                },
                "required": [
                    "flavor_text",
                    "language",
                    "version_group"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "generation": {
            "$ref": "/schema/v2/named_api_resource.json"
        },
        "id": {
            "type": "integer"
        },
        "learned_by_pokemon": {
            "items": {
                "$ref": "/schema/v2/named_api_resource.json"
            },
            "type": "array"
        },
        "machines": {
            "items": {
                "properties": {
                    "machine": {
                        "$ref": "/schema/v2/api_resource.json"
                    },
                    "version_group": {
                        "$ref": "/schema/v2/named_api_resource.json"
                    }
                },
                "required": [
                    "machine",
                    "version_group"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "meta": {
            "anyOf": [
                {
                    "type": "null"
                },
                {
                    "properties": {
                        "ailment": {
                            "$ref": "/schema/v2/named_api_resource.json"
                        },
                        "ailment_chance": {
                            "type": "integer"
                        },
                        "category": {
                            "$ref": "/schema/v2/named_api_resource.json"
                        },
                        "crit_rate": {
                            "type": "integer"
                        },
                        "drain": {
                            "type": "integer"
                        },
                        "flinch_chance": {
                            "type": "integer"
                        },
                        "healing": {
                            "type": "integer"
                        },
                        "max_hits": {
                            "type": [
                                "integer",
                                "null"
                            ]
                        },
                        "max_turns": {
                            "type": [
                                "integer",
                                "null"
                            ]
                        },
                        "min_hits": {
                            "type": [
                                "integer",
                                "null"
                            ]
                        },
                        "min_turns": {
                            "type": [
                                "integer",
                                "null"
                            ]
                        },
                        "stat_chance": {
                            "type": "integer"
                        }
                    },
                    "required": [
                        "ailment",
                        "ailment_chance",
                        "category",
                        "crit_rate",
                        "drain",
                        "flinch_chance",
                        "healing",
                        "max_hits",
                        "max_turns",
                        "min_hits",
                        "min_turns",
                        "stat_chance"
                    ],
                    "type": "object"
                }
            ]
        },
        "name": {
            "type": "string"
        },
        "names": {
            "items": {
                "properties": {
                    "language": {
                        "$ref": "/schema/v2/named_api_resource.json"
                    },
                    "name": {
                        "type": "string"
                    }
                },
                "required": [
                    "language",
                    "name"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "past_values": {
            "items": {
                "properties": {
                    "accuracy": {
                        "type": [
                            "integer",
                            "null"
                        ]
                    },
                    "effect_chance": {
                        "type": [
                            "integer",
                            "null"
                        ]
                    },
                    "effect_entries": {
                        "items": {
                            "properties": {
                                "effect": {
                                    "type": "string"
                                },
                                "language": {
                                    "$ref": "/schema/v2/named_api_resource.json"
                                },
                                "short_effect": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "effect",
                                "language",
                                "short_effect"
                            ],
                            "type": "object"
                        },
                        "type": "array"
                    },
                    "power": {
                        "type": [
                            "integer",
                            "null"
                        ]
                    },
                    "pp": {
                        "type": [
                            "integer",
                            "null"
                        ]
                    },
                    "type": {
                        "anyOf": [
                            {
                                "type": "null"
                            },
                            {
                                "$ref": "/schema/v2/named_api_resource.json"
                            }
                        ]
                    },
                    "version_group": {
                        "$ref": "/schema/v2/named_api_resource.json"
                    }
                },
                "required": [
                    "accuracy",
                    "effect_chance",
                    "effect_entries",
                    "power",
                    "pp",
                    "type",
                    "version_group"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "power": {
            "type": [
                "integer",
                "null"
            ]
        },
        "pp": {
            "type": [
                "integer",
                "null"
            ]
        },
        "priority": {
            "type": "integer"
        },
        "stat_changes": {
            "items": {
                "properties": {
                    "change": {
                        "type": "integer"
                    },
                    "stat": {
                        "$ref": "/schema/v2/named_api_resource.json"
                    }
                },
                "required": [
                    "change",
                    "stat"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "super_contest_effect": {
            "anyOf": [
                {
                    "type": "null"
                },
                {
                    "$ref": "/schema/v2/api_resource.json"
                }
            ]
        },
        "target": {
            "$ref": "/schema/v2/named_api_resource.json"
        },
        "type": {
            "$ref": "/schema/v2/named_api_resource.json"
        }
    },
    "required": [
        "accuracy",
        "contest_combos",
        "contest_effect",
        "contest_type",
        "damage_class",
        "effect_chance",
        "effect_changes",
        "effect_entries",
        "flavor_text_entries",
        "generation",
        "id",
        "learned_by_pokemon",
        "machines",
        "meta",
        "name",
        "names",
        "past_values",
        "power",
        "pp",
        "priority",
        "stat_changes",
        "super_contest_effect",
        "target",
        "type"
    ],
    "type": "object"
}

=== PokeAPI/api-data/data/api/v2/move/889/index.json
{
    "accuracy": 100,
    "contest_combos": null,
    "contest_effect": null,
    "contest_type": null,
    "damage_class": {
        "name": "physical",
        "url": "/api/v2/move-damage-class/2/"
    },
    "effect_chance": null,
    "effect_changes": [],
    "effect_entries": [],
    "flavor_text_entries": [
        {
            "flavor_text": "Le lanceur transforme sa col\u00e8re en \u00e9nergie pour attaquer. Plus il a subi d'attaques, plus la puissance de cette capacit\u00e9 augmente.",
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "version_group": {
                "name": "scarlet-violet",
                "url": "/api/v2/version-group/25/"
            }
        },
        {
            "flavor_text": "The user converts its rage into energy to attack. The more times the user has been hit by attacks, the greater the move's power.",
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "version_group": {
                "name": "scarlet-violet",
                "url": "/api/v2/version-group/25/"
            }
        }
    ],
    "generation": {
        "name": "generation-ix",
        "url": "/api/v2/generation/9/"
    },
    "id": 889,
    "learned_by_pokemon": [
        {
            "name": "primeape",
            "url": "/api/v2/pokemon/57/"
        },
        {
            "name": "annihilape",
            "url": "/api/v2/pokemon/979/"
        }
    ],
    "machines": [],
    "meta": null,
    "name": "rage-fist",
    "names": [
        {
            "language": {
                "name": "ja-hrkt",
                "url": "/api/v2/language/1/"
            },
            "name": "\u3075\u3093\u3069\u306e\u3053\u3076\u3057"
        },
        {
            "language": {
                "name": "ko",
                "url": "/api/v2/language/3/"
            },
            "name": "\ubd84\ub178\uc758\uc8fc\uba39"
        },
        {
            "language": {
                "name": "zh-hant",
                "url": "/api/v2/language/4/"
            },
            "name": "\u6124\u6012\u4e4b\u62f3"
        },
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "Poing de Col\u00e8re"
        },
        {
            "language": {
                "name": "it",
                "url": "/api/v2/language/8/"
            },
            "name": "Pugno Furibondo"
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Rage Fist"
        },
        {
            "language": {
                "name": "ja",
                "url": "/api/v2/language/11/"
            },
            "name": "\u3075\u3093\u3069\u306e\u3053\u3076\u3057"
        },
        {
            "language": {
                "name": "es-419",
                "url": "/api/v2/language/14/"
            },
            "name": "Pu\u00f1o Furia"
        },
        {
            "language": {
                "name": "es",
                "url": "/api/v2/language/7/"
            },
            "name": "Pu\u00f1o Furia"
        }
    ],
    "past_values": [],
    "power": 50,
    "pp": 10,
    "priority": 0,
    "stat_changes": [],
    "super_contest_effect": null,
    "target": {
        "name": "selected-pokemon",
        "url": "/api/v2/move-target/10/"
    },
    "type": {
        "name": "ghost",
        "url": "/api/v2/type/8/"
    }
}

=== PokeAPI/api-data/data/api/v2/move/10015/index.json
{
    "accuracy": 100,
    "contest_combos": null,
    "contest_effect": null,
    "contest_type": null,
    "damage_class": {
        "name": "status",
        "url": "/api/v2/move-damage-class/1/"
    },
    "effect_chance": null,
    "effect_changes": [],
    "effect_entries": [
        {
            "effect": "Diminue l'esquive de la cible de deux niveaux.",
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "short_effect": "Diminue l'esquive de la cible de deux niveaux."
        },
        {
            "effect": "Lowers the target\u2019s evasion by two stages.",
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "short_effect": "Lowers the target\u2019s evasion by two stages."
        }
    ],
    "flavor_text_entries": [],
    "generation": {
        "name": "generation-iii",
        "url": "/api/v2/generation/3/"
    },
    "id": 10015,
    "learned_by_pokemon": [],
    "machines": [],
    "meta": null,
    "name": "shadow-mist",
    "names": [
        {
            "language": {
                "name": "ja-hrkt",
                "url": "/api/v2/language/1/"
            },
            "name": "\u30c0\u30fc\u30af\u30df\u30b9\u30c8"
        },
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "Brume Noire"
        },
        {
            "language": {
                "name": "de",
                "url": "/api/v2/language/6/"
            },
            "name": "Cryptodunst"
        },
        {
            "language": {
                "name": "es",
                "url": "/api/v2/language/7/"
            },
            "name": "Bruma Oscura"
        },
        {
            "language": {
                "name": "it",
                "url": "/api/v2/language/8/"
            },
            "name": "Nebbiascura"
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Shadow Mist"
        },
        {
            "language": {
                "name": "es-419",
                "url": "/api/v2/language/14/"
            },
            "name": "Bruma Oscura"
        }
    ],
    "past_values": [],
    "power": null,
    "pp": null,
    "priority": 0,
    "stat_changes": [],
    "super_contest_effect": null,
    "target": {
        "name": "opponents-field",
        "url": "/api/v2/move-target/6/"
    },
    "type": {
        "name": "shadow",
        "url": "/api/v2/type/10002/"
    }
}
