=== PokeAPI/api-data/data/schema/v2/location/$id/index.json
{
    "$schema": "http://json-schema.org/schema#",
    "properties": {
        "areas": {
            "items": {
                "$ref": "/schema/v2/named_api_resource.json"
            },
            "type": "array"
        },
        "game_indices": {
            "items": {
                "$ref": "/schema/v2/generation_game_index.json"
            },
            "type": "array"
        },
        "id": {
            "type": "integer"
        },
        "name": {
            "type": "string"
        },
        "names": {
            "items": {
                "$ref": "/schema/v2/name.json"
            },
            "type": "array"
        },
        "region": {
            "anyOf": [
                {
                    "type": "null"
                },
                {
                    "$ref": "/schema/v2/named_api_resource.json"
                }
            ]
        }
    },
    "required": [
        "areas",
        "game_indices",
        "id",
        "name",
        "names",
        "region"
    ],
    "type": "object"
}

=== PokeAPI/api-data/data/api/v2/location/593/index.json
{
    "areas": [
        {
            "name": "santalune-forest-area",
            "url": "/api/v2/location-area/734/"
        }
    ],
    "game_indices": [
        {
            "game_index": 14,
            "generation": {
                "name": "generation-vi",
                "url": "/api/v2/generation/6/"
            }
        }
    ],
    "id": 593,
    "name": "santalune-forest",
    "names": [
        {
            "language": {
                "name": "ja-hrkt",
                "url": "/api/v2/language/1/"
            },
            "name": "\u30cf\u30af\u30c0\u30f3\u306e\u3082\u308a"
        },
        {
            "language": {
                "name": "ko",
                "url": "/api/v2/language/3/"
            },
            "name": "\ubc31\ub2e8\uc232"
        },
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "For\u00eat de Neuvartault"
        },
        {
            "language": {
                "name": "de",
                "url": "/api/v2/language/6/"
            },
            "name": "Nouvaria-Wald"
        },
        {
            "language": {
                "name": "es",
                "url": "/api/v2/language/7/"
            },
            "name": "Bosque de Novarte"
        },
        {
            "language": {
                "name": "it",
                "url": "/api/v2/language/8/"
            },
            "name": "Bosco Novartopoli"
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Santalune Forest"
        },
        {
            "language": {
                "name": "ja",
                "url": "/api/v2/language/11/"
            },
            "name": "\u30cf\u30af\u30c0\u30f3\u306e\u68ee"
        },
        {
            "language": {
                "name": "es-419",
                "url": "/api/v2/language/14/"
            },
            "name": "Bosque de Novarte"
        }
    ],
    "region": {
        "name": "kalos",
        "url": "/api/v2/region/6/"
    }
}

=== PokeAPI/api-data/data/api/v2/location/1029/index.json
{
    "areas": [
        {
            "name": "tidewater-dam-area",
            "url": "/api/v2/location-area/1023/"
        }
    ],
    "game_indices": [],
    "id": 1029,
    "name": "tidewater-dam",
    "names": [
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Tidewater Dam"
        }
    ],
    "region": {
        "name": "hisui",
        "url": "/api/v2/region/9/"
    }
}

=== PokeAPI/api-data/api/v2/location/656/index.json
{
    "areas": [],
    "game_indices": [
        {
            "game_index": 103,
            "generation": {
                "name": "generation-vi",
                "url": "http://localhost/api/v2/generation/6/"
            }
        }
    ],
    "id": 656,
    "name": "detourner-way",
    "names": [
        {
            "language": {
                "name": "ja",
                "url": "http://localhost/api/v2/language/11/"
            },
            "name": "\u30c7\u30c8\u30eb\u30cd\u901a\u308a"
        },
        {
            "language": {
                "name": "en",
                "url": "http://localhost/api/v2/language/9/"
            },
            "name": "D\u00e9tourner Way"
        },
        {
            "language": {
                "name": "it",
                "url": "http://localhost/api/v2/language/8/"
            },
            "name": "Via Detour"
        },
        {
            "language": {
                "name": "es",
                "url": "http://localhost/api/v2/language/7/"
            },
            "name": "V\u00eda Desv\u00edo"
        },
        {
            "language": {
                "name": "de",
                "url": "http://localhost/api/v2/language/6/"
            },
            "name": "D\u00e9tourn\u00e9-Weg"
        },
        {
            "language": {
                "name": "fr",
                "url": "http://localhost/api/v2/language/5/"
            },
            "name": "Chemin D\u00e9tour"
        },
        {
            "language": {
                "name": "ko",
                "url": "http://localhost/api/v2/language/3/"
            },
            "name": "\ub370\ub69c\ub974\ub124 \ub3c4\ub85c"
        },
        {
            "language": {
                "name": "ja-Hrkt",
                "url": "http://localhost/api/v2/language/1/"
            },
            "name": "\u30c7\u30c8\u30eb\u30cd\u3069\u304a\u308a"
        }
    ],
    "region": {
        "name": "kalos",
        "url": "http://localhost/api/v2/region/6/"
    }
}

=== PokeAPI/api-data/api/v2/location/56/index.json
{
    "areas": [
        {
            "name": "sinnoh-route-228-area",
            "url": "http://localhost/api/v2/location-area/175/"
        }
    ],
    "game_indices": [
        {
            "game_index": 43,
            "generation": {
                "name": "generation-iv",
                "url": "http://localhost/api/v2/generation/4/"
            }
        }
    ],
    "id": 56,
    "name": "sinnoh-route-228",
    "names": [
        {
            "language": {
                "name": "en",
                "url": "http://localhost/api/v2/language/9/"
            },
            "name": "Route 228"
        },
        {
            "language": {
                "name": "fr",
                "url": "http://localhost/api/v2/language/5/"
            },
            "name": "Route 228"
        }
    ],
    "region": {
        "name": "sinnoh",
        "url": "http://localhost/api/v2/region/4/"
    }
}

=== PokeAPI/api-data/data/api/v2/location/627/index.json
{
    "areas": [],
    "game_indices": [
        {
            "game_index": 63,
            "generation": {
                "name": "generation-vi",
                "url": "/api/v2/generation/6/"
            }
        }
    ],
    "id": 627,
    "name": "fourrage-road",
    "names": [
        {
            "language": {
                "name": "ja-hrkt",
                "url": "/api/v2/language/1/"
            },
            "name": "\u30d5\u30e9\u30fc\u30b8\u30e5\u3069\u304a\u308a"
        },
        {
            "language": {
                "name": "ko",
                "url": "/api/v2/language/3/"
            },
            "name": "\ud504\ub77c\uc8fc \ub3c4\ub85c"
        },
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "Chemin Fourrage"
        },
        {
            "language": {
                "name": "de",
                "url": "/api/v2/language/6/"
            },
            "name": "Fourrage-Weg"
        },
        {
            "language": {
                "name": "es",
                "url": "/api/v2/language/7/"
            },
            "name": "Vereda del Heno"
        },
        {
            "language": {
                "name": "it",
                "url": "/api/v2/language/8/"
            },
            "name": "Via dei Pascoli"
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Fourrage Road"
        },
        {
            "language": {
                "name": "ja",
                "url": "/api/v2/language/11/"
            },
            "name": "\u30d5\u30e9\u30fc\u30b8\u30e5\u901a\u308a"
        },
        {
            "language": {
                "name": "es-419",
                "url": "/api/v2/language/14/"
            },
            "name": "Vereda del Heno"
        }
    ],
    "region": {
        "name": "kalos",
        "url": "/api/v2/region/6/"
    }
}

=== PokeAPI/api-data/data/api/v2/location/1121/index.json
{
    "areas": [
        {
            "name": "kalos-berry-fields-area",
            "url": "/api/v2/location-area/1483/"
        }
    ],
    "game_indices": [],
    "id": 1121,
    "name": "kalos-berry-fields",
    "names": [
        {
            "language": {
                "name": "de",
                "url": "/api/v2/language/6/"
            },
            "name": "Kalos Berry Fields"
        }
    ],
    "region": {
        "name": "kalos",
        "url": "/api/v2/region/6/"
    }
}

=== PokeAPI/api-data/data/api/v2/location/714/index.json
{
    "areas": [
        {
            "name": "kalae-bay-area",
            "url": "/api/v2/location-area/1090/"
        }
    ],
    "game_indices": [
        {
            "game_index": 14,
            "generation": {
                "name": "generation-vii",
                "url": "/api/v2/generation/7/"
            }
        }
    ],
    "id": 714,
    "name": "kalae-bay",
    "names": [
        {
            "language": {
                "name": "ja-hrkt",
                "url": "/api/v2/language/1/"
            },
            "name": "\u30ab\u30fc\u30e9\u30a8\u308f\u3093"
        },
        {
            "language": {
                "name": "ko",
                "url": "/api/v2/language/3/"
            },
            "name": "\uce7c\ub77c\uc5d0\ub9cc"
        },
        {
            "language": {
                "name": "zh-hant",
                "url": "/api/v2/language/4/"
            },
            "name": "\u5361\u62c9\u851a\u7063"
        },
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "Baie de Kala\u2019e"
        },
        {
            "language": {
                "name": "de",
                "url": "/api/v2/language/6/"
            },
            "name": "Kala\u2019e-Bucht"
        },
        {
            "language": {
                "name": "es",
                "url": "/api/v2/language/7/"
            },
            "name": "Bah\u00eda Kalae"
        },
        {
            "language": {
                "name": "it",
                "url": "/api/v2/language/8/"
            },
            "name": "Baia Kala\u2019e"
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Kala\u2019e Bay"
        },
        {
            "language": {
                "name": "ja",
                "url": "/api/v2/language/11/"
            },
            "name": "\u30ab\u30fc\u30e9\u30a8\u6e7e"
        },
        {
            "language": {
                "name": "zh-hans",
                "url": "/api/v2/language/12/"
            },
            "name": "\u5361\u62c9\u851a\u6e7e"
        },
        {
            "language": {
                "name": "es-419",
                "url": "/api/v2/language/14/"
            },
            "name": "Bah\u00eda Kalae"
        }
    ],
    "region": {
        "name": "alola",
        "url": "/api/v2/region/7/"
    }
}

=== PokeAPI/api-data/data/api/v2/location/89/index.json
{
    "areas": [
        {
            "name": "kanto-route-10-area",
            "url": "/api/v2/location-area/304/"
        }
    ],
    "game_indices": [
        {
            "game_index": 21,
            "generation": {
                "name": "generation-i",
                "url": "/api/v2/generation/1/"
            }
        },
        {
            "game_index": 67,
            "generation": {
                "name": "generation-ii",
                "url": "/api/v2/generation/2/"
            }
        },
        {
            "game_index": 110,
            "generation": {
                "name": "generation-iii",
                "url": "/api/v2/generation/3/"
            }
        },
        {
            "game_index": 158,
            "generation": {
                "name": "generation-iv",
                "url": "/api/v2/generation/4/"
            }
        }
    ],
    "id": 89,
    "name": "kanto-route-10",
    "names": [
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "Route 10"
        },
        {
            "language": {
                "name": "de",
                "url": "/api/v2/language/6/"
            },
            "name": "Route 10"
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Route 10"
        }
    ],
    "region": {
        "name": "kanto",
        "url": "/api/v2/region/1/"
    }
}
