=== PokeAPI/api-data/data/schema/v2/location/$id/index.json
{
    "$schema": "http://json-schema.org/schema#",
    "properties": {
        "areas": {
            "items": {
                "$ref": "/schema/v2/named_api_resource.json"
            },
            "type": "array"
        },
        "game_indices": {
            "items": {
                "$ref": "/schema/v2/generation_game_index.json"
            },
            "type": "array"
        },
        "id": {
            "type": "integer"
        },
        "name": {
            "type": "string"
        },
        "names": {
            "items": {
                "$ref": "/schema/v2/name.json"
            },
            "type": "array"
        },
        "region": {
            "anyOf": [
                {
                    "type": "null"
                },
                {
                    "$ref": "/schema/v2/named_api_resource.json"
                }
            ]
        }
    },
    "required": [
        "areas",
        "game_indices",
        "id",
        "name",
        "names",
        "region"
    ],
    "type": "object"
}

=== PokeAPI/api-data/data/api/v2/location/613/index.json
{
    "areas": [],
    "game_indices": [
        {
            "game_index": 43,
            "generation": {
                "name": "generation-vi",
                "url": "/api/v2/generation/6/"
            }
        }
    ],
    "id": 613,
    "name": "muraille-coast",
    "names": [
        {
            "language": {
                "name": "ja-hrkt",
                "url": "/api/v2/language/1/"
            },
            "name": "\u30df\u30e5\u30e9\u30a4\u30e6\u304b\u3044\u304c\u3093"
        },
        {
            "language": {
                "name": "ko",
                "url": "/api/v2/language/3/"
            },
            "name": "\ubbf8\ub77c\uc720 \ud574\uc548"
        },
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "Falaise Muraille"
        },
        {
            "language": {
                "name": "de",
                "url": "/api/v2/language/6/"
            },
            "name": "Muraille-K\u00fcstenpfad"
        },
        {
            "language": {
                "name": "es",
                "url": "/api/v2/language/7/"
            },
            "name": "Muralla Costera"
        },
        {
            "language": {
                "name": "it",
                "url": "/api/v2/language/8/"
            },
            "name": "Muraglia Costiera"
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Muraille Coast"
        },
        {
            "language": {
                "name": "ja",
                "url": "/api/v2/language/11/"
            },
            "name": "\u30df\u30e5\u30e9\u30a4\u30e6\u6d77\u5cb8"
        },
        {
            "language": {
                "name": "es-419",
                "url": "/api/v2/language/14/"
            },
            "name": "Muralla Costera"
        }
    ],
    "region": {
        "name": "kalos",
        "url": "/api/v2/region/6/"
    }
}

=== PokeAPI/api-data/data/api/v2/location/469/index.json
{
    "areas": [
        {
            "name": "hoenn-route-121-area",
            "url": "/api/v2/location-area/413/"
        }
    ],
    "game_indices": [
        {
            "game_index": 244,
            "generation": {
                "name": "generation-vi",
                "url": "/api/v2/generation/6/"
            }
        }
    ],
    "id": 469,
    "name": "hoenn-route-121",
    "names": [
        {
            "language": {
                "name": "ja-hrkt",
                "url": "/api/v2/language/1/"
            },
            "name": "\uff11\uff12\uff11\u3070\u3093\u3069\u3046\u308d"
        },
        {
            "language": {
                "name": "ko",
                "url": "/api/v2/language/3/"
            },
            "name": "121\ubc88\ub3c4\ub85c"
        },
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "Route 121"
        },
        {
            "language": {
                "name": "de",
                "url": "/api/v2/language/6/"
            },
            "name": "Route 121"
        },
        {
            "language": {
                "name": "es",
                "url": "/api/v2/language/7/"
            },
            "name": "Ruta 121"
        },
        {
            "language": {
                "name": "it",
                "url": "/api/v2/language/8/"
            },
            "name": "Percorso 121"
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Route 121"
        },
        {
            "language": {
                "name": "ja",
                "url": "/api/v2/language/11/"
            },
            "name": "\uff11\uff12\uff11\u756a\u9053\u8def"
        },
        {
            "language": {
                "name": "es-419",
                "url": "/api/v2/language/14/"
            },
            "name": "Ruta 121"
        }
    ],
    "region": {
        "name": "hoenn",
        "url": "/api/v2/region/3/"
    }
}

=== PokeAPI/api-data/data/api/v2/location/517/index.json
{
    "areas": [
        {
            "name": "ruin-valley-area",
            "url": "/api/v2/location-area/524/"
        }
    ],
    "game_indices": [
        {
            "game_index": 166,
            "generation": {
                "name": "generation-iii",
                "url": "/api/v2/generation/3/"
            }
        }
    ],
    "id": 517,
    "name": "ruin-valley",
    "names": [
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "Vall\u00e9e Ruine"
        },
        {
            "language": {
                "name": "de",
                "url": "/api/v2/language/6/"
            },
            "name": "Ruinental"
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Ruin Valley"
        }
    ],
    "region": {
        "name": "kanto",
        "url": "/api/v2/region/1/"
    }
}

=== PokeAPI/api-data/data/api/v2/location/954/index.json
{
    "areas": [
        {
            "name": "arenas-approach-area",
            "url": "/api/v2/location-area/948/"
        }
    ],
    "game_indices": [],
    "id": 954,
    "name": "arenas-approach",
    "names": [
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Arena's Approach"
        }
    ],
    "region": {
        "name": "hisui",
        "url": "/api/v2/region/9/"
    }
}

=== PokeAPI/api-data/api/v2/location/572/index.json
{
    "areas": [],
    "game_indices": [],
    "id": 572,
    "name": "mauville-city",
    "names": [
        {
            "language": {
                "name": "en",
                "url": "http://localhost/api/v2/language/9/"
            },
            "name": "Mauville City"
        },
        {
            "language": {
                "name": "fr",
                "url": "http://localhost/api/v2/language/5/"
            },
            "name": "Lavandia"
        }
    ],
    "region": {
        "name": "hoenn",
        "url": "http://localhost/api/v2/region/3/"
    }
}

=== PokeAPI/api-data/data/api/v2/location/818/index.json
{
    "areas": [],
    "game_indices": [
        {
            "game_index": 84,
            "generation": {
                "name": "generation-ix",
                "url": "/api/v2/generation/9/"
            }
        }
    ],
    "id": 818,
    "name": "cortondo",
    "names": [
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "Sevaro"
        },
        {
            "language": {
                "name": "de",
                "url": "/api/v2/language/6/"
            },
            "name": "Moldrid"
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Cortondo"
        }
    ],
    "region": {
        "name": "paldea",
        "url": "/api/v2/region/10/"
    }
}

=== PokeAPI/api-data/data/api/v2/location/253/index.json
{
    "areas": [],
    "game_indices": [
        {
            "game_index": 2000,
            "generation": {
                "name": "generation-iv",
                "url": "/api/v2/generation/4/"
            }
        },
        {
            "game_index": 60002,
            "generation": {
                "name": "generation-v",
                "url": "/api/v2/generation/5/"
            }
        },
        {
            "game_index": 60002,
            "generation": {
                "name": "generation-vi",
                "url": "/api/v2/generation/6/"
            }
        }
    ],
    "id": 253,
    "name": "day-care-couple",
    "names": [
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "Couple Pension"
        },
        {
            "language": {
                "name": "de",
                "url": "/api/v2/language/6/"
            },
            "name": "Pensions-Paar"
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Day-Care Couple"
        }
    ],
    "region": null
}

=== PokeAPI/api-data/data/api/v2/location/314/index.json
{
    "areas": [],
    "game_indices": [
        {
            "game_index": 3049,
            "generation": {
                "name": "generation-iv",
                "url": "/api/v2/generation/4/"
            }
        },
        {
            "game_index": 40102,
            "generation": {
                "name": "generation-v",
                "url": "/api/v2/generation/5/"
            }
        }
    ],
    "id": 314,
    "name": "pokepark-14",
    "names": [
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "POK\u00e9PARK 14"
        },
        {
            "language": {
                "name": "de",
                "url": "/api/v2/language/6/"
            },
            "name": ""
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "POK\u00e9PARK 14"
        }
    ],
    "region": null
}
