=== PokeAPI/api-data/data/schema/v2/location/$id/index.json
{
    "$schema": "http://json-schema.org/schema#",
    "properties": {
        "areas": {
            "items": {
                "$ref": "/schema/v2/named_api_resource.json"
            },
            "type": "array"
        },
        "game_indices": {
            "items": {
                "$ref": "/schema/v2/generation_game_index.json"
            },
            "type": "array"
        },
        "id": {
            "type": "integer"
        },
        "name": {
            "type": "string"
        },
        "names": {
            "items": {
                "$ref": "/schema/v2/name.json"
            },
            "type": "array"
        },
        "region": {
            "anyOf": [
                {
                    "type": "null"
                },
                {
                    "$ref": "/schema/v2/named_api_resource.json"
                }
            ]
        }
    },
    "required": [
        "areas",
        "game_indices",
        "id",
        "name",
        "names",
        "region"
    ],
    "type": "object"
}

=== PokeAPI/api-data/data/api/v2/location/184/index.json
{
    "areas": [],
    "game_indices": [
        {
            "game_index": 80,
            "generation": {
                "name": "generation-iv",
                "url": "/api/v2/generation/4/"
            }
        }
    ],
    "id": 184,
    "name": "sinnoh-battle-tower",
    "names": [
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "Tour de Combat"
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Battle Tower"
        }
    ],
    "region": {
        "name": "sinnoh",
        "url": "/api/v2/region/4/"
    }
}

=== PokeAPI/api-data/data/api/v2/location/672/index.json
{
    "areas": [
        {
            "name": "connecting-cave-area",
            "url": "/api/v2/location-area/753/"
        }
    ],
    "game_indices": [
        {
            "game_index": 134,
            "generation": {
                "name": "generation-vi",
                "url": "/api/v2/generation/6/"
            }
        }
    ],
    "id": 672,
    "name": "connecting-cave",
    "names": [
        {
            "language": {
                "name": "ja-hrkt",
                "url": "/api/v2/language/1/"
            },
            "name": "\u3058\u3064\u306a\u304e\u306e\u3069\u3046\u3051\u3064"
        },
        {
            "language": {
                "name": "ko",
                "url": "/api/v2/language/3/"
            },
            "name": "\ub545\uc774\uc74c\uc758 \ub3d9\uad74"
        },
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "Cave Connecterre"
        },
        {
            "language": {
                "name": "de",
                "url": "/api/v2/language/6/"
            },
            "name": "Geolinkh\u00f6hle"
        },
        {
            "language": {
                "name": "es",
                "url": "/api/v2/language/7/"
            },
            "name": "Gruta Tierraunida"
        },
        {
            "language": {
                "name": "it",
                "url": "/api/v2/language/8/"
            },
            "name": "Grotta Trait d\u2019Union"
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Connecting Cave"
        },
        {
            "language": {
                "name": "ja",
                "url": "/api/v2/language/11/"
            },
            "name": "\u5730\u3064\u306a\u304e\u306e\u6d1e\u7a74"
        },
        {
            "language": {
                "name": "es-419",
                "url": "/api/v2/language/14/"
            },
            "name": "Gruta Tierraunida"
        }
    ],
    "region": {
        "name": "kalos",
        "url": "/api/v2/region/6/"
    }
}

=== PokeAPI/api-data/data/api/v2/location/1066/index.json
{
    "areas": [],
    "game_indices": [
        {
            "game_index": 164,
            "generation": {
                "name": "generation-ix",
                "url": "/api/v2/generation/9/"
            }
        }
    ],
    "id": 1066,
    "name": "kitakami-wilds",
    "names": [
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "Terres Vierges de Septentria"
        },
        {
            "language": {
                "name": "de",
                "url": "/api/v2/language/6/"
            },
            "name": "Wildnis von Kitakami"
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Kitakami Wilds"
        }
    ],
    "region": {
        "name": "paldea",
        "url": "/api/v2/region/10/"
    }
}

=== PokeAPI/api-data/data/api/v2/location/1012/index.json
{
    "areas": [
        {
            "name": "sacred-plaza-area",
            "url": "/api/v2/location-area/1006/"
        }
    ],
    "game_indices": [],
    "id": 1012,
    "name": "sacred-plaza",
    "names": [
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Sacred Plaza"
        }
    ],
    "region": {
        "name": "hisui",
        "url": "/api/v2/region/9/"
    }
}

=== PokeAPI/api-data/api/v2/location/646/index.json
{
    "areas": [
        {
            "name": "couriway-town-area",
            "url": "http://localhost/api/v2/location-area/708/"
        }
    ],
    "game_indices": [
        {
            "game_index": 90,
            "generation": {
                "name": "generation-vi",
                "url": "http://localhost/api/v2/generation/6/"
            }
        }
    ],
    "id": 646,
    "name": "couriway-town",
    "names": [
        {
            "language": {
                "name": "ja-kanji",
                "url": "http://localhost/api/v2/language/11/"
            },
            "name": "\u30ec\u30f3\u30ea\u30bf\u30a6\u30f3"
        },
        {
            "language": {
                "name": "en",
                "url": "http://localhost/api/v2/language/9/"
            },
            "name": "Couriway Town"
        },
        {
            "language": {
                "name": "it",
                "url": "http://localhost/api/v2/language/8/"
            },
            "name": "Ponte Mosaico"
        },
        {
            "language": {
                "name": "es",
                "url": "http://localhost/api/v2/language/7/"
            },
            "name": "Pueblo Mosaico"
        },
        {
            "language": {
                "name": "de",
                "url": "http://localhost/api/v2/language/6/"
            },
            "name": "Mosaia"
        },
        {
            "language": {
                "name": "fr",
                "url": "http://localhost/api/v2/language/5/"
            },
            "name": "Mozheim"
        },
        {
            "language": {
                "name": "ko",
                "url": "http://localhost/api/v2/language/3/"
            },
            "name": "\ubc30\ub871\ub9c8\uc744"
        },
        {
            "language": {
                "name": "ja",
                "url": "http://localhost/api/v2/language/1/"
            },
            "name": "\u30ec\u30f3\u30ea\u30bf\u30a6\u30f3"
        }
    ],
    "region": {
        "name": "kalos",
        "url": "http://localhost/api/v2/region/6/"
    }
}
