=== PokeAPI/api-data/data/schema/v2/item/$id/index.json
{
    "$schema": "http://json-schema.org/schema#",
    "properties": {
        "attributes": {
            "items": {
                "$ref": "/schema/v2/named_api_resource.json"
            },
            "type": "array"
        },
        "baby_trigger_for": {
            "anyOf": [
                {
                    "type": "null"
                },
                {
                    "$ref": "/schema/v2/api_resource.json"
                }
            ]
        },
        "category": {
            "$ref": "/schema/v2/named_api_resource.json"
        },
        "cost": {
            "type": "integer"
        },
        "effect_entries": {
            "items": {
                "$ref": "/schema/v2/verbose_effect.json"
            },
            "type": "array"
        },
        "flavor_text_entries": {
            "items": {
                "$ref": "/schema/v2/version_group_flavor_text.json"
            },
            "type": "array"
        },
        "fling_effect": {
            "anyOf": [
                {
                    "type": "null"
                },
                {
                    "$ref": "/schema/v2/named_api_resource.json"
                }
            ]
        },
        "fling_power": {
            "type": [
                "integer",
                "null"
            ]
        },
        "game_indices": {
            "items": {
                "$ref": "/schema/v2/generation_game_index.json"
            },
            "type": "array"
        },
        "held_by_pokemon": {
            "items": {
                "properties": {
                    "pokemon": {
                        "$ref": "/schema/v2/named_api_resource.json"
                    },
                    "version_details": {
                        "items": {
                            "properties": {
                                "rarity": {
                                    "type": "integer"
                                },
                                "version": {
                                    "$ref": "/schema/v2/named_api_resource.json"
                                }
                            },
                            "required": [
                                "rarity",
                                "version"
                            ],
                            "type": "object"
                        },
                        "type": "array"
                    }
                },
                "required": [
                    "pokemon",
                    "version_details"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "id": {
            "type": "integer"
        },
        "machines": {
            "items": {
                "$ref": "/schema/v2/machine_version_detail.json"
            },
            "type": "array"
        },
        "name": {
            "type": "string"
        },
        "names": {
            "items": {
                "$ref": "/schema/v2/name.json"
            },
            "type": "array"
        },
        "sprites": {
            "properties": {
                "default": {
                    "type": [
                        "null",
                        "string"
                    ]
                }
            },
            "required": [
                "default"
            ],
            "type": "object"
        }
    },
    "required": [
        "attributes",
        "baby_trigger_for",
        "category",
        "cost",
        "effect_entries",
        "flavor_text_entries",
        "fling_effect",
        "fling_power",
        "game_indices",
        "held_by_pokemon",
        "id",
        "machines",
        "name",
        "names",
        "sprites"
    ],
    "type": "object"
}

=== PokeAPI/api-data/data/api/v2/item/1179/index.json
{
    "attributes": [],
    "baby_trigger_for": null,
    "category": {
        "name": "held-items",
        "url": "/api/v2/item-category/12/"
    },
    "cost": 4000,
    "effect_entries": [],
    "flavor_text_entries": [
        {
            "language": {
                "name": "ja-hrkt",
                "url": "/api/v2/language/1/"
            },
            "text": "\u3081\u3044\u3061\u3085\u3046\u308a\u3064\u306b\u3000\u3088\u3063\u3066\n\u308f\u3056\u304c\u3000\u306f\u305a\u308c\u305f\u3068\u304d\n\u3059\u3070\u3084\u3055\u304c\u3000\u3050\u30fc\u3093\u3068\u3000\u3042\u304c\u308b\u3002",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        },
        {
            "language": {
                "name": "ko",
                "url": "/api/v2/language/3/"
            },
            "text": "\uba85\uc911\ub960\uc5d0 \uc758\ud574\n\uae30\uc220\uc774 \ube57\ub098\uac14\uc744 \ub54c\n\uc2a4\ud53c\ub4dc\uac00 \ud06c\uac8c \uc62c\ub77c\uac04\ub2e4.",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        },
        {
            "language": {
                "name": "zh-hant",
                "url": "/api/v2/language/4/"
            },
            "text": "\u7576\u62db\u5f0f\u53d7\u547d\u4e2d\u7387\u5f71\u97ff\n\u800c\u672a\u80fd\u64ca\u4e2d\u5c0d\u624b\u6642\uff0c\n\u81ea\u5df1\u7684\u901f\u5ea6\u5c07\u5927\u5e45\u63d0\u9ad8\u3002",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        },
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "text": "Si un Pok\u00e9mon manque sa cible parce qu\u2019une capacit\u00e9\na peu de Pr\u00e9cision, sa Vitesse augmente beaucoup.",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        },
        {
            "language": {
                "name": "de",
                "url": "/api/v2/language/6/"
            },
            "text": "Schl\u00e4gt eine Attacke des Anwenders mangels\nGenauigkeit fehl, steigt im Gegenzug dessen\nInitiative stark an.",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        },
        {
            "language": {
                "name": "es",
                "url": "/api/v2/language/7/"
            },
            "text": "Aumenta mucho la Velocidad cuando el Pok\u00e9mon yerra\nel movimiento debido a la precisi\u00f3n.",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        },
        {
            "language": {
                "name": "it",
                "url": "/api/v2/language/8/"
            },
            "text": "Se una mossa non va a segno a causa della scarsa\nprecisione, la Velocit\u00e0 aumenta considerevolmente.",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "text": "Raises Speed sharply when a Pok\u00e9mon misses with a\nmove because of accuracy.",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        },
        {
            "language": {
                "name": "ja",
                "url": "/api/v2/language/11/"
            },
            "text": "\u547d\u4e2d\u7387\u306b\u3000\u3088\u3063\u3066\n\u6280\u304c\u3000\u306f\u305a\u308c\u305f\u3068\u304d\n\u7d20\u65e9\u3055\u304c\u3000\u3050\u30fc\u3093\u3068\u3000\u4e0a\u304c\u308b\u3002",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        },
        {
            "language": {
                "name": "zh-hans",
                "url": "/api/v2/language/12/"
            },
            "text": "\u62db\u5f0f\u56e0\u547d\u4e2d\u7387\u5f71\u54cd\u800c\u843d\u7a7a\u65f6\uff0c\n\u901f\u5ea6\u4f1a\u5927\u5e45\u63d0\u9ad8\u3002",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        },
        {
            "language": {
                "name": "es-419",
                "url": "/api/v2/language/14/"
            },
            "text": "Aumenta mucho la Velocidad cuando el Pok\u00e9mon yerra\nel movimiento debido a la precisi\u00f3n.",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        }
    ],
    "fling_effect": null,
    "fling_power": 80,
    "game_indices": [
        {
            "game_index": 1121,
            "generation": {
                "name": "generation-viii",
                "url": "/api/v2/generation/8/"
            }
        }
    ],
    "held_by_pokemon": [],
    "id": 1179,
    "machines": [],
    "name": "blunder-policy",
    "names": [
        {
            "language": {
                "name": "ja-hrkt",
                "url": "/api/v2/language/1/"
            },
            "name": "\u304b\u3089\u3076\u308a\u307b\u3051\u3093"
        },
        {
            "language": {
                "name": "ko",
                "url": "/api/v2/language/3/"
            },
            "name": "\ud5c8\ud0d5\ubcf4\ud5d8"
        },
        {
            "language": {
                "name": "zh-hant",
                "url": "/api/v2/language/4/"
            },
            "name": "\u6253\u7a7a\u4fdd\u96aa"
        },
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "Assurance \u00c9chec"
        },
        {
            "language": {
                "name": "de",
                "url": "/api/v2/language/6/"
            },
            "name": "Fehlschlagschutz"
        },
        {
            "language": {
                "name": "es",
                "url": "/api/v2/language/7/"
            },
            "name": "Seguro Fallo"
        },
        {
            "language": {
                "name": "it",
                "url": "/api/v2/language/8/"
            },
            "name": "Fiascopolizza"
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Blunder Policy"
        },
        {
            "language": {
                "name": "ja",
                "url": "/api/v2/language/11/"
            },
            "name": "\u304b\u3089\u3076\u308a\u307b\u3051\u3093"
        },
        {
            "language": {
                "name": "zh-hans",
                "url": "/api/v2/language/12/"
            },
            "name": "\u6253\u7a7a\u4fdd\u9669"
        },
        {
            "language": {
                "name": "es-419",
                "url": "/api/v2/language/14/"
            },
            "name": "Seguro Fallo"
        }
    ],
    "sprites": {
        "default": null
    }
}

=== PokeAPI/api-data/data/api/v2/item/2115/index.json
{
    "attributes": [],
    "baby_trigger_for": null,
    "category": {
        "name": "vitamins",
        "url": "/api/v2/item-category/26/"
    },
    "cost": 125,
    "effect_entries": [],
    "flavor_text_entries": [],
    "fling_effect": null,
    "fling_power": null,
    "game_indices": [
        {
            "game_index": 2414,
            "generation": {
                "name": "generation-ix",
                "url": "/api/v2/generation/9/"
            }
        }
    ],
    "held_by_pokemon": [],
    "id": 2115,
    "machines": [],
    "name": "genius-mochi",
    "names": [
        {
            "language": {
                "name": "ja-hrkt",
                "url": "/api/v2/language/1/"
            },
            "name": "\u3061\u308a\u3087\u304f\u306e\u3082\u3061"
        },
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "Mochi Esprit"
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Genius Mochi"
        },
        {
            "language": {
                "name": "ja",
                "url": "/api/v2/language/11/"
            },
            "name": "\u3061\u308a\u3087\u304f\u306e\u3082\u3061"
        }
    ],
    "sprites": {
        "default": null
    }
}

=== PokeAPI/api-data/data/api/v2/item/1821/index.json
{
    "attributes": [],
    "baby_trigger_for": null,
    "category": {
        "name": "tm-materials",
        "url": "/api/v2/item-category/54/"
    },
    "cost": 160,
    "effect_entries": [],
    "flavor_text_entries": [],
    "fling_effect": null,
    "fling_power": null,
    "game_indices": [
        {
            "game_index": 2015,
            "generation": {
                "name": "generation-ix",
                "url": "/api/v2/generation/9/"
            }
        }
    ],
    "held_by_pokemon": [],
    "id": 1821,
    "machines": [],
    "name": "luvdisc-scales",
    "names": [
        {
            "language": {
                "name": "ja-hrkt",
                "url": "/api/v2/language/1/"
            },
            "name": "\u30e9\u30d6\u30ab\u30b9\u306e\u30a6\u30ed\u30b3"
        },
        {
            "language": {
                "name": "zh-hant",
                "url": "/api/v2/language/4/"
            },
            "name": "\u7231\u5fc3\u9c7c\u7684\u9cde\u7247"
        },
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "\u00c9caille de Lovdisc"
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Luvdisc Scales"
        },
        {
            "language": {
                "name": "ja",
                "url": "/api/v2/language/11/"
            },
            "name": "\u30e9\u30d6\u30ab\u30b9\u306e\u30a6\u30ed\u30b3"
        }
    ],
    "sprites": {
        "default": null
    }
}

=== PokeAPI/api-data/data/api/v2/item/1242/index.json
{
    "attributes": [],
    "baby_trigger_for": null,
    "category": {
        "name": "all-machines",
        "url": "/api/v2/item-category/37/"
    },
    "cost": 4000,
    "effect_entries": [],
    "flavor_text_entries": [
        {
            "language": {
                "name": "ja-hrkt",
                "url": "/api/v2/language/1/"
            },
            "text": "\u3042\u3044\u3066\u306e\u3000\u3042\u3057\u3082\u3068\u306b\u3000\u3069\u304f\u3073\u3057\u3092\n\u3057\u304b\u3051\u308b\u3002\u3000\u3053\u3046\u305f\u3044\u3067\u3000\u3067\u3066\u304d\u305f\u3000\u3042\u3044\u3066\u306e\n\u30dd\u30b1\u30e2\u30f3\u306b\u3000\u3069\u304f\u3092\u3000\u304a\u308f\u305b\u308b\u3002",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        },
        {
            "language": {
                "name": "ko",
                "url": "/api/v2/language/3/"
            },
            "text": "\uc0c1\ub300\uc758 \ubc1c\ubc11\uc5d0 \ub3c5 \uc555\uc815\uc744\n\ubfcc\ub9b0\ub2e4. \uad50\uccb4\ub85c \ub098\uc628 \uc0c1\ub300\n\ud3ec\ucf13\ubaac\uc5d0\uac8c \ub3c5\uc744 \ud37c\uc9c0\uac8c \ud55c\ub2e4.",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        },
        {
            "language": {
                "name": "zh-hant",
                "url": "/api/v2/language/4/"
            },
            "text": "\u5728\u5c0d\u624b\u8173\u4e0b\u6563\u5e03\u6bd2\u83f1\u3002\n\u8b93\u5c0d\u624b\u66ff\u63db\u51fa\u5834\u7684\u5bf6\u53ef\u5922\n\u9677\u5165\u4e2d\u6bd2\u72c0\u614b\u3002",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        },
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "text": "Lance des pics autour de l\u2019ennemi.\nIls empoisonnent les ennemis qui entrent au combat.",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        },
        {
            "language": {
                "name": "de",
                "url": "/api/v2/language/6/"
            },
            "text": "Anwender legt eine Falle mit Giftdornen aus. In den\nKampf eingewechselte gegnerische Pok\u00e9mon werden\nvergiftet.",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        },
        {
            "language": {
                "name": "es",
                "url": "/api/v2/language/7/"
            },
            "text": "Lanza una trampa de p\u00faas t\u00f3xicas a los pies del\nobjetivo. El veneno afecta a los Pok\u00e9mon oponentes\nque entran en combate.",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        },
        {
            "language": {
                "name": "it",
                "url": "/api/v2/language/8/"
            },
            "text": "Chi la usa piazza una trappola di punte che\navvelenano i nemici che scendono in campo.",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "text": "The user lays a trap of poison spikes at the feet of\nthe opposing team. The spikes will poison opposing\nPok\u00e9mon that switch into battle.",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        },
        {
            "language": {
                "name": "ja",
                "url": "/api/v2/language/11/"
            },
            "text": "\u76f8\u624b\u306e\u3000\u8db3\u4e0b\u306b\u3000\u3069\u304f\u3073\u3057\u3092\n\u3057\u304b\u3051\u308b\u3002\u3000\u4ea4\u4ee3\u3067\u3000\u3067\u3066\u304d\u305f\u3000\u76f8\u624b\u306e\n\u30dd\u30b1\u30e2\u30f3\u306b\u3000\u6bd2\u3092\u3000\u304a\u308f\u305b\u308b\u3002",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        },
        {
            "language": {
                "name": "zh-hans",
                "url": "/api/v2/language/12/"
            },
            "text": "\u5728\u5bf9\u624b\u7684\u811a\u4e0b\u6492\u6bd2\u83f1\u3002\n\u4f7f\u5bf9\u624b\u66ff\u6362\u51fa\u573a\u7684\u5b9d\u53ef\u68a6\u4e2d\u6bd2\u3002",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        },
        {
            "language": {
                "name": "es-419",
                "url": "/api/v2/language/14/"
            },
            "text": "Lanza una trampa de p\u00faas t\u00f3xicas a los pies del\nobjetivo. El veneno afecta a los Pok\u00e9mon oponentes\nque entran en combate.",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        }
    ],
    "fling_effect": null,
    "fling_power": 10,
    "game_indices": [
        {
            "game_index": 1184,
            "generation": {
                "name": "generation-viii",
                "url": "/api/v2/generation/8/"
            }
        }
    ],
    "held_by_pokemon": [],
    "id": 1242,
    "machines": [
        {
            "machine": {
                "url": "/api/v2/machine/1753/"
            },
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        }
    ],
    "name": "tr54",
    "names": [
        {
            "language": {
                "name": "ja-hrkt",
                "url": "/api/v2/language/1/"
            },
            "name": "\u308f\u3056\u30ec\u30b3\u30fc\u30c9\uff15\uff14"
        },
        {
            "language": {
                "name": "ko",
                "url": "/api/v2/language/3/"
            },
            "name": "\uae30\uc220\ub808\ucf54\ub4dc54"
        },
        {
            "language": {
                "name": "zh-hant",
                "url": "/api/v2/language/4/"
            },
            "name": "\u62db\u5f0f\u7d00\u9304\uff15\uff14"
        },
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "DT54"
        },
        {
            "language": {
                "name": "de",
                "url": "/api/v2/language/6/"
            },
            "name": "TP54"
        },
        {
            "language": {
                "name": "es",
                "url": "/api/v2/language/7/"
            },
            "name": "DT54"
        },
        {
            "language": {
                "name": "it",
                "url": "/api/v2/language/8/"
            },
            "name": "DT54"
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "TR54"
        },
        {
            "language": {
                "name": "ja",
                "url": "/api/v2/language/11/"
            },
            "name": "\u308f\u3056\u30ec\u30b3\u30fc\u30c9\uff15\uff14"
        },
        {
            "language": {
                "name": "zh-hans",
                "url": "/api/v2/language/12/"
            },
            "name": "\u62db\u5f0f\u8bb0\u5f55\uff15\uff14"
        },
        {
            "language": {
                "name": "es-419",
                "url": "/api/v2/language/14/"
            },
            "name": "DT54"
        }
    ],
    "sprites": {
        "default": null
    }
}
