=== PokeAPI/api-data/data/schema/v2/item/$id/index.json
{
    "$schema": "http://json-schema.org/schema#",
    "properties": {
        "attributes": {
            "items": {
                "$ref": "/schema/v2/named_api_resource.json"
            },
            "type": "array"
        },
        "baby_trigger_for": {
            "anyOf": [
                {
                    "type": "null"
                },
                {
                    "$ref": "/schema/v2/api_resource.json"
                }
            ]
        },
        "category": {
            "$ref": "/schema/v2/named_api_resource.json"
        },
        "cost": {
            "type": "integer"
        },
        "effect_entries": {
            "items": {
                "$ref": "/schema/v2/verbose_effect.json"
            },
            "type": "array"
        },
        "flavor_text_entries": {
            "items": {
                "$ref": "/schema/v2/version_group_flavor_text.json"
            },
            "type": "array"
        },
        "fling_effect": {
            "anyOf": [
                {
                    "type": "null"
                },
                {
                    "$ref": "/schema/v2/named_api_resource.json"
                }
            ]
        },
        "fling_power": {
            "type": [
                "integer",
                "null"
            ]
        },
        "game_indices": {
            "items": {
                "$ref": "/schema/v2/generation_game_index.json"
            },
            "type": "array"
        },
        "held_by_pokemon": {
            "items": {
                "properties": {
                    "pokemon": {
                        "$ref": "/schema/v2/named_api_resource.json"
                    },
                    "version_details": {
                        "items": {
                            "properties": {
                                "rarity": {
                                    "type": "integer"
                                },
                                "version": {
                                    "$ref": "/schema/v2/named_api_resource.json"
                                }
                            },
                            "required": [
                                "rarity",
                                "version"
                            ],
                            "type": "object"
                        },
                        "type": "array"
                    }
                },
                "required": [
                    "pokemon",
                    "version_details"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "id": {
            "type": "integer"
        },
        "machines": {
            "items": {
                "$ref": "/schema/v2/machine_version_detail.json"
            },
            "type": "array"
        },
        "name": {
            "type": "string"
        },
        "names": {
            "items": {
                "$ref": "/schema/v2/name.json"
            },
            "type": "array"
        },
        "sprites": {
            "properties": {
                "default": {
                    "type": [
                        "null",
                        "string"
                    ]
                }
            },
            "required": [
                "default"
            ],
            "type": "object"
        }
    },
    "required": [
        "attributes",
        "baby_trigger_for",
        "category",
        "cost",
        "effect_entries",
        "flavor_text_entries",
        "fling_effect",
        "fling_power",
        "game_indices",
        "held_by_pokemon",
        "id",
        "machines",
        "name",
        "names",
        "sprites"
    ],
    "type": "object"
}

=== PokeAPI/api-data/api/v2/item/444/index.json
{
    "attributes": [],
    "baby_trigger_for": null,
    "category": {
        "name": "event-items",
        "url": "http://localhost/api/v2/item-category/20/"
    },
    "cost": 0,
    "effect_entries": [
        {
            "effect": "Used by trainer on a shaymin\n:   Changes the target Shaymin from Land Forme to Sky Forme.\n\n    This item cannot be used on a frozen Shaymin or at night.  Sky Forme Shaymin will revert to Land Forme overnight, when frozen, and upon entering a link battle.  This item must be used again to change it back.",
            "language": {
                "name": "en",
                "url": "http://localhost/api/v2/language/9/"
            },
            "short_effect": "Changes an unfrozen Shaymin to Sky Forme in the day."
        }
    ],
    "flavor_text_entries": [
        {
            "language": {
                "name": "ja-kanji",
                "url": "http://localhost/api/v2/language/11/"
            },
            "text": "\u8a95\u751f\u65e5\u3084\u3000\u8a18\u5ff5\u65e5\u306a\u3069\u306b\n\u611f\u8b1d\u306e\u3000\u6c17\u6301\u3061\u3092\u3000\u4f1d\u3048\u308b\u305f\u3081\n\u30d6\u30fc\u30b1\u306b\u3057\u3066\u3000\u8d08\u308b\u3053\u3068\u304c\u3000\u3042\u308b\u3002",
            "version_group": {
                "name": "x-y",
                "url": "http://localhost/api/v2/version-group/15/"
            }
        },
        {
            "language": {
                "name": "en",
                "url": "http://localhost/api/v2/language/9/"
            },
            "text": "A flower sometimes bundled in\nbouquets to convey gratitude on\nspecial occasions like birthdays.",
            "version_group": {
                "name": "x-y",
                "url": "http://localhost/api/v2/version-group/15/"
            }
        },
        {
            "language": {
                "name": "it",
                "url": "http://localhost/api/v2/language/8/"
            },
            "text": "Un fiore, a volte offerto in bouquet, che\nesprime gratitudine in occasioni particolari,\ncome i compleanni.",
            "version_group": {
                "name": "x-y",
                "url": "http://localhost/api/v2/version-group/15/"
            }
        },
        {
            "language": {
                "name": "es",
                "url": "http://localhost/api/v2/language/7/"
            },
            "text": "Bonguri de color rojo y aroma muy penetrante.",
            "version_group": {
                "name": "x-y",
                "url": "http://localhost/api/v2/version-group/15/"
            }
        },
        {
            "language": {
                "name": "de",
                "url": "http://localhost/api/v2/language/6/"
            },
            "text": "Mit dieser Blume, manchmal auch als Teil eines\nBouquets, kann man an speziellen Tagen seine\nDankbarkeit ausdr\u00fccken.",
            "version_group": {
                "name": "x-y",
                "url": "http://localhost/api/v2/version-group/15/"
            }
        },
        {
            "language": {
                "name": "fr",
                "url": "http://localhost/api/v2/language/5/"
            },
            "text": "Une fleur que l\u2019on offre en gage de\nreconnaissance, notamment \u00e0 l\u2019occasion\nd\u2019un anniversaire.",
            "version_group": {
                "name": "x-y",
                "url": "http://localhost/api/v2/version-group/15/"
            }
        },
        {
            "language": {
                "name": "ko",
                "url": "http://localhost/api/v2/language/3/"
            },
            "text": "\uc0dd\uc77c\uc774\ub098 \uae30\ub150\uc77c \ub4f1\uc5d0\n\uac10\uc0ac\uc758 \ub9c8\uc74c\uc744 \uc804\ud558\uae30 \uc704\ud574\n\ubd80\ucf00\ub85c \ub9cc\ub4e4\uc5b4 \ubcf4\ub0b4\ub294 \uc77c\uc774 \uc788\ub2e4.",
            "version_group": {
                "name": "x-y",
                "url": "http://localhost/api/v2/version-group/15/"
            }
        },
        {
            "language": {
                "name": "ja",
                "url": "http://localhost/api/v2/language/1/"
            },
            "text": "\u305f\u3093\u3058\u3087\u3046\u3073\u3084\u3000\u304d\u306d\u3093\u3073\u3000\u306a\u3069\u306b\n\u304b\u3093\u3057\u3083\u306e\u3000\u304d\u3082\u3061\u3092\u3000\u3064\u305f\u3048\u308b\u305f\u3081\n\u30d6\u30fc\u30b1\u306b\u3057\u3066\u3000\u304a\u304f\u308b\u3053\u3068\u304c\u3000\u3042\u308b\u3002",
            "version_group": {
                "name": "x-y",
                "url": "http://localhost/api/v2/version-group/15/"
            }
        },
        {
            "language": {
                "name": "en",
                "url": "http://localhost/api/v2/language/9/"
            },
            "text": "A flower sometimes bundled in bouquets\nto convey gratitude on special\noccasions like birthdays.",
            "version_group": {
                "name": "black-2-white-2",
                "url": "http://localhost/api/v2/version-group/14/"
            }
        },
        {
            "language": {
                "name": "en",
                "url": "http://localhost/api/v2/language/9/"
            },
            "text": "A flower sometimes bundled in bouquets\nto convey gratitude on special\noccasions like birthdays.",
            "version_group": {
                "name": "black-white",
                "url": "http://localhost/api/v2/version-group/11/"
            }
        },
        {
            "language": {
                "name": "fr",
                "url": "http://localhost/api/v2/language/5/"
            },
            "text": "Fleur que l\u2019on offre en gage de\nreconnaissance, notamment \u00e0\nl\u2019occasion d\u2019un anniversaire.",
            "version_group": {
                "name": "black-white",
                "url": "http://localhost/api/v2/version-group/11/"
            }
        },
        {
            "language": {
                "name": "en",
                "url": "http://localhost/api/v2/language/9/"
            },
            "text": "A flower sometimes bundled in bouquets\nto convey gratitude on special\noccasions like birthdays.",
            "version_group": {
                "name": "heartgold-soulsilver",
                "url": "http://localhost/api/v2/version-group/10/"
            }
        },
        {
            "language": {
                "name": "en",
                "url": "http://localhost/api/v2/language/9/"
            },
            "text": "A flower sometimes bundled in bouquets\nto convey gratitude on special\noccasions like birthdays.",
            "version_group": {
                "name": "platinum",
                "url": "http://localhost/api/v2/version-group/9/"
            }
        }
    ],
    "fling_effect": null,
    "fling_power": null,
    "game_indices": [
        {
            "game_index": 466,
            "generation": {
                "name": "generation-vi",
                "url": "http://localhost/api/v2/generation/6/"
            }
        },
        {
            "game_index": 466,
            "generation": {
                "name": "generation-v",
                "url": "http://localhost/api/v2/generation/5/"
            }
        },
        {
            "game_index": 466,
            "generation": {
                "name": "generation-iv",
                "url": "http://localhost/api/v2/generation/4/"
            }
        }
    ],
    "held_by_pokemon": [],
    "id": 444,
    "machines": [],
    "name": "gracidea",
    "names": [
        {
            "language": {
                "name": "en",
                "url": "http://localhost/api/v2/language/9/"
            },
            "name": "Gracidea"
        },
        {
            "language": {
                "name": "it",
                "url": "http://localhost/api/v2/language/8/"
            },
            "name": "Gracidea"
        },
        {
            "language": {
                "name": "es",
                "url": "http://localhost/api/v2/language/7/"
            },
            "name": "Grac\u00eddea"
        },
        {
            "language": {
                "name": "de",
                "url": "http://localhost/api/v2/language/6/"
            },
            "name": "Gracidea"
        },
        {
            "language": {
                "name": "fr",
                "url": "http://localhost/api/v2/language/5/"
            },
            "name": "Gracid\u00e9e"
        },
        {
            "language": {
                "name": "ko",
                "url": "http://localhost/api/v2/language/3/"
            },
            "name": "\uadf8\ub77c\uc2dc\ub370\uc544\uaf43"
        },
        {
            "language": {
                "name": "ja",
                "url": "http://localhost/api/v2/language/1/"
            },
            "name": "\u30b0\u30e9\u30b7\u30c7\u30a2\u306e\u306f\u306a"
        }
    ],
    "sprites": {
        "default": "http://localhost/media/sprites/items/gracidea.png"
    }
}

=== PokeAPI/api-data/data/api/v2/item/1467/index.json
{
    "attributes": [],
    "baby_trigger_for": null,
    "category": {
        "name": "dynamax-crystals",
        "url": "/api/v2/item-category/49/"
    },
    "cost": 20,
    "effect_entries": [],
    "flavor_text_entries": [
        {
            "language": {
                "name": "ja-hrkt",
                "url": "/api/v2/language/1/"
            },
            "text": "\u3064\u304b\u3063\u305f\u3000\u3072\u306b\u3000\u30ef\u30a4\u30eb\u30c9\u30a8\u30ea\u30a2\u306e\n\u307f\u306f\u308a\u3068\u3046\u306e\u30c0\u30a4\u3059\u3042\u306a\u3000\u304b\u3089\n[VAR (0000)]\u304c\u3000\u3042\u3089\u308f\u308c\u308b\u3002",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        },
        {
            "language": {
                "name": "ko",
                "url": "/api/v2/language/3/"
            },
            "text": "\uc0ac\uc6a9\ud55c \ub2f9\uc77c\uc5d0\ub9cc \uc640\uc77c\ub4dc\uc5d0\ub9ac\uc5b4\uc5d0 \uc788\ub294\n\uac10\uc2dc\ud0d1\uc758 \ub2e4\uc774\ub9e5\uc2a4\uad74\uc5d0\uc11c\n[VAR (0000)][VAR (0003)] \ub098\ud0c0\ub09c\ub2e4.",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        },
        {
            "language": {
                "name": "zh-hant",
                "url": "/api/v2/language/4/"
            },
            "text": "\u4f7f\u7528\u5f8c\u7684\u7576\u5929\uff0c\n[VAR (0000)]\u6703\u51fa\u73fe\u5728\n\u66e0\u91ce\u5730\u5e36\u7684\u77ad\u671b\u5854\u5de8\u5de2\u3002",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        },
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "text": "Un objet faisant appara\u00eetre un [VAR (0000)]\ndans l\u2019antre g\u00e9ant de la Tour en ruines\ndes Terres Sauvages jusqu\u2019\u00e0 la fin de la journ\u00e9e.",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        },
        {
            "language": {
                "name": "de",
                "url": "/api/v2/language/6/"
            },
            "text": "Dieses Item bewirkt, dass im Wachturm-Nest in der\nNaturzone ein [VAR (0000)] bis zum Ende des Tages\nerscheint, an dem das Item eingesetzt wurde.",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        },
        {
            "language": {
                "name": "es",
                "url": "/api/v2/language/7/"
            },
            "text": "Posibilita la aparici\u00f3n de [VAR (0000)] en el nido\nDinamax de la Atalaya del \u00c1rea Silvestre hasta finalizar\nel d\u00eda en que se ha usado.",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        },
        {
            "language": {
                "name": "it",
                "url": "/api/v2/language/8/"
            },
            "text": "Strumento che fa apparire [VAR (0000)] nella\ndynatana della Torre Diroccata, nelle Terre Selvagge,\nfino alla fine del giorno in cui viene usato.",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "text": "An item that causes [VAR (0000)] to appear from\nthe Watchtower Lair in the Wild Area until the end of\nthe day.",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        },
        {
            "language": {
                "name": "ja",
                "url": "/api/v2/language/11/"
            },
            "text": "\u4f7f\u3063\u305f\u3000\u65e5\u306b\u3000\u30ef\u30a4\u30eb\u30c9\u30a8\u30ea\u30a2\u306e\n\u898b\u5f35\u308a\u5854\u306e\u30c0\u30a4\u5de3\u7a74\u3000\u304b\u3089\n[VAR (0000)]\u304c\u3000\u73fe\u308c\u308b\u3002",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        },
        {
            "language": {
                "name": "zh-hans",
                "url": "/api/v2/language/12/"
            },
            "text": "\u4f7f\u7528\u540e\u7684\u5f53\u5929\uff0c\n\u65f7\u91ce\u5730\u5e26\u7684\u77ad\u671b\u5854\u5de8\u5de2\u4e2d\n\u4f1a\u51fa\u73b0[VAR (0000)]\u3002",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        },
        {
            "language": {
                "name": "es-419",
                "url": "/api/v2/language/14/"
            },
            "text": "Posibilita la aparici\u00f3n de [VAR (0000)] en el nido\nDinamax de la Atalaya del \u00c1rea Silvestre hasta finalizar\nel d\u00eda en que se ha usado.",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        }
    ],
    "fling_effect": null,
    "fling_power": null,
    "game_indices": [
        {
            "game_index": 1416,
            "generation": {
                "name": "generation-viii",
                "url": "/api/v2/generation/8/"
            }
        }
    ],
    "held_by_pokemon": [],
    "id": 1467,
    "machines": [],
    "name": "dynamax-crystal-cet681",
    "names": [
        {
            "language": {
                "name": "ja-hrkt",
                "url": "/api/v2/language/1/"
            },
            "name": "\u2605Cet681"
        },
        {
            "language": {
                "name": "ko",
                "url": "/api/v2/language/3/"
            },
            "name": "\u2605Cet681"
        },
        {
            "language": {
                "name": "zh-hant",
                "url": "/api/v2/language/4/"
            },
            "name": "\u2605Cet681"
        },
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "\u2605Cet681"
        },
        {
            "language": {
                "name": "de",
                "url": "/api/v2/language/6/"
            },
            "name": "\u2605Cet681"
        },
        {
            "language": {
                "name": "es",
                "url": "/api/v2/language/7/"
            },
            "name": "\u2605Cet681"
        },
        {
            "language": {
                "name": "it",
                "url": "/api/v2/language/8/"
            },
            "name": "\u2605Cet681"
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "\u2605Cet681"
        },
        {
            "language": {
                "name": "ja",
                "url": "/api/v2/language/11/"
            },
            "name": "\u2605Cet681"
        },
        {
            "language": {
                "name": "zh-hans",
                "url": "/api/v2/language/12/"
            },
            "name": "\u2605Cet681"
        },
        {
            "language": {
                "name": "es-419",
                "url": "/api/v2/language/14/"
            },
            "name": "\u2605Cet681"
        }
    ],
    "sprites": {
        "default": null
    }
}

=== PokeAPI/api-data/data/api/v2/item/2065/index.json
{
    "attributes": [],
    "baby_trigger_for": null,
    "category": {
        "name": "picnic",
        "url": "/api/v2/item-category/55/"
    },
    "cost": 3000,
    "effect_entries": [],
    "flavor_text_entries": [],
    "fling_effect": null,
    "fling_power": null,
    "game_indices": [
        {
            "game_index": 2366,
            "generation": {
                "name": "generation-ix",
                "url": "/api/v2/generation/9/"
            }
        }
    ],
    "held_by_pokemon": [],
    "id": 2065,
    "machines": [],
    "name": "plaid-tablecloth-y",
    "names": [
        {
            "language": {
                "name": "ja-hrkt",
                "url": "/api/v2/language/1/"
            },
            "name": "\u304d\u3044\u308d\u30c1\u30a7\u30c3\u30af\u30af\u30ed\u30b9"
        },
        {
            "language": {
                "name": "zh-hant",
                "url": "/api/v2/language/4/"
            },
            "name": "\u9ec4\u8272\u683c\u5b50\u684c\u5dfe"
        },
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "Nappe Tartan Jaune"
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Plaid Tablecloth (Y)"
        },
        {
            "language": {
                "name": "ja",
                "url": "/api/v2/language/11/"
            },
            "name": "\u304d\u3044\u308d\u30c1\u30a7\u30c3\u30af\u30af\u30ed\u30b9"
        }
    ],
    "sprites": {
        "default": null
    }
}

=== PokeAPI/api-data/data/api/v2/item/2030/index.json
{
    "attributes": [],
    "baby_trigger_for": null,
    "category": {
        "name": "picnic",
        "url": "/api/v2/item-category/55/"
    },
    "cost": 4000,
    "effect_entries": [],
    "flavor_text_entries": [],
    "fling_effect": null,
    "fling_power": null,
    "game_indices": [
        {
            "game_index": 2327,
            "generation": {
                "name": "generation-ix",
                "url": "/api/v2/generation/9/"
            }
        }
    ],
    "held_by_pokemon": [],
    "id": 2030,
    "machines": [],
    "name": "spooky-tablecloth",
    "names": [
        {
            "language": {
                "name": "ja-hrkt",
                "url": "/api/v2/language/1/"
            },
            "name": "\u3046\u3089\u3081\u3057\u30af\u30ed\u30b9"
        },
        {
            "language": {
                "name": "zh-hant",
                "url": "/api/v2/language/4/"
            },
            "name": "\u9b3c\u795f\u684c\u5dfe"
        },
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "Nappe Hant\u00e9e"
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Spooky Tablecloth"
        },
        {
            "language": {
                "name": "ja",
                "url": "/api/v2/language/11/"
            },
            "name": "\u3046\u3089\u3081\u3057\u30af\u30ed\u30b9"
        }
    ],
    "sprites": {
        "default": null
    }
}

=== PokeAPI/api-data/data/api/v2/item/1968/index.json
{
    "attributes": [],
    "baby_trigger_for": null,
    "category": {
        "name": "all-machines",
        "url": "/api/v2/item-category/37/"
    },
    "cost": 0,
    "effect_entries": [],
    "flavor_text_entries": [],
    "fling_effect": null,
    "fling_power": null,
    "game_indices": [],
    "held_by_pokemon": [],
    "id": 1968,
    "machines": [
        {
            "machine": {
                "url": "/api/v2/machine/1940/"
            },
            "version_group": {
                "name": "scarlet-violet",
                "url": "/api/v2/version-group/25/"
            }
        },
        {
            "machine": {
                "url": "/api/v2/machine/2133/"
            },
            "version_group": {
                "name": "the-indigo-disk",
                "url": "/api/v2/version-group/27/"
            }
        },
        {
            "machine": {
                "url": "/api/v2/machine/2337/"
            },
            "version_group": {
                "name": "mega-dimension",
                "url": "/api/v2/version-group/31/"
            }
        }
    ],
    "name": "tm125",
    "names": [
        {
            "language": {
                "name": "ja-hrkt",
                "url": "/api/v2/language/1/"
            },
            "name": "\u308f\u3056\u30de\u30b7\u30f3\uff11\uff12\uff15"
        },
        {
            "language": {
                "name": "zh-hant",
                "url": "/api/v2/language/4/"
            },
            "name": "\u62db\u5f0f\u5b66\u4e60\u5668\uff11\uff12\uff15"
        },
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "CT125"
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "TM125"
        },
        {
            "language": {
                "name": "ja",
                "url": "/api/v2/language/11/"
            },
            "name": "\u308f\u3056\u30de\u30b7\u30f3\uff11\uff12\uff15"
        }
    ],
    "sprites": {
        "default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-normal.png"
    }
}

=== PokeAPI/api-data/data/api/v2/item/2056/index.json
{
    "attributes": [],
    "baby_trigger_for": null,
    "category": {
        "name": "picnic",
        "url": "/api/v2/item-category/55/"
    },
    "cost": 800,
    "effect_entries": [],
    "flavor_text_entries": [],
    "fling_effect": null,
    "fling_power": null,
    "game_indices": [
        {
            "game_index": 2357,
            "generation": {
                "name": "generation-ix",
                "url": "/api/v2/generation/9/"
            }
        }
    ],
    "held_by_pokemon": [],
    "id": 2056,
    "machines": [],
    "name": "fire-pattern-cup",
    "names": [
        {
            "language": {
                "name": "ja-hrkt",
                "url": "/api/v2/language/1/"
            },
            "name": "\u30d5\u30a1\u30a4\u30e4\u30fc\u30ab\u30c3\u30d7"
        },
        {
            "language": {
                "name": "zh-hant",
                "url": "/api/v2/language/4/"
            },
            "name": "\u706b\u7130\u6c34\u676f"
        },
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "Tasse \u00e0 Flammes"
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Fire Pattern Cup"
        },
        {
            "language": {
                "name": "ja",
                "url": "/api/v2/language/11/"
            },
            "name": "\u30d5\u30a1\u30a4\u30e4\u30fc\u30ab\u30c3\u30d7"
        }
    ],
    "sprites": {
        "default": null
    }
}

=== PokeAPI/api-data/data/api/v2/item/2279/index.json
{
    "attributes": [],
    "baby_trigger_for": null,
    "category": {
        "name": "type-protection",
        "url": "/api/v2/item-category/7/"
    },
    "cost": 200,
    "effect_entries": [],
    "flavor_text_entries": [],
    "fling_effect": null,
    "fling_power": 10,
    "game_indices": [],
    "held_by_pokemon": [],
    "id": 2279,
    "machines": [],
    "name": "roseli-berry",
    "names": [],
    "sprites": {
        "default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/roseli-berry.png"
    }
}
