=== PokeAPI/api-data/data/schema/v2/item/$id/index.json
{
    "$schema": "http://json-schema.org/schema#",
    "properties": {
        "attributes": {
            "items": {
                "$ref": "/schema/v2/named_api_resource.json"
            },
            "type": "array"
        },
        "baby_trigger_for": {
            "anyOf": [
                {
                    "type": "null"
                },
                {
                    "$ref": "/schema/v2/api_resource.json"
                }
            ]
        },
        "category": {
            "$ref": "/schema/v2/named_api_resource.json"
        },
        "cost": {
            "type": "integer"
        },
        "effect_entries": {
            "items": {
                "$ref": "/schema/v2/verbose_effect.json"
            },
            "type": "array"
        },
        "flavor_text_entries": {
            "items": {
                "$ref": "/schema/v2/version_group_flavor_text.json"
            },
            "type": "array"
        },
        "fling_effect": {
            "anyOf": [
                {
                    "type": "null"
                },
                {
                    "$ref": "/schema/v2/named_api_resource.json"
                }
            ]
        },
        "fling_power": {
            "type": [
                "integer",
                "null"
            ]
        },
        "game_indices": {
            "items": {
                "$ref": "/schema/v2/generation_game_index.json"
            },
            "type": "array"
        },
        "held_by_pokemon": {
            "items": {
                "properties": {
                    "pokemon": {
                        "$ref": "/schema/v2/named_api_resource.json"
                    },
                    "version_details": {
                        "items": {
                            "properties": {
                                "rarity": {
                                    "type": "integer"
                                },
                                "version": {
                                    "$ref": "/schema/v2/named_api_resource.json"
                                }
                            },
                            "required": [
                                "rarity",
                                "version"
                            ],
                            "type": "object"
                        },
                        "type": "array"
                    }
                },
                "required": [
                    "pokemon",
                    "version_details"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "id": {
            "type": "integer"
        },
        "machines": {
            "items": {
                "$ref": "/schema/v2/machine_version_detail.json"
            },
            "type": "array"
        },
        "name": {
            "type": "string"
        },
        "names": {
            "items": {
                "$ref": "/schema/v2/name.json"
            },
            "type": "array"
        },
        "sprites": {
            "properties": {
                "default": {
                    "type": [
                        "null",
                        "string"
                    ]
                }
            },
            "required": [
                "default"
            ],
            "type": "object"
        }
    },
    "required": [
        "attributes",
        "baby_trigger_for",
        "category",
        "cost",
        "effect_entries",
        "flavor_text_entries",
        "fling_effect",
        "fling_power",
        "game_indices",
        "held_by_pokemon",
        "id",
        "machines",
        "name",
        "names",
        "sprites"
    ],
    "type": "object"
}

=== PokeAPI/api-data/data/api/v2/item/1329/index.json
{
    "attributes": [],
    "baby_trigger_for": null,
    "category": {
        "name": "gameplay",
        "url": "/api/v2/item-category/21/"
    },
    "cost": 0,
    "effect_entries": [],
    "flavor_text_entries": [
        {
            "language": {
                "name": "ja-hrkt",
                "url": "/api/v2/language/1/"
            },
            "text": "\u30ed\u30c8\u30e0\u304c\u3000\u3059\u304d\u306a\u3000\u304b\u3067\u3093\u304c\u3000\u306e\u3063\u3066\u3044\u308b\u3002\n\u30ab\u30bf\u30ed\u30b0\u3092\u3000\u3064\u304b\u3046\u3053\u3068\u3067\u3000\u30ed\u30c8\u30e0\u3092\n\u304b\u3067\u3093\u306b\u3000\u3044\u308c\u305f\u308a\u3000\u3060\u3059\u3053\u3068\u304c\u3000\u3067\u304d\u308b\u3002",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        },
        {
            "language": {
                "name": "ko",
                "url": "/api/v2/language/3/"
            },
            "text": "\ub85c\ud1a0\ubb34\uac00 \uc88b\uc544\ud558\ub294 \uac00\uc804\uc81c\ud488\uc774 \uc2e4\ub824 \uc788\ub2e4.\n\uce74\ud0c8\ub85c\uadf8\ub97c \uc0ac\uc6a9\ud558\uba74 \ub85c\ud1a0\ubb34\ub97c\n\uac00\uc804\uc81c\ud488\uc5d0 \ub123\uac70\ub098 \uaebc\ub0bc \uc218 \uc788\ub2e4.",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        },
        {
            "language": {
                "name": "zh-hant",
                "url": "/api/v2/language/4/"
            },
            "text": "\u8a18\u8f09\u8457\u6d1b\u6258\u59c6\u559c\u6b61\u7684\u96fb\u5668\u3002\n\u900f\u904e\u4f7f\u7528\u9019\u672c\u578b\u9304\uff0c\u53ef\u4ee5\u8b93\n\u6d1b\u6258\u59c6\u9032\u5165\u6216\u96e2\u958b\u96fb\u5668\u3002",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        },
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "text": "Un catalogue pr\u00e9sentant divers appareils m\u00e9nagers\nque Motisma appr\u00e9cie. \u00c0 utiliser pour faire entrer\nMotisma dans ces appareils ou l\u2019en faire sortir.",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        },
        {
            "language": {
                "name": "de",
                "url": "/api/v2/language/6/"
            },
            "text": "Ein Katalog, der Rotoms Lieblingsger\u00e4te auflistet.\nMit diesem Katalog kann Rotom in Ger\u00e4te schl\u00fcpfen\nund sie wieder verlassen.",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        },
        {
            "language": {
                "name": "es",
                "url": "/api/v2/language/7/"
            },
            "text": "Un cat\u00e1logo de los artilugios favoritos de Rotom que le\npermite introducirse o salir f\u00e1cilmente de los mismos.",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        },
        {
            "language": {
                "name": "it",
                "url": "/api/v2/language/8/"
            },
            "text": "Contiene una lista degli apparecchi che piacciono\na Rotom. Pu\u00f2 essere usato per far entrare Rotom\nnel motore degli elettrodomestici o per farlo uscire.",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "text": "A catalog of devices that Rotom like. Use the catalog\nto have Rotom hop in and out of the various devices\nlisted within.",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        },
        {
            "language": {
                "name": "ja",
                "url": "/api/v2/language/11/"
            },
            "text": "\u30ed\u30c8\u30e0\u304c\u3000\u597d\u304d\u306a\u3000\u5bb6\u96fb\u304c\u3000\u8f09\u3063\u3066\u3044\u308b\u3002\n\u30ab\u30bf\u30ed\u30b0\u3092\u3000\u4f7f\u3046\u3053\u3068\u3067\u3000\u30ed\u30c8\u30e0\u3092\n\u5bb6\u96fb\u306b\u3000\u3044\u308c\u305f\u308a\u3000\u3060\u3059\u3053\u3068\u304c\u3000\u3067\u304d\u308b\u3002",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        },
        {
            "language": {
                "name": "zh-hans",
                "url": "/api/v2/language/12/"
            },
            "text": "\u4e0a\u9762\u8bb0\u8f7d\u7740\u6d1b\u6258\u59c6\u559c\u6b22\u7684\u5bb6\u7535\u3002\n\u901a\u8fc7\u4f7f\u7528\u8fd9\u672c\u6307\u5357\uff0c\u53ef\u4ee5\n\u8ba9\u6d1b\u6258\u59c6\u6f5c\u5165\u6216\u8131\u79bb\u5bb6\u7535\u3002",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        },
        {
            "language": {
                "name": "es-419",
                "url": "/api/v2/language/14/"
            },
            "text": "Un cat\u00e1logo de los artilugios favoritos de Rotom que le\npermite introducirse o salir f\u00e1cilmente de los mismos.",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        }
    ],
    "fling_effect": null,
    "fling_power": null,
    "game_indices": [
        {
            "game_index": 1278,
            "generation": {
                "name": "generation-viii",
                "url": "/api/v2/generation/8/"
            }
        }
    ],
    "held_by_pokemon": [],
    "id": 1329,
    "machines": [],
    "name": "rotom-catalog",
    "names": [
        {
            "language": {
                "name": "ja-hrkt",
                "url": "/api/v2/language/1/"
            },
            "name": "\u30ed\u30c8\u30e0\u306e\u30ab\u30bf\u30ed\u30b0"
        },
        {
            "language": {
                "name": "ko",
                "url": "/api/v2/language/3/"
            },
            "name": "\ub85c\ud1a0\ubb34\uce74\ud0c8\ub85c\uadf8"
        },
        {
            "language": {
                "name": "zh-hant",
                "url": "/api/v2/language/4/"
            },
            "name": "\u6d1b\u6258\u59c6\u578b\u9304"
        },
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "Moti-Catalogue"
        },
        {
            "language": {
                "name": "de",
                "url": "/api/v2/language/6/"
            },
            "name": "Rotom-Katalog"
        },
        {
            "language": {
                "name": "es",
                "url": "/api/v2/language/7/"
            },
            "name": "Cat\u00e1logo Rotom"
        },
        {
            "language": {
                "name": "it",
                "url": "/api/v2/language/8/"
            },
            "name": "Catalogo Rotom"
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Rotom Catalog"
        },
        {
            "language": {
                "name": "ja",
                "url": "/api/v2/language/11/"
            },
            "name": "\u30ed\u30c8\u30e0\u306e\u30ab\u30bf\u30ed\u30b0"
        },
        {
            "language": {
                "name": "zh-hans",
                "url": "/api/v2/language/12/"
            },
            "name": "\u6d1b\u6258\u59c6\u578b\u5f55"
        },
        {
            "language": {
                "name": "es-419",
                "url": "/api/v2/language/14/"
            },
            "name": "Cat\u00e1logo Rotom"
        }
    ],
    "sprites": {
        "default": null
    }
}

=== PokeAPI/api-data/data/api/v2/item/1250/index.json
{
    "attributes": [],
    "baby_trigger_for": null,
    "category": {
        "name": "all-machines",
        "url": "/api/v2/item-category/37/"
    },
    "cost": 6000,
    "effect_entries": [],
    "flavor_text_entries": [
        {
            "language": {
                "name": "ja-hrkt",
                "url": "/api/v2/language/1/"
            },
            "text": "\u304a\u304a\u304d\u306a\u3000\u304f\u3061\u304b\u3089\u3000\u3057\u3087\u3046\u3052\u304d\u306f\u3092\n\u307e\u304d\u304a\u3053\u3057\u3066\u3000\u3042\u3044\u3066\u3092\u3000\u3053\u3046\u3052\u304d\u3059\u308b\u3002",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        },
        {
            "language": {
                "name": "ko",
                "url": "/api/v2/language/3/"
            },
            "text": "\ud070 \uc785\uc73c\ub85c \ucda9\uaca9\ud30c\ub97c\n\uc77c\uc73c\ucf1c\uc11c \uc0c1\ub300\ub97c \uacf5\uaca9\ud55c\ub2e4.",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        },
        {
            "language": {
                "name": "zh-hant",
                "url": "/api/v2/language/4/"
            },
            "text": "\u5f9e\u5f35\u5927\u7684\u53e3\u4e2d\n\u767c\u5c04\u885d\u64ca\u6ce2\u653b\u64ca\u5c0d\u624b\u3002",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        },
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "text": "Le lanceur ouvre la bouche pour envoyer\nune onde de choc qui frappe l\u2019ennemi.",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        },
        {
            "language": {
                "name": "de",
                "url": "/api/v2/language/6/"
            },
            "text": "Das Ziel wird mit einer Schockwelle angegriffen,\ndie aus dem offenen Maul des Anwenders kommt.",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        },
        {
            "language": {
                "name": "es",
                "url": "/api/v2/language/7/"
            },
            "text": "Abre mucho la boca y libera una onda de choque que\nataca al objetivo.",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        },
        {
            "language": {
                "name": "it",
                "url": "/api/v2/language/8/"
            },
            "text": "Chi la usa spalanca la bocca e genera un\u2019onda\nd\u2019urto che colpisce il bersaglio.",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "text": "The target is attacked with a shock wave generated\nby the user\u2019s gaping mouth.",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        },
        {
            "language": {
                "name": "ja",
                "url": "/api/v2/language/11/"
            },
            "text": "\u5927\u304d\u306a\u3000\u53e3\u304b\u3089\u3000\u885d\u6483\u6ce2\u3092\n\u307e\u304d\u304a\u3053\u3057\u3066\u3000\u76f8\u624b\u3092\u3000\u653b\u6483\u3059\u308b\u3002",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        },
        {
            "language": {
                "name": "zh-hans",
                "url": "/api/v2/language/12/"
            },
            "text": "\u4ece\u5927\u5927\u7684\u53e3\u4e2d\n\u6380\u8d77\u51b2\u51fb\u6ce2\u653b\u51fb\u5bf9\u624b\u3002",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        },
        {
            "language": {
                "name": "es-419",
                "url": "/api/v2/language/14/"
            },
            "text": "Abre mucho la boca y libera una onda de choque que\nataca al objetivo.",
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        }
    ],
    "fling_effect": null,
    "fling_power": 85,
    "game_indices": [
        {
            "game_index": 1192,
            "generation": {
                "name": "generation-viii",
                "url": "/api/v2/generation/8/"
            }
        }
    ],
    "held_by_pokemon": [],
    "id": 1250,
    "machines": [
        {
            "machine": {
                "url": "/api/v2/machine/1761/"
            },
            "version_group": {
                "name": "sword-shield",
                "url": "/api/v2/version-group/20/"
            }
        }
    ],
    "name": "tr62",
    "names": [
        {
            "language": {
                "name": "ja-hrkt",
                "url": "/api/v2/language/1/"
            },
            "name": "\u308f\u3056\u30ec\u30b3\u30fc\u30c9\uff16\uff12"
        },
        {
            "language": {
                "name": "ko",
                "url": "/api/v2/language/3/"
            },
            "name": "\uae30\uc220\ub808\ucf54\ub4dc62"
        },
        {
            "language": {
                "name": "zh-hant",
                "url": "/api/v2/language/4/"
            },
            "name": "\u62db\u5f0f\u7d00\u9304\uff16\uff12"
        },
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "DT62"
        },
        {
            "language": {
                "name": "de",
                "url": "/api/v2/language/6/"
            },
            "name": "TP62"
        },
        {
            "language": {
                "name": "es",
                "url": "/api/v2/language/7/"
            },
            "name": "DT62"
        },
        {
            "language": {
                "name": "it",
                "url": "/api/v2/language/8/"
            },
            "name": "DT62"
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "TR62"
        },
        {
            "language": {
                "name": "ja",
                "url": "/api/v2/language/11/"
            },
            "name": "\u308f\u3056\u30ec\u30b3\u30fc\u30c9\uff16\uff12"
        },
        {
            "language": {
                "name": "zh-hans",
                "url": "/api/v2/language/12/"
            },
            "name": "\u62db\u5f0f\u8bb0\u5f55\uff16\uff12"
        },
        {
            "language": {
                "name": "es-419",
                "url": "/api/v2/language/14/"
            },
            "name": "DT62"
        }
    ],
    "sprites": {
        "default": null
    }
}

=== PokeAPI/api-data/data/api/v2/item/1818/index.json
{
    "attributes": [],
    "baby_trigger_for": null,
    "category": {
        "name": "tm-materials",
        "url": "/api/v2/item-category/54/"
    },
    "cost": 80,
    "effect_entries": [],
    "flavor_text_entries": [],
    "fling_effect": null,
    "fling_power": null,
    "game_indices": [
        {
            "game_index": 2012,
            "generation": {
                "name": "generation-ix",
                "url": "/api/v2/generation/9/"
            }
        }
    ],
    "held_by_pokemon": [],
    "id": 1818,
    "machines": [],
    "name": "shuppet-scrap",
    "names": [
        {
            "language": {
                "name": "ja-hrkt",
                "url": "/api/v2/language/1/"
            },
            "name": "\u30ab\u30b2\u30dc\u30a6\u30ba\u306e\u304d\u308c\u306f\u3057"
        },
        {
            "language": {
                "name": "zh-hant",
                "url": "/api/v2/language/4/"
            },
            "name": "\u6028\u5f71\u5a03\u5a03\u7684\u6b8b\u7247"
        },
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "Tissu de Polichombr"
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Shuppet Scrap"
        },
        {
            "language": {
                "name": "ja",
                "url": "/api/v2/language/11/"
            },
            "name": "\u30ab\u30b2\u30dc\u30a6\u30ba\u306e\u304d\u308c\u306f\u3057"
        }
    ],
    "sprites": {
        "default": null
    }
}

=== PokeAPI/api-data/data/api/v2/item/1933/index.json
{
    "attributes": [],
    "baby_trigger_for": null,
    "category": {
        "name": "tm-materials",
        "url": "/api/v2/item-category/54/"
    },
    "cost": 120,
    "effect_entries": [],
    "flavor_text_entries": [],
    "fling_effect": null,
    "fling_power": null,
    "game_indices": [
        {
            "game_index": 2132,
            "generation": {
                "name": "generation-ix",
                "url": "/api/v2/generation/9/"
            }
        }
    ],
    "held_by_pokemon": [],
    "id": 1933,
    "machines": [],
    "name": "glimmet-crystal",
    "names": [
        {
            "language": {
                "name": "ja-hrkt",
                "url": "/api/v2/language/1/"
            },
            "name": "\u30ad\u30e9\u30fc\u30e1\u306e\u3051\u3063\u3057\u3087\u3046"
        },
        {
            "language": {
                "name": "zh-hant",
                "url": "/api/v2/language/4/"
            },
            "name": "\u6676\u5149\u82bd\u7684\u7ed3\u6676"
        },
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "Cristal de Germ\u00e9clat"
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Glimmet Crystal"
        },
        {
            "language": {
                "name": "ja",
                "url": "/api/v2/language/11/"
            },
            "name": "\u30ad\u30e9\u30fc\u30e1\u306e\u3051\u3063\u3057\u3087\u3046"
        }
    ],
    "sprites": {
        "default": null
    }
}

=== PokeAPI/api-data/data/api/v2/item/2137/index.json
{
    "attributes": [],
    "baby_trigger_for": null,
    "category": {
        "name": "tm-materials",
        "url": "/api/v2/item-category/54/"
    },
    "cost": 20,
    "effect_entries": [],
    "flavor_text_entries": [],
    "fling_effect": null,
    "fling_power": null,
    "game_indices": [
        {
            "game_index": 2456,
            "generation": {
                "name": "generation-ix",
                "url": "/api/v2/generation/9/"
            }
        }
    ],
    "held_by_pokemon": [],
    "id": 2137,
    "machines": [],
    "name": "lotad-leaf",
    "names": [
        {
            "language": {
                "name": "ja-hrkt",
                "url": "/api/v2/language/1/"
            },
            "name": "\u30cf\u30b9\u30dc\u30fc\u306e\u306f\u3063\u3071"
        },
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "Feuille de N\u00e9nupiot"
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Lotad Leaf"
        },
        {
            "language": {
                "name": "ja",
                "url": "/api/v2/language/11/"
            },
            "name": "\u30cf\u30b9\u30dc\u30fc\u306e\u306f\u3063\u3071"
        }
    ],
    "sprites": {
        "default": null
    }
}
