=== PokeAPI/api-data/data/schema/v2/pokemon-shape/$id/index.json
{
    "$schema": "http://json-schema.org/schema#",
    "properties": {
        "awesome_names": {
            "items": {
                "properties": {
                    "awesome_name": {
                        "type": "string"
                    },
                    "language": {
                        "$ref": "/schema/v2/named_api_resource.json"
                    }
                },
                "required": [
                    "awesome_name",
                    "language"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "id": {
            "type": "integer"
        },
        "name": {
            "type": "string"
        },
        "names": {
            "items": {
                "properties": {
                    "language": {
                        "$ref": "/schema/v2/named_api_resource.json"
                    },
                    "name": {
                        "type": "string"
                    }
                },
                "required": [
                    "language",
                    "name"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "pokemon_species": {
            "items": {
                "$ref": "/schema/v2/named_api_resource.json"
            },
            "type": "array"
        }
    },
    "required": [
        "awesome_names",
        "id",
        "name",
        "names",
        "pokemon_species"
    ],
    "type": "object"
}

=== PokeAPI/api-data/data/api/v2/pokemon-shape/12/index.json
{
    "awesome_names": [
        {
            "awesome_name": "Anthropomorphique",
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            }
        },
        {
            "awesome_name": "Anthropomorphic",
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            }
        }
    ],
    "id": 12,
    "name": "humanoid",
    "names": [
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "Humano\u00efde"
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Humanoid"
        }
    ],
    "pokemon_species": [
        {
            "name": "venonat",
            "url": "/api/v2/pokemon-species/48/"
        },
        {
            "name": "bellsprout",
            "url": "/api/v2/pokemon-species/69/"
        },
        {
            "name": "jigglypuff",
            "url": "/api/v2/pokemon-species/39/"
        },
        {
            "name": "wigglytuff",
            "url": "/api/v2/pokemon-species/40/"
        },
        {
            "name": "gloom",
            "url": "/api/v2/pokemon-species/44/"
        },
        {
            "name": "vileplume",
            "url": "/api/v2/pokemon-species/45/"
        },
        {
            "name": "poliwhirl",
            "url": "/api/v2/pokemon-species/61/"
        },
        {
            "name": "poliwrath",
            "url": "/api/v2/pokemon-species/62/"
        },
        {
            "name": "alakazam",
            "url": "/api/v2/pokemon-species/65/"
        },
        {
            "name": "machoke",
            "url": "/api/v2/pokemon-species/67/"
        },
        {
            "name": "machamp",
            "url": "/api/v2/pokemon-species/68/"
        },
        {
            "name": "graveler",
            "url": "/api/v2/pokemon-species/75/"
        },
        {
            "name": "greninja",
            "url": "/api/v2/pokemon-species/658/"
        },
        {
            "name": "drowzee",
            "url": "/api/v2/pokemon-species/96/"
        },
        {
            "name": "pinsir",
            "url": "/api/v2/pokemon-species/127/"
        },
        {
            "name": "hypno",
            "url": "/api/v2/pokemon-species/97/"
        },
        {
            "name": "hitmonlee",
            "url": "/api/v2/pokemon-species/106/"
        },
        {
            "name": "hitmonchan",
            "url": "/api/v2/pokemon-species/107/"
        },
        {
            "name": "mr-mime",
            "url": "/api/v2/pokemon-species/122/"
        },
        {
            "name": "jynx",
            "url": "/api/v2/pokemon-species/124/"
        },
        {
            "name": "snorlax",
            "url": "/api/v2/pokemon-species/143/"
        },
        {
            "name": "cyndaquil",
            "url": "/api/v2/pokemon-species/155/"
        },
        {
            "name": "igglybuff",
            "url": "/api/v2/pokemon-species/174/"
        },
        {
            "name": "togepi",
            "url": "/api/v2/pokemon-species/175/"
        },
        {
            "name": "snubbull",
            "url": "/api/v2/pokemon-species/209/"
        },
        {
            "name": "heracross",
            "url": "/api/v2/pokemon-species/214/"
        },
        {
            "name": "togetic",
            "url": "/api/v2/pokemon-species/176/"
        },
        {
            "name": "bellossom",
            "url": "/api/v2/pokemon-species/182/"
        },
        {
            "name": "sudowoodo",
            "url": "/api/v2/pokemon-species/185/"
        },
        {
            "name": "politoed",
            "url": "/api/v2/pokemon-species/186/"
        },
        {
            "name": "sunflora",
            "url": "/api/v2/pokemon-species/192/"
        },
        {
            "name": "tyrogue",
            "url": "/api/v2/pokemon-species/236/"
        },
        {
            "name": "smoochum",
            "url": "/api/v2/pokemon-species/238/"
        },
        {
            "name": "elekid",
            "url": "/api/v2/pokemon-species/239/"
        },
        {
            "name": "celebi",
            "url": "/api/v2/pokemon-species/251/"
        },
        {
            "name": "ralts",
            "url": "/api/v2/pokemon-species/280/"
        },
        {
            "name": "makuhita",
            "url": "/api/v2/pokemon-species/296/"
        },
        {
            "name": "nosepass",
            "url": "/api/v2/pokemon-species/299/"
        },
        {
            "name": "blissey",
            "url": "/api/v2/pokemon-species/242/"
        },
        {
            "name": "lombre",
            "url": "/api/v2/pokemon-species/271/"
        },
        {
            "name": "ludicolo",
            "url": "/api/v2/pokemon-species/272/"
        },
        {
            "name": "nuzleaf",
            "url": "/api/v2/pokemon-species/274/"
        },
        {
            "name": "shiftry",
            "url": "/api/v2/pokemon-species/275/"
        },
        {
            "name": "kirlia",
            "url": "/api/v2/pokemon-species/281/"
        },
        {
            "name": "gardevoir",
            "url": "/api/v2/pokemon-species/282/"
        },
        {
            "name": "slaking",
            "url": "/api/v2/pokemon-species/289/"
        },
        {
            "name": "hariyama",
            "url": "/api/v2/pokemon-species/297/"
        },
        {
            "name": "sableye",
            "url": "/api/v2/pokemon-species/302/"
        },
        {
            "name": "mawile",
            "url": "/api/v2/pokemon-species/303/"
        },
        {
            "name": "meditite",
            "url": "/api/v2/pokemon-species/307/"
        },
        {
            "name": "illumise",
            "url": "/api/v2/pokemon-species/314/"
        },
        {
            "name": "cacnea",
            "url": "/api/v2/pokemon-species/331/"
        },
        {
            "name": "snorunt",
            "url": "/api/v2/pokemon-species/361/"
        },
        {
            "name": "bagon",
            "url": "/api/v2/pokemon-species/371/"
        },
        {
            "name": "medicham",
            "url": "/api/v2/pokemon-species/308/"
        },
        {
            "name": "roselia",
            "url": "/api/v2/pokemon-species/315/"
        },
        {
            "name": "cacturne",
            "url": "/api/v2/pokemon-species/332/"
        },
        {
            "name": "dusclops",
            "url": "/api/v2/pokemon-species/356/"
        },
        {
            "name": "regirock",
            "url": "/api/v2/pokemon-species/377/"
        },
        {
            "name": "regice",
            "url": "/api/v2/pokemon-species/378/"
        },
        {
            "name": "registeel",
            "url": "/api/v2/pokemon-species/379/"
        },
        {
            "name": "jirachi",
            "url": "/api/v2/pokemon-species/385/"
        },
        {
            "name": "deoxys",
            "url": "/api/v2/pokemon-species/386/"
        },
        {
            "name": "piplup",
            "url": "/api/v2/pokemon-species/393/"
        },
        {
            "name": "kricketot",
            "url": "/api/v2/pokemon-species/401/"
        },
        {
            "name": "budew",
            "url": "/api/v2/pokemon-species/406/"
        },
        {
            "name": "chingling",
            "url": "/api/v2/pokemon-species/433/"
        },
        {
            "name": "mime-jr",
            "url": "/api/v2/pokemon-species/439/"
        },
        {
            "name": "happiny",
            "url": "/api/v2/pokemon-species/440/"
        },
        {
            "name": "munchlax",
            "url": "/api/v2/pokemon-species/446/"
        },
        {
            "name": "croagunk",
            "url": "/api/v2/pokemon-species/453/"
        },
        {
            "name": "roserade",
            "url": "/api/v2/pokemon-species/407/"
        },
        {
            "name": "regigigas",
            "url": "/api/v2/pokemon-species/486/"
        },
        {
            "name": "manaphy",
            "url": "/api/v2/pokemon-species/490/"
        },
        {
            "name": "darkrai",
            "url": "/api/v2/pokemon-species/491/"
        },
        {
            "name": "victini",
            "url": "/api/v2/pokemon-species/494/"
        },
        {
            "name": "lickilicky",
            "url": "/api/v2/pokemon-species/463/"
        },
        {
            "name": "tangrowth",
            "url": "/api/v2/pokemon-species/465/"
        },
        {
            "name": "gallade",
            "url": "/api/v2/pokemon-species/475/"
        },
        {
            "name": "musharna",
            "url": "/api/v2/pokemon-species/518/"
        },
        {
            "name": "excadrill",
            "url": "/api/v2/pokemon-species/530/"
        },
        {
            "name": "timburr",
            "url": "/api/v2/pokemon-species/532/"
        },
        {
            "name": "throh",
            "url": "/api/v2/pokemon-species/538/"
        },
        {
            "name": "sawk",
            "url": "/api/v2/pokemon-species/539/"
        },
        {
            "name": "darumaka",
            "url": "/api/v2/pokemon-species/554/"
        },
        {
            "name": "trubbish",
            "url": "/api/v2/pokemon-species/568/"
        },
        {
            "name": "gothita",
            "url": "/api/v2/pokemon-species/574/"
        },
        {
            "name": "karrablast",
            "url": "/api/v2/pokemon-species/588/"
        },
        {
            "name": "conkeldurr",
            "url": "/api/v2/pokemon-species/534/"
        },
        {
            "name": "seismitoad",
